/**
 * Complete 58-Wilaya Agricultural & Pedological Registry for Algeria
 * With GPS Centroids, SVG Map Polygon Projections, Soil Classes & Agronomic Metrics.
 */

import { AlgeriaAgroZone, AlgeriaSoilClass, AlgeriaBioclimate, MajorCropCategory } from './algeria-map-data';

export interface WilayaDataFull {
  code: number;
  codeStr: string;
  id: string;
  nameEn: string;
  nameAr: string;
  nameFr: string;
  capitalEn: string;
  capitalAr: string;
  capitalFr: string;
  zone: AlgeriaAgroZone;
  lat: number;
  lng: number;
  
  // Agricultural & Pedological Specs
  dominantSoil: AlgeriaSoilClass;
  soilNameFr: string;
  soilNameAr: string;
  textureFr: string;
  textureAr: string;
  ph: number;
  omPct: number;
  limePct: number;
  salinityEC: number;
  whcMm: number;
  salinityRisk: 'none' | 'low' | 'moderate' | 'high' | 'severe';
  erosionRisk: 'low' | 'moderate' | 'high' | 'severe';

  // Climate Specs
  bioclimate: AlgeriaBioclimate;
  rainfallMm: number;
  tempSummer: number;
  tempWinter: number;
  et0: number;
  frostDays: number;
  siroccoDays: number;

  // Crops & Specialty
  dominantCrops: MajorCropCategory[];
  keyProduceFr: string;
  keyProduceAr: string;
  agronomicHighlightFr: string;
  agronomicHighlightAr: string;

  // Water
  waterSourceFr: string;
  waterSourceAr: string;
  damOrBasinFr: string;

  // SVG representation relative coordinates (0-1000 x 0-1000 canvas)
  svgCentroid: { x: number; y: number };
  svgPolygonPath?: string;
}

export const projectCoordinates = (lat: number, lng: number) => {
  const minLng = -8.7;
  const maxLng = 12.0;
  const minLat = 18.8;
  const maxLat = 37.3;

  const x = ((lng - minLng) / (maxLng - minLng)) * 740 + 30;
  const y = ((maxLat - lat) / (maxLat - minLat)) * 740 + 30;
  return { x, y };
};

export const ALL_58_WILAYAS: WilayaDataFull[] = [
  {
    code: 1,
    codeStr: '01',
    id: 'adrar',
    nameEn: 'Adrar',
    nameAr: 'أدرار',
    nameFr: 'Adrar',
    capitalEn: 'Adrar',
    capitalAr: 'أدرار',
    capitalFr: 'Adrar',
    zone: 'deep_sahara',
    lat: 27.87,
    lng: -0.29,
    dominantSoil: 'arenosol',
    soilNameFr: 'Sables éoliens & limons d’oasis',
    soilNameAr: 'رمال صحراوية وطمي الواحات',
    textureFr: 'Sableux à sablo-limoneux',
    textureAr: 'رملية إلى رملية طميية',
    ph: 8.2,
    omPct: 0.3,
    limePct: 12.0,
    salinityEC: 3.8,
    whcMm: 55,
    salinityRisk: 'moderate',
    erosionRisk: 'severe',
    bioclimate: 'hyper_arid',
    rainfallMm: 15,
    tempSummer: 45,
    tempWinter: 12,
    et0: 7.8,
    frostDays: 1,
    siroccoDays: 42,
    dominantCrops: ['cereals', 'pivot_potato', 'date_palms', 'livestock'],
    keyProduceFr: 'Blé sous pivot géant, Dattes, Maïs grain, Luzerne',
    keyProduceAr: 'قمح بالري المحوري، تمور، ذرة حبوب، فصة علفية',
    agronomicHighlightFr: 'Pôle stratégique céréalier exploitant la nappe fossile de l’Albien.',
    agronomicHighlightAr: 'قطب حبوبي استراتيجي يعتمد على المياه الجوفية العميقة لطبقة الألبيان.',
    waterSourceFr: 'Nappe de l’Albien & Foggaras',
    waterSourceAr: 'طبقة الألبيان والفقارات',
    damOrBasinFr: 'Continental Intercalaire',
    svgCentroid: { x: 380, y: 520 },
  },
  {
    code: 2,
    codeStr: '02',
    id: 'chlef',
    nameEn: 'Chlef',
    nameAr: 'الشلف',
    nameFr: 'Chlef',
    capitalEn: 'Chlef',
    capitalAr: 'الشلف',
    capitalFr: 'Chlef',
    zone: 'tell_coastal',
    lat: 36.16,
    lng: 1.33,
    dominantSoil: 'fluvisol',
    soilNameFr: 'Alluvions du Chéliff & vertisols calciques',
    soilNameAr: 'طمي وادي الشلف الفيضي وتربة التيرس الكلسية',
    textureFr: 'Argilo-limoneux',
    textureAr: 'طميية طينية إلى طينية',
    ph: 7.9,
    omPct: 1.8,
    limePct: 14.5,
    salinityEC: 2.4,
    whcMm: 175,
    salinityRisk: 'moderate',
    erosionRisk: 'moderate',
    bioclimate: 'semi_arid',
    rainfallMm: 420,
    tempSummer: 38,
    tempWinter: 8,
    et0: 4.6,
    frostDays: 4,
    siroccoDays: 18,
    dominantCrops: ['citrus', 'greenhouses', 'cereals', 'olives'],
    keyProduceFr: 'Oranges Navel & Valencia, Tomate industrielle, Céréales',
    keyProduceAr: 'برتقال نافيل وفالنسيا، طماطم صناعية، حبوب',
    agronomicHighlightFr: 'Grande plaine alluviale irrigable avec forte vocation agrumicole et maraîchère.',
    agronomicHighlightAr: 'سهل فيضي شاسع مجهز بالسقي ذو إنتاجية عالية للحمضيات والخضار.',
    waterSourceFr: 'Barrage Sidi Yacoub & Oued Chéliff',
    waterSourceAr: 'سد سيدي يعقوب ووادي الشلف',
    damOrBasinFr: 'Bassin versant du Chéliff',
    svgCentroid: { x: 450, y: 130 },
  },
  {
    code: 3,
    codeStr: '03',
    id: 'laghouat',
    nameEn: 'Laghouat',
    nameAr: 'الأغواط',
    nameFr: 'Laghouat',
    capitalEn: 'Laghouat',
    capitalAr: 'الأغواط',
    capitalFr: 'Laghouat',
    zone: 'high_plateaus',
    lat: 33.80,
    lng: 2.87,
    dominantSoil: 'calcisol',
    soilNameFr: 'Calcisols steppiques & limons d’oasis',
    soilNameAr: 'تربة جيرية سهوبية وطمي الواحات',
    textureFr: 'Sablo-argilo-limoneux',
    textureAr: 'رملية طينية طميية',
    ph: 8.1,
    omPct: 0.9,
    limePct: 18.0,
    salinityEC: 2.8,
    whcMm: 110,
    salinityRisk: 'moderate',
    erosionRisk: 'high',
    bioclimate: 'arid',
    rainfallMm: 180,
    tempSummer: 40,
    tempWinter: 4,
    et0: 5.4,
    frostDays: 12,
    siroccoDays: 26,
    dominantCrops: ['livestock', 'arboriculture', 'cereals'],
    keyProduceFr: 'Élevage ovin Ouled Djellal, Abricots d’Aflou, Luzerne',
    keyProduceAr: 'أغنام أولاد جلال، مشمش آفلو الجبلي، فصة',
    agronomicHighlightFr: 'Zone de transition agro-pastorale avec arboriculture fruitière d’altitude.',
    agronomicHighlightAr: 'منطقة رعوية وزراعية انتقالية تتميز ببساتين المشمش والفاكهة الجبلية.',
    waterSourceFr: 'Forages Albien & Oued M’zi',
    waterSourceAr: 'آبار الألبيان ووادي مزي',
    damOrBasinFr: 'Oued M’zi & Bassin de l’Atlas',
    svgCentroid: { x: 500, y: 240 },
  },
  {
    code: 4,
    codeStr: '04',
    id: 'oum_el_bouaghi',
    nameEn: 'Oum El Bouaghi',
    nameAr: 'أم البواقي',
    nameFr: 'Oum El Bouaghi',
    capitalEn: 'Oum El Bouaghi',
    capitalAr: 'أم البواقي',
    capitalFr: 'Oum El Bouaghi',
    zone: 'high_plateaus',
    lat: 35.87,
    lng: 7.11,
    dominantSoil: 'calcisol',
    soilNameFr: 'Calcisols bruns & rendzines des hautes plaines',
    soilNameAr: 'تربة بنية جيرية ورندزينا بالسهول المرتفعة',
    textureFr: 'Argilo-limoneux calcaire',
    textureAr: 'طميية طينية كلسية',
    ph: 8.2,
    omPct: 1.4,
    limePct: 24.0,
    salinityEC: 1.8,
    whcMm: 140,
    salinityRisk: 'low',
    erosionRisk: 'moderate',
    bioclimate: 'semi_arid',
    rainfallMm: 350,
    tempSummer: 36,
    tempWinter: 1,
    et0: 4.5,
    frostDays: 28,
    siroccoDays: 15,
    dominantCrops: ['cereals', 'livestock', 'pivot_potato'],
    keyProduceFr: 'Blé dur, Orge, Légumineuses sèches (Pois chiche, Lentille)',
    keyProduceAr: 'قمح صلب، شعير، بقوليات جافة (حمص، عدس)',
    agronomicHighlightFr: 'Grand bassin céréalier oriental avec élevage ovin et cultures de plein champ.',
    agronomicHighlightAr: 'حوض حبوبي شرقي بارز مع تربية الأغنام وزراعة البقوليات.',
    waterSourceFr: 'Barrage Ourkis & Forages profonds',
    waterSourceAr: 'سد أوركيد والآبار العميقة',
    damOrBasinFr: 'Barrage Ourkis',
    svgCentroid: { x: 670, y: 145 },
  },
  {
    code: 5,
    codeStr: '05',
    id: 'batna',
    nameEn: 'Batna',
    nameAr: 'باتنة',
    nameFr: 'Batna',
    capitalEn: 'Batna',
    capitalAr: 'باتنة',
    capitalFr: 'Batna',
    zone: 'mountains',
    lat: 35.55,
    lng: 6.17,
    dominantSoil: 'luvisol',
    soilNameFr: 'Sols bruns de montagne & calcisols des vallées',
    soilNameAr: 'تربة بنية جبلية وكلسية في الوديان',
    textureFr: 'Argilo-limoneux à caillouteux',
    textureAr: 'طميية طينية إلى حصوية',
    ph: 7.8,
    omPct: 2.1,
    limePct: 16.0,
    salinityEC: 1.0,
    whcMm: 150,
    salinityRisk: 'low',
    erosionRisk: 'high',
    bioclimate: 'semi_arid',
    rainfallMm: 410,
    tempSummer: 35,
    tempWinter: 0,
    et0: 4.3,
    frostDays: 35,
    siroccoDays: 12,
    dominantCrops: ['arboriculture', 'cereals', 'livestock', 'olives'],
    keyProduceFr: 'Pommes de l’Aurès, Abricots de N’Gaous, Céréales, Aviculture',
    keyProduceAr: 'تفاح الأوراس، مشمش نقاوس، حبوب، دواجن',
    agronomicHighlightFr: 'Capitale nationale de l’arboriculture fruitière d’altitude et de l’aviculture.',
    agronomicHighlightAr: 'عاصمة وطنية لإنتاج التفاحيات وفاكهة المرتفعات وشعبة الدواجن.',
    waterSourceFr: 'Barrage Koudiet Medaouar & Sources de l’Aurès',
    waterSourceAr: 'سد كدية مداور وينابيع الأوراس',
    damOrBasinFr: 'Barrage Timgad / Koudiet Medaouar',
    svgCentroid: { x: 630, y: 160 },
  },
  {
    code: 6,
    codeStr: '06',
    id: 'bejaia',
    nameEn: 'Béjaïa',
    nameAr: 'بجاية',
    nameFr: 'Béjaïa',
    capitalEn: 'Béjaïa',
    capitalAr: 'بجاية',
    capitalFr: 'Béjaïa',
    zone: 'mountains',
    lat: 36.75,
    lng: 5.06,
    dominantSoil: 'luvisol',
    soilNameFr: 'Sols rouges fersiallitiques & alluvions de la Soummam',
    soilNameAr: 'تربة حمراء متوسطية وطمي وادي الصومام',
    textureFr: 'Argilo-limoneux riche',
    textureAr: 'طميية طينية خصبة',
    ph: 7.2,
    omPct: 2.7,
    limePct: 6.5,
    salinityEC: 0.8,
    whcMm: 180,
    salinityRisk: 'none',
    erosionRisk: 'high',
    bioclimate: 'humid',
    rainfallMm: 880,
    tempSummer: 31,
    tempWinter: 8,
    et0: 3.7,
    frostDays: 3,
    siroccoDays: 8,
    dominantCrops: ['olives', 'arboriculture', 'citrus', 'greenhouses'],
    keyProduceFr: 'Huile d’olive AOC Soummam, Figues sèches, Maraîchage côtier',
    keyProduceAr: 'زيت زيتون الصومام الممتاز، تين جاف، خضار ساحلية',
    agronomicHighlightFr: 'Vallée fertile de la Soummam et massifs oléicoles d’excellence.',
    agronomicHighlightAr: 'وادي الصومام الخصيب وأعرق بساتين الزيتون وإنتاج الزيت بالجزائر.',
    waterSourceFr: 'Barrage Tichy-Haf & Oued Soummam',
    waterSourceAr: 'سد تيشي حاف ووادي الصومام',
    damOrBasinFr: 'Bassin versant de la Soummam',
    svgCentroid: { x: 575, y: 115 },
  },
  {
    code: 7,
    codeStr: '07',
    id: 'biskra',
    nameEn: 'Biskra',
    nameAr: 'بسكرة',
    nameFr: 'Biskra',
    capitalEn: 'Biskra',
    capitalAr: 'بسكرة',
    capitalFr: 'Biskra',
    zone: 'sahara_oasis',
    lat: 34.85,
    lng: 5.73,
    dominantSoil: 'arenosol',
    soilNameFr: 'Sols gypso-sableux des Ziban & limons d’oasis',
    soilNameAr: 'تربة الزيبان الجبسية الرملية وطمي الواحات',
    textureFr: 'Sablo-limoneux à gypseux',
    textureAr: 'رملية طميية إلى جبسية',
    ph: 8.0,
    omPct: 0.7,
    limePct: 16.5,
    salinityEC: 3.6,
    whcMm: 85,
    salinityRisk: 'high',
    erosionRisk: 'high',
    bioclimate: 'arid',
    rainfallMm: 130,
    tempSummer: 44,
    tempWinter: 11,
    et0: 6.2,
    frostDays: 2,
    siroccoDays: 35,
    dominantCrops: ['greenhouses', 'date_palms', 'pivot_potato', 'arboriculture'],
    keyProduceFr: 'Tomates & Poivrons primeurs sous serres, Dattes Deglet Nour de Tolga',
    keyProduceAr: 'طماطم وفلفل البيوت البلاستيكية، تمور دقلة نور بطولقة',
    agronomicHighlightFr: 'La Californie algérienne : 1er producteur national de légumes primeurs sous serres.',
    agronomicHighlightAr: 'كاليفورنيا الجزائر: القطب الأول لإنتاج الخضروات المحمية المبكرة وتمور دقلة نور.',
    waterSourceFr: 'Barrages Foum El Gherza & Fontaine des Gazelles, Nappe Albienne',
    waterSourceAr: 'سدود فم الخرزة وعين الغزال وآبار الألبيان',
    damOrBasinFr: 'Bassin du Chott Melghir',
    svgCentroid: { x: 620, y: 200 },
  },
  {
    code: 8,
    codeStr: '08',
    id: 'bechar',
    nameEn: 'Béchar',
    nameAr: 'بشار',
    nameFr: 'Béchar',
    capitalEn: 'Béchar',
    capitalAr: 'بشار',
    capitalFr: 'Béchar',
    zone: 'deep_sahara',
    lat: 31.62,
    lng: -2.22,
    dominantSoil: 'lithosol',
    soilNameFr: 'Sols alluviaux de la Saoura & regs rocailleux',
    soilNameAr: 'طمي وادي الساورة الفيضي والرقوق الصخرية',
    textureFr: 'Sablo-graveleux à limoneux',
    textureAr: 'رملية حصوية إلى طميية',
    ph: 8.1,
    omPct: 0.4,
    limePct: 15.0,
    salinityEC: 3.2,
    whcMm: 65,
    salinityRisk: 'moderate',
    erosionRisk: 'high',
    bioclimate: 'hyper_arid',
    rainfallMm: 80,
    tempSummer: 44,
    tempWinter: 7,
    et0: 6.7,
    frostDays: 4,
    siroccoDays: 30,
    dominantCrops: ['date_palms', 'livestock', 'cereals', 'greenhouses'],
    keyProduceFr: 'Dattes Feggous & Hmira, Céréales sous pivot, Élevage camelin/ovin',
    keyProduceAr: 'تمور الفقوس والحميرة، قمح محوري، تربية الإبل والأغنام',
    agronomicHighlightFr: 'Oasis de la Saoura et périmètres de mise en valeur agricole saharienne.',
    agronomicHighlightAr: 'واحات وادي الساورة ومشاريع الاستصلاح الزراعي الصحراوي الحديثة.',
    waterSourceFr: 'Barrage Djorf Torba & Nappe de la Saoura',
    waterSourceAr: 'سد جرف التربة ومياه الساورة الجوفية',
    damOrBasinFr: 'Barrage Djorf Torba',
    svgCentroid: { x: 280, y: 340 },
  },
  {
    code: 9,
    codeStr: '09',
    id: 'blida',
    nameEn: 'Blida',
    nameAr: 'البليدة',
    nameFr: 'Blida',
    capitalEn: 'Blida',
    capitalAr: 'البليدة',
    capitalFr: 'Blida',
    zone: 'tell_coastal',
    lat: 36.47,
    lng: 2.83,
    dominantSoil: 'vertisol',
    soilNameFr: 'Tirs noirs et gris profonds de la Mitidja',
    soilNameAr: 'تربة التيرس السوداء والرمادية بسهل متيجة',
    textureFr: 'Argile lourde',
    textureAr: 'طين ثقيل عالي الخصوبة',
    ph: 7.7,
    omPct: 2.4,
    limePct: 8.5,
    salinityEC: 1.1,
    whcMm: 195,
    salinityRisk: 'low',
    erosionRisk: 'low',
    bioclimate: 'humid',
    rainfallMm: 780,
    tempSummer: 33,
    tempWinter: 9,
    et0: 3.8,
    frostDays: 2,
    siroccoDays: 10,
    dominantCrops: ['citrus', 'greenhouses', 'arboriculture', 'cereals'],
    keyProduceFr: 'Clémentines de la Mitidja, Pommes de terre primeurs, Raisin de table',
    keyProduceAr: 'كليمونتين متيجة الشهير، بطاطا مبكرة، عنب المائدة',
    agronomicHighlightFr: 'Cœur battant de la plaine de la Mitidja, sol d’une exceptionnelle fertilité.',
    agronomicHighlightAr: 'قلب سهل متيجة الزراعي الخصيب، موطن الحمضيات والخضار المبكرة.',
    waterSourceFr: 'Nappe de la Mitidja & Barrage Bouroumi',
    waterSourceAr: 'الطبقة الجوفية لمتيجة وسد بورومي',
    damOrBasinFr: 'Plaine de la Mitidja',
    svgCentroid: { x: 490, y: 125 },
  },
  {
    code: 10,
    codeStr: '10',
    id: 'bouira',
    nameEn: 'Bouira',
    nameAr: 'البويرة',
    nameFr: 'Bouira',
    capitalEn: 'Bouira',
    capitalAr: 'البويرة',
    capitalFr: 'Bouira',
    zone: 'tell_coastal',
    lat: 36.37,
    lng: 3.90,
    dominantSoil: 'cambisol',
    soilNameFr: 'Sols bruns de piémont & alluvions de la plaine des Issers',
    soilNameAr: 'تربة بنية لسفوح الجبال وطمي سهل يسر',
    textureFr: 'Argilo-limoneux',
    textureAr: 'طميية طينية',
    ph: 7.6,
    omPct: 2.0,
    limePct: 11.0,
    salinityEC: 0.9,
    whcMm: 165,
    salinityRisk: 'low',
    erosionRisk: 'moderate',
    bioclimate: 'humid',
    rainfallMm: 640,
    tempSummer: 34,
    tempWinter: 6,
    et0: 4.0,
    frostDays: 10,
    siroccoDays: 12,
    dominantCrops: ['cereals', 'olives', 'pivot_potato', 'arboriculture'],
    keyProduceFr: 'Pomme de terre d’Ain Bessam, Huile d’olive, Céréales',
    keyProduceAr: 'بطاطا عين بسام، زيت زيتون، قمح صلب',
    agronomicHighlightFr: 'Plateau d’Ain Bessam réputé pour la pomme de terre et l’oléiculture de montagne.',
    agronomicHighlightAr: 'هضبة عين بسام الرائدة في إنتاج البطاطا وزراعة الزيتون في السفوح.',
    waterSourceFr: 'Barrages Tilesdit & Koudiat Acerdoune',
    waterSourceAr: 'سد تيلسديت وسد كدية أسردون',
    damOrBasinFr: 'Barrage Koudiat Acerdoune (640M m3)',
    svgCentroid: { x: 530, y: 130 },
  },
  {
    code: 11,
    codeStr: '11',
    id: 'tamanrasset',
    nameEn: 'Tamanrasset',
    nameAr: 'تمنراست',
    nameFr: 'Tamanrasset',
    capitalEn: 'Tamanrasset',
    capitalAr: 'تمنراست',
    capitalFr: 'Tamanrasset',
    zone: 'deep_sahara',
    lat: 22.78,
    lng: 5.53,
    dominantSoil: 'lithosol',
    soilNameFr: 'Sols volcaniques du Hoggar & sables alluviaux d’oueds',
    soilNameAr: 'تربة بركانية بالهقار وطمي أودية السيول',
    textureFr: 'Sablo-graveleux volcanique',
    textureAr: 'رملية حصوية بركانية',
    ph: 7.8,
    omPct: 0.5,
    limePct: 4.0,
    salinityEC: 2.0,
    whcMm: 50,
    salinityRisk: 'low',
    erosionRisk: 'high',
    bioclimate: 'hyper_arid',
    rainfallMm: 50,
    tempSummer: 38,
    tempWinter: 6,
    et0: 6.9,
    frostDays: 3,
    siroccoDays: 20,
    dominantCrops: ['arboriculture', 'greenhouses', 'date_palms', 'livestock'],
    keyProduceFr: 'Fruits tempérés du Hoggar (Raisin, Grenade, Pêche), Tomate sous abri',
    keyProduceAr: 'فواكه الهقار المميزة (عنب، رمان، خوخ)، طماطم محمية',
    agronomicHighlightFr: 'Microclimat d’altitude du massif du Hoggar permettant des cultures tempérées.',
    agronomicHighlightAr: 'مناخ محلي فريد في مرتفعات الهقار يسمح بإنتاج فاكهة معتدلة استثنائية.',
    waterSourceFr: 'Forages dans le socle granitique & Oued Tamanrasset',
    waterSourceAr: 'الآبار في القاعدة الجرانيتية ومياه وادي تمنراست',
    damOrBasinFr: 'Bassin hydrographique du Hoggar',
    svgCentroid: { x: 610, y: 830 },
  },
  {
    code: 13,
    codeStr: '13',
    id: 'tlemcen',
    nameEn: 'Tlemcen',
    nameAr: 'تلمسان',
    nameFr: 'Tlemcen',
    capitalEn: 'Tlemcen',
    capitalAr: 'تلمسان',
    capitalFr: 'Tlemcen',
    zone: 'mountains',
    lat: 34.88,
    lng: -1.31,
    dominantSoil: 'luvisol',
    soilNameFr: 'Terra Rossa fersiallitique & sols bruns de Maghnia',
    soilNameAr: 'التربة الحمراء المتوسطية وتربة مغنية الخصبة',
    textureFr: 'Argilo-limoneux rouge',
    textureAr: 'طميية طينية حمراء',
    ph: 7.5,
    omPct: 2.3,
    limePct: 9.0,
    salinityEC: 1.1,
    whcMm: 170,
    salinityRisk: 'low',
    erosionRisk: 'moderate',
    bioclimate: 'semi_arid',
    rainfallMm: 520,
    tempSummer: 33,
    tempWinter: 6,
    et0: 4.2,
    frostDays: 8,
    siroccoDays: 14,
    dominantCrops: ['olives', 'arboriculture', 'greenhouses', 'cereals'],
    keyProduceFr: 'Arboriculture (Cerises, Prunes), Huile d’olive, Maraîchage de Maghnia',
    keyProduceAr: 'أشجار الفاكهة (كرز، برقوق)، زيت زيتون، خضار مغنية',
    agronomicHighlightFr: 'Plaine de Maghnia et monts de Tlemcen aux terroirs d’arboriculture d’élite.',
    agronomicHighlightAr: 'سهل مغنية وجبال تلمسان المشهورة ببساتين الكرز والزيتون والخضار.',
    waterSourceFr: 'Barrages Sikkak, Beni Bahdel & Meffrouch',
    waterSourceAr: 'سدود السكاك، بني بهدل والمفروش',
    damOrBasinFr: 'Barrage Sikkak & Beni Bahdel',
    svgCentroid: { x: 340, y: 180 },
  },
  {
    code: 14,
    codeStr: '14',
    id: 'tiaret',
    nameEn: 'Tiaret',
    nameAr: 'تيارت',
    nameFr: 'Tiaret',
    capitalEn: 'Tiaret',
    capitalAr: 'تيارت',
    capitalFr: 'Tiaret',
    zone: 'high_plateaus',
    lat: 35.37,
    lng: 1.32,
    dominantSoil: 'calcisol',
    soilNameFr: 'Calcisols des hautes steppes du Sersou',
    soilNameAr: 'تربة كلسية لسهول السرسو الخصبة',
    textureFr: 'Argilo-limoneux',
    textureAr: 'طميية طينية',
    ph: 8.1,
    omPct: 1.5,
    limePct: 19.0,
    salinityEC: 1.2,
    whcMm: 155,
    salinityRisk: 'low',
    erosionRisk: 'high',
    bioclimate: 'semi_arid',
    rainfallMm: 390,
    tempSummer: 37,
    tempWinter: 2,
    et0: 4.6,
    frostDays: 25,
    siroccoDays: 16,
    dominantCrops: ['cereals', 'livestock', 'pivot_potato', 'arboriculture'],
    keyProduceFr: 'Grenier à blé du Sersou (Blé dur de haute qualité), Élevage équin/ovin',
    keyProduceAr: 'صومعة قمح السرسو الشهير، تربية الخيول العربية والأغنام',
    agronomicHighlightFr: 'Le Sersou : l’un des plus grands greniers céréaliers historiques d’Algérie.',
    agronomicHighlightAr: 'سهل السرسو: أحد أعظم وأعرق أحواض إنتاج القمح وتربية الخيول الأصيلة بالجزائر.',
    waterSourceFr: 'Barrage Dahmouni & Nappe du Sersou',
    waterSourceAr: 'سد دحموني وطبقة السرسو الجوفية',
    damOrBasinFr: 'Plaine du Sersou',
    svgCentroid: { x: 440, y: 180 },
  },
  {
    code: 15,
    codeStr: '15',
    id: 'tizi_ouzou',
    nameEn: 'Tizi Ouzou',
    nameAr: 'تيزي وزو',
    nameFr: 'Tizi Ouzou',
    capitalEn: 'Tizi Ouzou',
    capitalAr: 'تيزي وزو',
    capitalFr: 'Tizi Ouzou',
    zone: 'mountains',
    lat: 36.71,
    lng: 4.04,
    dominantSoil: 'luvisol',
    soilNameFr: 'Sols rouges fersiallitiques & cambisols de Kabylie',
    soilNameAr: 'تربة حمراء متوسطية وتربة بنية جبلية بالقبائل',
    textureFr: 'Sablo-argilo-limoneux',
    textureAr: 'رملية طينية طميية',
    ph: 6.8,
    omPct: 2.8,
    limePct: 4.0,
    salinityEC: 0.6,
    whcMm: 145,
    salinityRisk: 'none',
    erosionRisk: 'severe',
    bioclimate: 'humid',
    rainfallMm: 920,
    tempSummer: 32,
    tempWinter: 7,
    et0: 3.6,
    frostDays: 6,
    siroccoDays: 8,
    dominantCrops: ['olives', 'arboriculture', 'livestock'],
    keyProduceFr: 'Huile d’olive traditionnelle Chemlal, Figues de montagne, Miel de thym',
    keyProduceAr: 'زيت زيتون صنف شملال، تين جبلي، عسل الزعتر',
    agronomicHighlightFr: 'Terroir oléicole et arboricole de montagne par excellence.',
    agronomicHighlightAr: 'معقل إنتاج زيت الزيتون التقليدي الفاخر والأشجار المثمرة الجبلية.',
    waterSourceFr: 'Barrage Taksebt & Sources du Djurdjura',
    waterSourceAr: 'سد تاقسبت وينابيع جبال جرجرة',
    damOrBasinFr: 'Barrage Taksebt (180M m3)',
    svgCentroid: { x: 535, y: 110 },
  },
  {
    code: 16,
    codeStr: '16',
    id: 'alger',
    nameEn: 'Algiers',
    nameAr: 'الجزائر',
    nameFr: 'Alger',
    capitalEn: 'Algiers',
    capitalAr: 'الجزائر',
    capitalFr: 'Alger',
    zone: 'tell_coastal',
    lat: 36.75,
    lng: 3.05,
    dominantSoil: 'vertisol',
    soilNameFr: 'Tirs de la Mitidja nord & sols bruns du Sahel algérois',
    soilNameAr: 'تربة تيرس شمال متيجة والتربة البنية لساحل الجزائر',
    textureFr: 'Argilo-limoneux fertile',
    textureAr: 'طميية طينية خصبة',
    ph: 7.6,
    omPct: 2.2,
    limePct: 9.0,
    salinityEC: 1.0,
    whcMm: 185,
    salinityRisk: 'none',
    erosionRisk: 'low',
    bioclimate: 'humid',
    rainfallMm: 720,
    tempSummer: 31,
    tempWinter: 10,
    et0: 3.8,
    frostDays: 1,
    siroccoDays: 8,
    dominantCrops: ['greenhouses', 'citrus', 'arboriculture'],
    keyProduceFr: 'Maraîchage périurbain, Fleurs coupées, Fraises, Arboriculture',
    keyProduceAr: 'خضار حول المدن، زهور مقطوفة، فراولة، أشجار مثمرة',
    agronomicHighlightFr: 'Maraîchage intensif périurbain et ceintures horticoles du Sahel.',
    agronomicHighlightAr: 'زراعة خضار مكثفة حول الحواضر وحزام ساحلي للبساتين والشتائل.',
    waterSourceFr: 'Dessalement d’eau de mer & Nappe du Sahel',
    waterSourceAr: 'تحلية مياه البحر وطبقة الساحل',
    damOrBasinFr: 'Bassin côtier algérois',
    svgCentroid: { x: 500, y: 110 },
  },
  {
    code: 17,
    codeStr: '17',
    id: 'djelfa',
    nameEn: 'Djelfa',
    nameAr: 'الجلفة',
    nameFr: 'Djelfa',
    capitalEn: 'Djelfa',
    capitalAr: 'الجلفة',
    capitalFr: 'Djelfa',
    zone: 'high_plateaus',
    lat: 34.67,
    lng: 3.25,
    dominantSoil: 'calcisol',
    soilNameFr: 'Calcisols steppiques à croûte calcaire & parcours d’Alfa',
    soilNameAr: 'تربة جيرية سهوبية مع قشرة كلسية ومراعي الحلفاء',
    textureFr: 'Sablo-limoneux à caillouteux',
    textureAr: 'رملية طميية إلى حصوية',
    ph: 8.3,
    omPct: 0.8,
    limePct: 26.0,
    salinityEC: 2.2,
    whcMm: 95,
    salinityRisk: 'moderate',
    erosionRisk: 'high',
    bioclimate: 'arid',
    rainfallMm: 240,
    tempSummer: 38,
    tempWinter: 1,
    et0: 5.1,
    frostDays: 30,
    siroccoDays: 22,
    dominantCrops: ['livestock', 'cereals', 'arboriculture', 'olives'],
    keyProduceFr: 'Capitale du Mouton Ouled Djellal (4M têtes ovines), Céréales, Pommiers',
    keyProduceAr: 'عاصمة الأغنام أولاد جلال (أكثر من 4 ملايين رأس)، حبوب، تفاح',
    agronomicHighlightFr: 'Premier pôle d’élevage ovin et pastoral d’Algérie.',
    agronomicHighlightAr: 'القطب الأول بلا منازع لتربية المواشي وإنتاج اللحوم الحمراء بالجزائر.',
    waterSourceFr: 'Forages profonds & Barrage Charef',
    waterSourceAr: 'آبار عميقة وسد الشارف',
    damOrBasinFr: 'Bassin des Chotts / Zahrez',
    svgCentroid: { x: 510, y: 200 },
  },
  {
    code: 18,
    codeStr: '18',
    id: 'jijel',
    nameEn: 'Jijel',
    nameAr: 'جيجل',
    nameFr: 'Jijel',
    capitalEn: 'Jijel',
    capitalAr: 'جيجل',
    capitalFr: 'Jijel',
    zone: 'tell_coastal',
    lat: 36.82,
    lng: 5.76,
    dominantSoil: 'cambisol',
    soilNameFr: 'Sols bruns acides & alluvions côtières',
    soilNameAr: 'تربة بنية حمضية وطمي السهول الساحلية',
    textureFr: 'Sablo-limoneux riche',
    textureAr: 'رملية طميية غنية',
    ph: 6.4,
    omPct: 3.2,
    limePct: 2.0,
    salinityEC: 0.5,
    whcMm: 175,
    salinityRisk: 'none',
    erosionRisk: 'high',
    bioclimate: 'humid',
    rainfallMm: 1100,
    tempSummer: 30,
    tempWinter: 9,
    et0: 3.5,
    frostDays: 1,
    siroccoDays: 6,
    dominantCrops: ['greenhouses', 'arboriculture', 'olives'],
    keyProduceFr: 'Fraises de Jijel (Capitale de la fraise), Maraîchage sous serre, Huile d’olive',
    keyProduceAr: 'فراولة جيجل الشهيرة، خضار البيوت البلاستيكية، زيت زيتون',
    agronomicHighlightFr: 'Zone la plus arrosée du pays, leader incontesté de la culture de fraises.',
    agronomicHighlightAr: 'أغزر ولايات الوطن تساقطاً للأمطار، ورائدة زراعة الفراولة في الجزائر.',
    waterSourceFr: 'Barrages Kissir, Tabellout & Boussiaba',
    waterSourceAr: 'سدود كيسير، تابلّوط وبوسيابة',
    damOrBasinFr: 'Barrage Tabellout (294M m3)',
    svgCentroid: { x: 610, y: 110 },
  },
  {
    code: 19,
    codeStr: '19',
    id: 'setif',
    nameEn: 'Sétif',
    nameAr: 'سطيف',
    nameFr: 'Sétif',
    capitalEn: 'Sétif',
    capitalAr: 'سطيف',
    capitalFr: 'Sétif',
    zone: 'high_plateaus',
    lat: 36.19,
    lng: 5.41,
    dominantSoil: 'calcisol',
    soilNameFr: 'Calcisols & rendzines des hautes plaines sétifiennes',
    soilNameAr: 'تربة الكالسيسول والرندزينا بسهول سطيف المرتفعة',
    textureFr: 'Argilo-limoneux',
    textureAr: 'طميية طينية',
    ph: 8.1,
    omPct: 1.6,
    limePct: 22.0,
    salinityEC: 1.2,
    whcMm: 160,
    salinityRisk: 'low',
    erosionRisk: 'high',
    bioclimate: 'semi_arid',
    rainfallMm: 390,
    tempSummer: 35,
    tempWinter: 2,
    et0: 4.4,
    frostDays: 32,
    siroccoDays: 14,
    dominantCrops: ['cereals', 'arboriculture', 'livestock', 'pivot_potato'],
    keyProduceFr: 'Blé dur de référence, Pommes d’Ain Oulmene, Pomme de terre, Élevage laitier',
    keyProduceAr: 'قمح صلب عالي الجودة، تفاح عين ولمان، بطاطا، حليب وأبقار',
    agronomicHighlightFr: 'Capitale économique des Hauts Plateaux et 1er producteur de blé dur et de lait.',
    agronomicHighlightAr: 'عاصمة الهضاب العليا والرائدة الوطنية الأولى في إنتاج القمح الصلب والحليب.',
    waterSourceFr: 'Barrages Ain Zada, Mahouane & Grands Transferts',
    waterSourceAr: 'سدود عين زادة، مهوان ومنظومة التحويلات الكبرى',
    damOrBasinFr: 'Système Ain Zada / Mahouane',
    svgCentroid: { x: 590, y: 135 },
  },
  {
    code: 20,
    codeStr: '20',
    id: 'saida',
    nameEn: 'Saïda',
    nameAr: 'سعيدة',
    nameFr: 'Saïda',
    capitalEn: 'Saïda',
    capitalAr: 'سعيدة',
    capitalFr: 'Saïda',
    zone: 'high_plateaus',
    lat: 34.83,
    lng: 0.15,
    dominantSoil: 'calcisol',
    soilNameFr: 'Calcisols bruns & piémonts des monts de Daïa',
    soilNameAr: 'تربة جيرية بنية وسفوح جبال الضاية',
    textureFr: 'Argilo-limoneux calcaire',
    textureAr: 'طميية طينية كلسية',
    ph: 8.0,
    omPct: 1.4,
    limePct: 17.0,
    salinityEC: 1.3,
    whcMm: 135,
    salinityRisk: 'low',
    erosionRisk: 'moderate',
    bioclimate: 'semi_arid',
    rainfallMm: 340,
    tempSummer: 36,
    tempWinter: 3,
    et0: 4.7,
    frostDays: 20,
    siroccoDays: 18,
    dominantCrops: ['cereals', 'livestock', 'olives', 'arboriculture'],
    keyProduceFr: 'Céréales (Blé dur, Orge), Élevage ovin, Eaux minérales naturelles',
    keyProduceAr: 'حبوب (قمح صلب، شعير)، تربية الأغنام، بساتين الزيتون',
    agronomicHighlightFr: 'Plateau agro-pastoral réputé pour la qualité de son blé et ses eaux de source.',
    agronomicHighlightAr: 'هضبة رعوية وحبوبية متميزة بجودة القمح والشعير وينابيع المياه العذبة.',
    waterSourceFr: 'Barrage Kef Boukerche & Forages',
    waterSourceAr: 'سد كاف بوكرش والآبار',
    damOrBasinFr: 'Bassin versant de l’Oued Saïda',
    svgCentroid: { x: 405, y: 190 },
  },
  {
    code: 21,
    codeStr: '21',
    id: 'skikda',
    nameEn: 'Skikda',
    nameAr: 'سكيكدة',
    nameFr: 'Skikda',
    capitalEn: 'Skikda',
    capitalAr: 'سكيكدة',
    capitalFr: 'Skikda',
    zone: 'tell_coastal',
    lat: 36.87,
    lng: 6.90,
    dominantSoil: 'fluvisol',
    soilNameFr: 'Alluvions riches de la plaine de Saf-Saf & sols rouges',
    soilNameAr: 'طمي سهل صفصاف الرسوبي والتربة الحمراء',
    textureFr: 'Argilo-limoneux profond',
    textureAr: 'طميية طينية عميقة',
    ph: 7.3,
    omPct: 2.6,
    limePct: 7.0,
    salinityEC: 0.9,
    whcMm: 185,
    salinityRisk: 'none',
    erosionRisk: 'moderate',
    bioclimate: 'humid',
    rainfallMm: 850,
    tempSummer: 31,
    tempWinter: 9,
    et0: 3.7,
    frostDays: 1,
    siroccoDays: 8,
    dominantCrops: ['citrus', 'greenhouses', 'cereals', 'olives'],
    keyProduceFr: 'Tomate industrielle de Saf-Saf, Fraises de Tamalous, Agrumes',
    keyProduceAr: 'طماطم صناعية بسهل صفصاف، فراولة تمالوس، حمضيات',
    agronomicHighlightFr: 'Grand pôle de la tomate industrielle et arboriculture littorale florissante.',
    agronomicHighlightAr: 'قطب رائد لإنتاج وتحويل الطماطم الصناعية وبساتين الحمضيات والفراولة.',
    waterSourceFr: 'Barrages Zit Emba & Guenitra',
    waterSourceAr: 'سدود زيت عنبة والقنيطرة',
    damOrBasinFr: 'Bassin du Saf-Saf',
    svgCentroid: { x: 660, y: 110 },
  },
  {
    code: 22,
    codeStr: '22',
    id: 'sidi_bel_abbes',
    nameEn: 'Sidi Bel Abbès',
    nameAr: 'سيدي بلعباس',
    nameFr: 'Sidi Bel Abbès',
    capitalEn: 'Sidi Bel Abbès',
    capitalAr: 'سيدي بلعباس',
    capitalFr: 'Sidi Bel Abbès',
    zone: 'high_plateaus',
    lat: 35.19,
    lng: -0.63,
    dominantSoil: 'vertisol',
    soilNameFr: 'Tirs de la plaine de la Tessala & calcisols',
    soilNameAr: 'تربة التيرس بسهل تسالة والتربة الكلسية',
    textureFr: 'Argileux à argilo-limoneux',
    textureAr: 'طينية إلى طينية طميية',
    ph: 8.0,
    omPct: 1.7,
    limePct: 15.0,
    salinityEC: 1.4,
    whcMm: 180,
    salinityRisk: 'low',
    erosionRisk: 'moderate',
    bioclimate: 'semi_arid',
    rainfallMm: 380,
    tempSummer: 36,
    tempWinter: 5,
    et0: 4.5,
    frostDays: 16,
    siroccoDays: 15,
    dominantCrops: ['cereals', 'olives', 'livestock', 'viticulture'],
    keyProduceFr: 'Blé dur, Oignon de renommée, Légumineuses, Olives de table',
    keyProduceAr: 'قمح صلب، بصل عالي الجودة، بقوليات جافة، زيتون',
    agronomicHighlightFr: 'Grand pôle céréalier et maraîcher de l’Ouest algérien.',
    agronomicHighlightAr: 'قطب حبوبي وخضري رائد في الغرب الجزائري.',
    waterSourceFr: 'Barrages Tabia & Sarno, Oued Mekerra',
    waterSourceAr: 'سدود طابية وسارنو ووادي مكرة',
    damOrBasinFr: 'Barrage Sarno',
    svgCentroid: { x: 375, y: 165 },
  },
  {
    code: 23,
    codeStr: '23',
    id: 'annaba',
    nameEn: 'Annaba',
    nameAr: 'عنابة',
    nameFr: 'Annaba',
    capitalEn: 'Annaba',
    capitalAr: 'عنابة',
    capitalFr: 'Annaba',
    zone: 'tell_coastal',
    lat: 36.90,
    lng: 7.76,
    dominantSoil: 'fluvisol',
    soilNameFr: 'Alluvions riches de la Seybouse & sols côtiers',
    soilNameAr: 'طمي وادي سيبوس الفيضي والتربة الساحلية الخصبة',
    textureFr: 'Argilo-limoneux profond',
    textureAr: 'طميية طينية عميقة',
    ph: 7.4,
    omPct: 2.8,
    limePct: 6.0,
    salinityEC: 0.8,
    whcMm: 190,
    salinityRisk: 'none',
    erosionRisk: 'low',
    bioclimate: 'humid',
    rainfallMm: 800,
    tempSummer: 31,
    tempWinter: 9,
    et0: 3.7,
    frostDays: 1,
    siroccoDays: 8,
    dominantCrops: ['citrus', 'greenhouses', 'cereals'],
    keyProduceFr: 'Tomate industrielle de la Seybouse, Maraîchage primeur, Agrumes',
    keyProduceAr: 'طماطم صناعية بحوض سيبوس، خضار مبكرة، حمضيات',
    agronomicHighlightFr: 'Bassin alluvionnaire de la Seybouse à forte intensité maraîchère et agro-industrielle.',
    agronomicHighlightAr: 'حوض وادي سيبوس الخصب، مركز للصناعات الغذائية والطماطم.',
    waterSourceFr: 'Barrages Mexa & Cheffia, Oued Seybouse',
    waterSourceAr: 'سدود مكسة والشافية ووادي سيبوس',
    damOrBasinFr: 'Plaine de la Seybouse',
    svgCentroid: { x: 700, y: 110 },
  },
  {
    code: 24,
    codeStr: '24',
    id: 'guelma',
    nameEn: 'Guelma',
    nameAr: 'قالمة',
    nameFr: 'Guelma',
    capitalEn: 'Guelma',
    capitalAr: 'قالمة',
    capitalFr: 'Guelma',
    zone: 'tell_coastal',
    lat: 36.46,
    lng: 7.43,
    dominantSoil: 'cambisol',
    soilNameFr: 'Sols bruns de vallées & vertisols alluviaux',
    soilNameAr: 'تربة بنية بالوديان وتربة تيرس رسوبية',
    textureFr: 'Argilo-limoneux',
    textureAr: 'طميية طينية خصبة',
    ph: 7.7,
    omPct: 2.2,
    limePct: 12.0,
    salinityEC: 0.9,
    whcMm: 175,
    salinityRisk: 'low',
    erosionRisk: 'moderate',
    bioclimate: 'humid',
    rainfallMm: 620,
    tempSummer: 35,
    tempWinter: 6,
    et0: 4.1,
    frostDays: 8,
    siroccoDays: 12,
    dominantCrops: ['cereals', 'greenhouses', 'olives', 'citrus'],
    keyProduceFr: 'Leader de la Tomate Industrielle, Blé dur, Olives, Élevage bovin',
    keyProduceAr: 'رائد وطني للطماطم الصناعية، قمح صلب، زيتون، تربية الأبقار',
    agronomicHighlightFr: 'La capitale incontournable de la tomate industrielle et des usines de concentré.',
    agronomicHighlightAr: 'عاصمة الطماطم الصناعية ومصانع المعجون بالجزائر مع زراعة الحبوب.',
    waterSourceFr: 'Barrage Bouhamdane & Oued Seybouse',
    waterSourceAr: 'سد بوحمدان ووادي سيبوس',
    damOrBasinFr: 'Barrage Bouhamdane (185M m3)',
    svgCentroid: { x: 685, y: 125 },
  },
  {
    code: 25,
    codeStr: '25',
    id: 'constantine',
    nameEn: 'Constantine',
    nameAr: 'قسنطينة',
    nameFr: 'Constantine',
    capitalEn: 'Constantine',
    capitalAr: 'قسنطينة',
    capitalFr: 'Constantine',
    zone: 'high_plateaus',
    lat: 36.36,
    lng: 6.61,
    dominantSoil: 'calcisol',
    soilNameFr: 'Calcisols bruns & rendzines des plateaux calcaires',
    soilNameAr: 'تربة بنية جيرية ورندزينا بالهضاب الكلسية',
    textureFr: 'Argilo-limoneux lourd',
    textureAr: 'طميية طينية ثقيلة',
    ph: 8.0,
    omPct: 1.9,
    limePct: 20.0,
    salinityEC: 1.0,
    whcMm: 165,
    salinityRisk: 'low',
    erosionRisk: 'moderate',
    bioclimate: 'semi_arid',
    rainfallMm: 550,
    tempSummer: 34,
    tempWinter: 4,
    et0: 4.1,
    frostDays: 18,
    siroccoDays: 12,
    dominantCrops: ['cereals', 'livestock', 'arboriculture'],
    keyProduceFr: 'Blé dur d’excellence, Légumineuses sèches (Pois chiche), Élevage laitier',
    keyProduceAr: 'قمح صلب فاخر، حمضيات، بقوليات جافة (حمص)، حليب وأبقار',
    agronomicHighlightFr: 'Haut lieu historique de la céréaliculture algérienne et de la sélection variétale.',
    agronomicHighlightAr: 'مركز تاريخي وأكاديمي لزراعة الحبوب واستنباط البذور المحسنة.',
    waterSourceFr: 'Barrage Beni Haroun (Grands Transferts) & Oued Rhumel',
    waterSourceAr: 'سد بني هارون العملاق ووادي الرمال',
    damOrBasinFr: 'Système Beni Haroun (1 Milliard m3)',
    svgCentroid: { x: 650, y: 130 },
  },
  {
    code: 26,
    codeStr: '26',
    id: 'medea',
    nameEn: 'Médéa',
    nameAr: 'المدية',
    nameFr: 'Médéa',
    capitalEn: 'Médéa',
    capitalAr: 'المدية',
    capitalFr: 'Médéa',
    zone: 'mountains',
    lat: 36.26,
    lng: 2.75,
    dominantSoil: 'cambisol',
    soilNameFr: 'Sols bruns de montagne & marnes du Titteri',
    soilNameAr: 'تربة بنية جبلية ومارن هضاب التيطري',
    textureFr: 'Argilo-limoneux à marneux',
    textureAr: 'طميية طينية مارنية',
    ph: 7.9,
    omPct: 2.1,
    limePct: 18.0,
    salinityEC: 0.9,
    whcMm: 160,
    salinityRisk: 'low',
    erosionRisk: 'severe',
    bioclimate: 'semi_arid',
    rainfallMm: 580,
    tempSummer: 34,
    tempWinter: 4,
    et0: 4.2,
    frostDays: 20,
    siroccoDays: 14,
    dominantCrops: ['arboriculture', 'viticulture', 'olives', 'cereals'],
    keyProduceFr: 'Raisin de table (Dattier de Médéa), Pommes, Huile d’olive, Apiculture',
    keyProduceAr: 'عنب المائدة (داتييه المدية)، تفاح، زيت زيتون، تربية النحل',
    agronomicHighlightFr: 'Vignobles et vergers d’altitude réputés du Titteri.',
    agronomicHighlightAr: 'بساتين الكروم وفاكهة المرتفعات العريقة في منطقة التيطري.',
    waterSourceFr: 'Barrages Ladrat, Ghrib & Sources de montagne',
    waterSourceAr: 'سدود لدرات، الغريب والينابيع الجبلية',
    damOrBasinFr: 'Barrage Ghrib & Ladrat',
    svgCentroid: { x: 485, y: 140 },
  },
  {
    code: 27,
    codeStr: '27',
    id: 'mostaganem',
    nameEn: 'Mostaganem',
    nameAr: 'مستغانم',
    nameFr: 'Mostaganem',
    capitalEn: 'Mostaganem',
    capitalAr: 'مستغانم',
    capitalFr: 'Mostaganem',
    zone: 'tell_coastal',
    lat: 35.93,
    lng: 0.09,
    dominantSoil: 'arenosol',
    soilNameFr: 'Sables côtiers du Dahra & sols alluviaux de la basse Mina',
    soilNameAr: 'رمال الظهرة الساحلية وطمي وادي مينا السفلي',
    textureFr: 'Sablo-limoneux léger',
    textureAr: 'رملية طميية خفيفة',
    ph: 7.8,
    omPct: 1.3,
    limePct: 10.0,
    salinityEC: 1.5,
    whcMm: 110,
    salinityRisk: 'low',
    erosionRisk: 'moderate',
    bioclimate: 'semi_arid',
    rainfallMm: 400,
    tempSummer: 32,
    tempWinter: 9,
    et0: 4.4,
    frostDays: 2,
    siroccoDays: 14,
    dominantCrops: ['pivot_potato', 'citrus', 'greenhouses', 'viticulture'],
    keyProduceFr: 'Capitale côtière de la Pomme de Terre, Maraîchage sous serre, Raisin',
    keyProduceAr: 'عاصمة البطاطا الساحلية، خضار البيوت المحمية، عنب المائدة',
    agronomicHighlightFr: 'Leader national de la pomme de terre de saison et arrière-saison avec le Dahra.',
    agronomicHighlightAr: 'رائدة وطنية لإنتاج البطاطا الموسمية وما بعد الموسمية وخضار الساحل.',
    waterSourceFr: 'Barrage Cheliff & Station de dessalement',
    waterSourceAr: 'سد الشلف ومحطة تحلية مياه البحر',
    damOrBasinFr: 'Bassin versant du Dahra côtier',
    svgCentroid: { x: 410, y: 140 },
  },
  {
    code: 28,
    codeStr: '28',
    id: 'msila',
    nameEn: 'M’Sila',
    nameAr: 'المسيلة',
    nameFr: 'M’Sila',
    capitalEn: 'M’Sila',
    capitalAr: 'المسيلة',
    capitalFr: 'M’Sila',
    zone: 'high_plateaus',
    lat: 35.70,
    lng: 4.54,
    dominantSoil: 'solonchak',
    soilNameFr: 'Sols halomorphes du Hodna & calcisols steppiques',
    soilNameAr: 'تربة الحضنة الملحية والتربة الجيرية السهوبية',
    textureFr: 'Limono-argileux à salé',
    textureAr: 'طميية طينية إلى ملحية',
    ph: 8.2,
    omPct: 0.9,
    limePct: 22.0,
    salinityEC: 4.2,
    whcMm: 120,
    salinityRisk: 'high',
    erosionRisk: 'high',
    bioclimate: 'arid',
    rainfallMm: 220,
    tempSummer: 40,
    tempWinter: 3,
    et0: 5.3,
    frostDays: 22,
    siroccoDays: 24,
    dominantCrops: ['livestock', 'arboriculture', 'cereals', 'greenhouses'],
    keyProduceFr: 'Abricots de M’Sila (AOC Maghra), Élevage ovin, Céréales sous pivot',
    keyProduceAr: 'مشمش المسيلة (مغرة)، تربية الأغنام، قمح بالري المحوري',
    agronomicHighlightFr: 'Bassin du Hodna réputé pour son arboriculture abricotière et le pastoralisme.',
    agronomicHighlightAr: 'حوض الحضنة المشهور بإنتاج المشمش العالي الجودة وتربية الماشية.',
    waterSourceFr: 'Barrage Ksob & Soubella, Forages profonds',
    waterSourceAr: 'سدود القصب وسبلة والآبار العميقة',
    damOrBasinFr: 'Bassin du Chott El Hodna',
    svgCentroid: { x: 555, y: 160 },
  },
  {
    code: 29,
    codeStr: '29',
    id: 'mascara',
    nameEn: 'Mascara',
    nameAr: 'معسكر',
    nameFr: 'Mascara',
    capitalEn: 'Mascara',
    capitalAr: 'معسكر',
    capitalFr: 'Mascara',
    zone: 'tell_coastal',
    lat: 35.39,
    lng: 0.14,
    dominantSoil: 'vertisol',
    soilNameFr: 'Tirs de la plaine de Ghriss & alluvions de l’Habra',
    soilNameAr: 'تربة التيرس بسهل غريس وطمي سهل الهبرة',
    textureFr: 'Argilo-limoneux profond',
    textureAr: 'طميية طينية عميقة خصبة',
    ph: 7.9,
    omPct: 2.1,
    limePct: 14.0,
    salinityEC: 1.3,
    whcMm: 185,
    salinityRisk: 'low',
    erosionRisk: 'moderate',
    bioclimate: 'semi_arid',
    rainfallMm: 440,
    tempSummer: 36,
    tempWinter: 5,
    et0: 4.4,
    frostDays: 12,
    siroccoDays: 16,
    dominantCrops: ['olives', 'pivot_potato', 'citrus', 'viticulture'],
    keyProduceFr: 'Pomme de terre de Ghriss, Olives Sigoise de table, Agrumes de l’Habra, Oignons',
    keyProduceAr: 'بطاطا سهل غريس، زيتون سيغ المائدة، حمضيات الهبرة، بصل',
    agronomicHighlightFr: 'Plaine mythique de Ghriss et Sig : bastion de la pomme de terre et de l’olive.',
    agronomicHighlightAr: 'سهل غريس وسيق الشهير: قلعة وطنية لإنتاج البطاطا وزيتون المائدة والحمضيات.',
    waterSourceFr: 'Barrages Ouizert, Bouhanifia & Fergoug',
    waterSourceAr: 'سدود ويزرت، بوحنيفية والفرقوق',
    damOrBasinFr: 'Périmètre irrigué de Ghriss & Habra',
    svgCentroid: { x: 405, y: 160 },
  },
  {
    code: 30,
    codeStr: '30',
    id: 'ouargla',
    nameEn: 'Ouargla',
    nameAr: 'ورقلة',
    nameFr: 'Ouargla',
    capitalEn: 'Ouargla',
    capitalAr: 'ورقلة',
    capitalFr: 'Ouargla',
    zone: 'deep_sahara',
    lat: 31.95,
    lng: 5.32,
    dominantSoil: 'arenosol',
    soilNameFr: 'Sables du bassin du bas Sahara & sols gypsifères',
    soilNameAr: 'رمال حوض الصحراء السفلى والتربة الجبسية',
    textureFr: 'Sableux éolien',
    textureAr: 'رملية صحراوية',
    ph: 8.2,
    omPct: 0.3,
    limePct: 11.0,
    salinityEC: 4.0,
    whcMm: 50,
    salinityRisk: 'high',
    erosionRisk: 'severe',
    bioclimate: 'hyper_arid',
    rainfallMm: 50,
    tempSummer: 46,
    tempWinter: 10,
    et0: 7.2,
    frostDays: 1,
    siroccoDays: 40,
    dominantCrops: ['date_palms', 'pivot_potato', 'cereals'],
    keyProduceFr: 'Dattes Deglet Nour & Ghars, Céréales sous pivot, Cultures maraîchères',
    keyProduceAr: 'تمور دقلة نور والغرس، قمح بالري المحوري، خضار',
    agronomicHighlightFr: 'Grande oasis historique et nouveaux mégas-périmètres agricoles sahariens.',
    agronomicHighlightAr: 'واحة تاريخية كبرى ومحيطات امتياز زراعي حديثة بالري المحوري.',
    waterSourceFr: 'Nappes du Complexe Terminal et du Continental Intercalaire',
    waterSourceAr: 'طبقات المركب النهائي والألبيان الجوفية',
    damOrBasinFr: 'Bassin du Sahara Septentrional',
    svgCentroid: { x: 600, y: 320 },
  },
  {
    code: 31,
    codeStr: '31',
    id: 'oran',
    nameEn: 'Oran',
    nameAr: 'وهران',
    nameFr: 'Oran',
    capitalEn: 'Oran',
    capitalAr: 'وهران',
    capitalFr: 'Oran',
    zone: 'tell_coastal',
    lat: 35.69,
    lng: -0.63,
    dominantSoil: 'calcisol',
    soilNameFr: 'Sols bruns calcaires & alluvions de la plaine de Mleta',
    soilNameAr: 'تربة بنية جيرية وطمي سهل ملاتة',
    textureFr: 'Argilo-limoneux calcaire',
    textureAr: 'طميية طينية كلسية',
    ph: 7.9,
    omPct: 1.8,
    limePct: 16.0,
    salinityEC: 1.6,
    whcMm: 165,
    salinityRisk: 'moderate',
    erosionRisk: 'low',
    bioclimate: 'semi_arid',
    rainfallMm: 380,
    tempSummer: 32,
    tempWinter: 10,
    et0: 4.3,
    frostDays: 1,
    siroccoDays: 12,
    dominantCrops: ['greenhouses', 'olives', 'citrus', 'viticulture'],
    keyProduceFr: 'Maraîchage sous serre de la Mleta, Olives, Primeurs, Raisin',
    keyProduceAr: 'خضار البيوت المحمية بسهل ملاتة، زيتون، عنب المائدة',
    agronomicHighlightFr: 'Plaine de la Mleta et ceintures maraîchères littorales modernes.',
    agronomicHighlightAr: 'سهل ملاتة والأحزمة الخضرية الساحلية المزودة بالسقي الحديث.',
    waterSourceFr: 'Station de dessalement d’El Mactaa & Réseau MAO',
    waterSourceAr: 'محطة تحلية مياه البحر بالمقطع ومنظومة ماو',
    damOrBasinFr: 'Bassin versant côtier oranais',
    svgCentroid: { x: 380, y: 145 },
  },
  {
    code: 32,
    codeStr: '32',
    id: 'el_bayadh',
    nameEn: 'El Bayadh',
    nameAr: 'البيض',
    nameFr: 'El Bayadh',
    capitalEn: 'El Bayadh',
    capitalAr: 'البيض',
    capitalFr: 'El Bayadh',
    zone: 'high_plateaus',
    lat: 33.68,
    lng: 1.01,
    dominantSoil: 'calcisol',
    soilNameFr: 'Sols steppiques caillouteux & croûtes gypso-calcaires',
    soilNameAr: 'تربة سهوبية حصوية مع قشور جبسية كلسية',
    textureFr: 'Sablo-limoneux caillouteux',
    textureAr: 'رملية طميية حصوية',
    ph: 8.2,
    omPct: 0.7,
    limePct: 22.0,
    salinityEC: 2.0,
    whcMm: 85,
    salinityRisk: 'moderate',
    erosionRisk: 'high',
    bioclimate: 'arid',
    rainfallMm: 210,
    tempSummer: 39,
    tempWinter: 0,
    et0: 5.2,
    frostDays: 35,
    siroccoDays: 25,
    dominantCrops: ['livestock', 'cereals', 'arboriculture'],
    keyProduceFr: 'Élevage pastoral ovin d’élite, Céréales sous pivot, Arboriculture rustique',
    keyProduceAr: 'تربية الأغنام السهوبية الأصيلة، قمح بالري المحوري، أشجار مقاومة',
    agronomicHighlightFr: 'Grand bastion pastoral des hauts plateaux de l’Ouest et élevage ovin.',
    agronomicHighlightAr: 'أحد أهم معاقل تربية المواشي والمراعي السهوبية في الغرب الجزائري.',
    waterSourceFr: 'Barrage Larouia & Forages profonds',
    waterSourceAr: 'سد لاروية والآبار الجوفية العميقة',
    damOrBasinFr: 'Chott Ech Chergui',
    svgCentroid: { x: 430, y: 240 },
  },
  {
    code: 34,
    codeStr: '34',
    id: 'bordj_bou_arreridj',
    nameEn: 'Bordj Bou Arréridj',
    nameAr: 'برج بوعريريج',
    nameFr: 'Bordj Bou Arréridj',
    capitalEn: 'Bordj Bou Arréridj',
    capitalAr: 'برج بوعريريج',
    capitalFr: 'Bordj Bou Arréridj',
    zone: 'high_plateaus',
    lat: 36.07,
    lng: 4.76,
    dominantSoil: 'calcisol',
    soilNameFr: 'Calcisols bruns & rendzines des plaines de la Medjana',
    soilNameAr: 'تربة بنية جيرية ورندزينا بسهل مجانة',
    textureFr: 'Argilo-limoneux',
    textureAr: 'طميية طينية',
    ph: 8.0,
    omPct: 1.7,
    limePct: 18.0,
    salinityEC: 1.0,
    whcMm: 155,
    salinityRisk: 'low',
    erosionRisk: 'moderate',
    bioclimate: 'semi_arid',
    rainfallMm: 450,
    tempSummer: 35,
    tempWinter: 3,
    et0: 4.3,
    frostDays: 24,
    siroccoDays: 14,
    dominantCrops: ['cereals', 'arboriculture', 'livestock', 'olives'],
    keyProduceFr: 'Blé dur de la Medjana, Olives, Arboriculture (Pommes, Poires), Élevage avicole',
    keyProduceAr: 'قمح صلب بسهل مجانة، زيتون، تفاحيات، تربية الدواجن',
    agronomicHighlightFr: 'Plaine céréalière historique de la Medjana et forte intégration avicole.',
    agronomicHighlightAr: 'سهل مجانة الحبوبي العريق مع ريادة في تربية الدواجن وإنتاج الزيتون.',
    waterSourceFr: 'Barrage Ain Zada & Barrage Soubella',
    waterSourceAr: 'سد عين زادة وسد سبلة',
    damOrBasinFr: 'Plaine de la Medjana',
    svgCentroid: { x: 565, y: 135 },
  },
  {
    code: 35,
    codeStr: '35',
    id: 'boumerdes',
    nameEn: 'Boumerdès',
    nameAr: 'بومرداس',
    nameFr: 'Boumerdès',
    capitalEn: 'Boumerdès',
    capitalAr: 'بومرداس',
    capitalFr: 'Boumerdès',
    zone: 'tell_coastal',
    lat: 36.76,
    lng: 3.47,
    dominantSoil: 'vertisol',
    soilNameFr: 'Tirs de la Mitidja orientale & alluvions des Issers',
    soilNameAr: 'تربة التيرس لشرق متيجة وطمي وادي يسر',
    textureFr: 'Argilo-limoneux profond',
    textureAr: 'طميية طينية خصبة',
    ph: 7.5,
    omPct: 2.5,
    limePct: 7.5,
    salinityEC: 0.9,
    whcMm: 190,
    salinityRisk: 'none',
    erosionRisk: 'low',
    bioclimate: 'humid',
    rainfallMm: 790,
    tempSummer: 31,
    tempWinter: 9,
    et0: 3.8,
    frostDays: 1,
    siroccoDays: 8,
    dominantCrops: ['viticulture', 'greenhouses', 'citrus', 'arboriculture'],
    keyProduceFr: 'Capitale du Raisin de Table (Red Globe, Cardinal), Maraîchage, Fraises',
    keyProduceAr: 'عاصمة عنب المائدة الوطني (ريد غلوب، كاردينال)، خضار، فراولة',
    agronomicHighlightFr: 'Premier producteur national de raisin de table avec une arboriculture littorale de pointe.',
    agronomicHighlightAr: 'الرائد الوطني الأول لإنتاج عنب المائدة والخضار الساحلية المبكرة.',
    waterSourceFr: 'Barrage Beni Amrane, Keddara & Station de Cap Djinet',
    waterSourceAr: 'سدود قدارة وبني عمران ومحطة كاب جنات',
    damOrBasinFr: 'Barrage Keddara & Beni Amrane',
    svgCentroid: { x: 515, y: 115 },
  },
  {
    code: 39,
    codeStr: '39',
    id: 'el_oued',
    nameEn: 'El Oued',
    nameAr: 'الوادي',
    nameFr: 'El Oued',
    capitalEn: 'El Oued',
    capitalAr: 'الوادي',
    capitalFr: 'El Oued',
    zone: 'sahara_oasis',
    lat: 33.37,
    lng: 6.86,
    dominantSoil: 'arenosol',
    soilNameFr: 'Sables éoliens du Grand Erg Oriental & Ghouts',
    soilNameAr: 'رمال العرق الشرقي الكثبانية والغيطان التقليدية',
    textureFr: 'Sable éolien pur',
    textureAr: 'رمل صحراوي نقي',
    ph: 8.3,
    omPct: 0.2,
    limePct: 7.0,
    salinityEC: 2.2,
    whcMm: 38,
    salinityRisk: 'moderate',
    erosionRisk: 'severe',
    bioclimate: 'hyper_arid',
    rainfallMm: 75,
    tempSummer: 46,
    tempWinter: 10,
    et0: 6.8,
    frostDays: 1,
    siroccoDays: 38,
    dominantCrops: ['pivot_potato', 'date_palms', 'greenhouses', 'arboriculture'],
    keyProduceFr: 'Leader National Pomme de Terre sous pivot (1.5M tonnes/an), Dattes Deglet Nour du Souf, Oignons',
    keyProduceAr: 'الرائد الوطني الأول للبطاطا تحت الري المحوري (1.5 مليون طن)، دقلة نور وادي سوف، بصل',
    agronomicHighlightFr: 'Le miracle agricole du Souf : reconversion spectaculaire des dunes en pivots ultra-productifs.',
    agronomicHighlightAr: 'معجزة وادي سوف الفلاحية: تحويل كثبان الرمال إلى أكبر قطب لإنتاج البطاطا والتمور.',
    waterSourceFr: 'Nappes du Complexe Terminal et Continental Intercalaire (Albien)',
    waterSourceAr: 'طبقات المركب النهائي والألبيان الجوفية',
    damOrBasinFr: 'Bassin du Grand Erg Oriental',
    svgCentroid: { x: 670, y: 260 },
  },
  {
    code: 42,
    codeStr: '42',
    id: 'tipaza',
    nameEn: 'Tipaza',
    nameAr: 'تيبازة',
    nameFr: 'Tipaza',
    capitalEn: 'Tipaza',
    capitalAr: 'تيبازة',
    capitalFr: 'Tipaza',
    zone: 'tell_coastal',
    lat: 36.59,
    lng: 2.44,
    dominantSoil: 'vertisol',
    soilNameFr: 'Tirs de l’ouest de la Mitidja & sols rouges littoraux',
    soilNameAr: 'تربة التيرس لغرب متيجة والتربة الحمراء الساحلية',
    textureFr: 'Argilo-limoneux riche',
    textureAr: 'طميية طينية غنية',
    ph: 7.6,
    omPct: 2.4,
    limePct: 8.0,
    salinityEC: 0.9,
    whcMm: 190,
    salinityRisk: 'none',
    erosionRisk: 'low',
    bioclimate: 'humid',
    rainfallMm: 740,
    tempSummer: 31,
    tempWinter: 10,
    et0: 3.8,
    frostDays: 1,
    siroccoDays: 8,
    dominantCrops: ['citrus', 'greenhouses', 'arboriculture', 'viticulture'],
    keyProduceFr: 'Agrumes (Clémentines, Oranges), Maraîchage sous serre, Raisin de table',
    keyProduceAr: 'حمضيات وكليمونتين، خضار البيوت المحمية، عنب المائدة',
    agronomicHighlightFr: 'Extension occidentale de la Mitidja, sol d’excellence pour les agrumes.',
    agronomicHighlightAr: 'الامتداد الغربي الخصيب لسهل متيجة وبساتين الحمضيات والخضار.',
    waterSourceFr: 'Barrages Taikser et Boukourdane, Dessalement de Fouka',
    waterSourceAr: 'سدود تيكسير وبوكردان ومحطة تحلية فوكة',
    damOrBasinFr: 'Barrage Boukourdane',
    svgCentroid: { x: 475, y: 120 },
  },
  {
    code: 47,
    codeStr: '47',
    id: 'ghardaia',
    nameEn: 'Ghardaïa',
    nameAr: 'غرداية',
    nameFr: 'Ghardaïa',
    capitalEn: 'Ghardaïa',
    capitalAr: 'غرداية',
    capitalFr: 'Ghardaïa',
    zone: 'sahara_oasis',
    lat: 32.49,
    lng: 3.67,
    dominantSoil: 'arenosol',
    soilNameFr: 'Sols caillouteux du M’Zab & alluvions',
    soilNameAr: 'تربة وادي ميزاب الحصوية والطميية الفيضية',
    textureFr: 'Sablo-limoneux à caillouteux',
    textureAr: 'رملية طميية إلى حصوية',
    ph: 8.2,
    omPct: 0.5,
    limePct: 19.0,
    salinityEC: 2.9,
    whcMm: 70,
    salinityRisk: 'moderate',
    erosionRisk: 'high',
    bioclimate: 'hyper_arid',
    rainfallMm: 95,
    tempSummer: 43,
    tempWinter: 9,
    et0: 6.0,
    frostDays: 3,
    siroccoDays: 30,
    dominantCrops: ['date_palms', 'pivot_potato', 'greenhouses', 'livestock'],
    keyProduceFr: 'Palmeraies du M’Zab, Pomme de terre sous pivot à Guerrara, Élevage caprin/bovin laitier',
    keyProduceAr: 'واحات وادي ميزاب، بطاطا الري المحوري بالقرارة، تربية الماعز والأبقار',
    agronomicHighlightFr: 'Périmètres de Guerrara et oases ancestrales du M’Zab.',
    agronomicHighlightAr: 'محيطات القرارة الزراعية الكبرى وواحات وادي ميزاب العريقة.',
    waterSourceFr: 'Nappe de l’Albien & Digues traditionnelles de crues',
    waterSourceAr: 'مياه طبقة الألبيان وسدود تحويل السيول التقليدية',
    damOrBasinFr: 'Nappe du Continental Intercalaire',
    svgCentroid: { x: 535, y: 300 },
  },
  {
    code: 48,
    codeStr: '48',
    id: 'relizane',
    nameEn: 'Relizane',
    nameAr: 'غليزان',
    nameFr: 'Relizane',
    capitalEn: 'Relizane',
    capitalAr: 'غليزان',
    capitalFr: 'Relizane',
    zone: 'tell_coastal',
    lat: 35.74,
    lng: 0.55,
    dominantSoil: 'fluvisol',
    soilNameFr: 'Alluvions de la basse Mina et du bas Chéliff & vertisols',
    soilNameAr: 'طمي وادي مينا والشلف السفلي وتربة التيرس',
    textureFr: 'Argilo-limoneux',
    textureAr: 'طميية طينية',
    ph: 8.0,
    omPct: 1.7,
    limePct: 15.5,
    salinityEC: 2.8,
    whcMm: 170,
    salinityRisk: 'high',
    erosionRisk: 'moderate',
    bioclimate: 'semi_arid',
    rainfallMm: 370,
    tempSummer: 39,
    tempWinter: 7,
    et0: 4.8,
    frostDays: 6,
    siroccoDays: 20,
    dominantCrops: ['citrus', 'greenhouses', 'cereals', 'olives'],
    keyProduceFr: 'Agrumes de la Mina, Tomates, Maraîchage, Céréales',
    keyProduceAr: 'حمضيات وادي مينا، طماطم، خضار، حبوب',
    agronomicHighlightFr: 'Grand périmètre irrigué de la Mina et de Yellel.',
    agronomicHighlightAr: 'محيط السقي الكبير لوادي مينا ويلل، إنتاج غزير للحمضيات والخضار.',
    waterSourceFr: 'Barrages Sidi M’hamed Benaouda & Gargar',
    waterSourceAr: 'سدود سيدي امحمد بن عودة وقرقار',
    damOrBasinFr: 'Barrage Gargar (450M m3)',
    svgCentroid: { x: 430, y: 145 },
  },
  {
    code: 49,
    codeStr: '49',
    id: 'timimoun',
    nameEn: 'Timimoun',
    nameAr: 'تيميمون',
    nameFr: 'Timimoun',
    capitalEn: 'Timimoun',
    capitalAr: 'تيميمون',
    capitalFr: 'Timimoun',
    zone: 'deep_sahara',
    lat: 29.26,
    lng: 0.23,
    dominantSoil: 'arenosol',
    soilNameFr: 'Sables rouges du Gourara & oasis à foggaras',
    soilNameAr: 'رمال قورارة الحمراء وواحات الفقارات',
    textureFr: 'Sable éolien fin',
    textureAr: 'رمل إيولي ناعم',
    ph: 8.1,
    omPct: 0.3,
    limePct: 9.0,
    salinityEC: 2.5,
    whcMm: 45,
    salinityRisk: 'moderate',
    erosionRisk: 'severe',
    bioclimate: 'hyper_arid',
    rainfallMm: 20,
    tempSummer: 45,
    tempWinter: 11,
    et0: 7.5,
    frostDays: 1,
    siroccoDays: 38,
    dominantCrops: ['cereals', 'date_palms', 'pivot_potato'],
    keyProduceFr: 'Blé stratégique sous pivots géants, Dattes Hamraya & Tinacer, Maïs',
    keyProduceAr: 'القمح الاستراتيجي بالري المحوري، تمور الحمرة وتناصر، ذرة',
    agronomicHighlightFr: 'Nouveau grand pôle agricole saharien avec mégas-concessions céréalières.',
    agronomicHighlightAr: 'قطب فلاحي صحراوي صاعد للاستثمارات الكبرى في الحبوب والذرة.',
    waterSourceFr: 'Nappe de l’Albien & Réseau de foggaras du Gourara',
    waterSourceAr: 'مياه طبقة الألبيان الجوفية وشبكة فقارات قورارة',
    damOrBasinFr: 'Continental Intercalaire',
    svgCentroid: { x: 410, y: 440 },
  },
  {
    code: 51,
    codeStr: '51',
    id: 'ouled_djellal',
    nameEn: 'Ouled Djellal',
    nameAr: 'أولاد جلال',
    nameFr: 'Ouled Djellal',
    capitalEn: 'Ouled Djellal',
    capitalAr: 'أولاد جلال',
    capitalFr: 'Ouled Djellal',
    zone: 'sahara_oasis',
    lat: 34.43,
    lng: 5.06,
    dominantSoil: 'arenosol',
    soilNameFr: 'Sols sablo-gypseux & alluvions de l’oued Djedi',
    soilNameAr: 'تربة رملية جبسية وطمي وادي جدي',
    textureFr: 'Sablo-limoneux',
    textureAr: 'رملية طميية',
    ph: 8.1,
    omPct: 0.6,
    limePct: 18.0,
    salinityEC: 3.4,
    whcMm: 80,
    salinityRisk: 'high',
    erosionRisk: 'high',
    bioclimate: 'arid',
    rainfallMm: 140,
    tempSummer: 43,
    tempWinter: 9,
    et0: 6.0,
    frostDays: 3,
    siroccoDays: 32,
    dominantCrops: ['livestock', 'date_palms', 'greenhouses', 'pivot_potato'],
    keyProduceFr: 'Berceau mondial de la race ovine Ouled Djellal, Dattes Deglet Nour, Primeurs',
    keyProduceAr: 'المهد العالمي لسلالة أغنام أولاد جلال البيضاء، تمور دقلة نور، خضار مبكرة',
    agronomicHighlightFr: 'Capitale mondiale et berceau génétique de la race ovine blanche Ouled Djellal.',
    agronomicHighlightAr: 'العاصمة والمهد الجيني لأشهر سلالة أغنام في شمال إفريقيا.',
    waterSourceFr: 'Nappe Albienne & Oued Djedi',
    waterSourceAr: 'طبقة الألبيان ووادي جدي',
    damOrBasinFr: 'Bassin de l’Oued Djedi',
    svgCentroid: { x: 590, y: 220 },
  },
  {
    code: 55,
    codeStr: '55',
    id: 'touggourt',
    nameEn: 'Touggourt',
    nameAr: 'تقرت',
    nameFr: 'Touggourt',
    capitalEn: 'Touggourt',
    capitalAr: 'تقرت',
    capitalFr: 'Touggourt',
    zone: 'sahara_oasis',
    lat: 33.10,
    lng: 6.06,
    dominantSoil: 'solonchak',
    soilNameFr: 'Sols gypso-salins de l’Oued Righ & sables d’oasis',
    soilNameAr: 'تربة وادي ريغ الجبسية الملحية ورمال الواحات',
    textureFr: 'Sablo-limoneux salé',
    textureAr: 'رملية طميية ملحية',
    ph: 8.2,
    omPct: 0.5,
    limePct: 15.0,
    salinityEC: 4.5,
    whcMm: 65,
    salinityRisk: 'severe',
    erosionRisk: 'high',
    bioclimate: 'hyper_arid',
    rainfallMm: 60,
    tempSummer: 45,
    tempWinter: 10,
    et0: 6.9,
    frostDays: 1,
    siroccoDays: 36,
    dominantCrops: ['date_palms', 'pivot_potato', 'greenhouses'],
    keyProduceFr: 'Capitale de la vallée de l’Oued Righ (Dattes Deglet Nour royales, Cultures sous pivot)',
    keyProduceAr: 'عاصمة وادي ريغ العريق (تمور دقلة نور الفاخرة، زراعات بالري المحوري)',
    agronomicHighlightFr: 'Palmeraies historiques de l’Oued Righ avec plus de 1.8 million de dattiers.',
    agronomicHighlightAr: 'واحات وادي ريغ التاريخية بأكثر من 1.8 مليون نخلة منتجة.',
    waterSourceFr: 'Nappes du Complexe Terminal et de l’Albien, Canal de l’Oued Righ',
    waterSourceAr: 'طبقات المركب النهائي والألبيان وقناة وادي ريغ',
    damOrBasinFr: 'Vallée de l’Oued Righ',
    svgCentroid: { x: 635, y: 270 },
  },
  {
    code: 58,
    codeStr: '58',
    id: 'el_menia',
    nameEn: 'El Menia',
    nameAr: 'المنيعة',
    nameFr: 'El Menia',
    capitalEn: 'El Menia',
    capitalAr: 'المنيعة',
    capitalFr: 'El Menia',
    zone: 'deep_sahara',
    lat: 30.58,
    lng: 2.88,
    dominantSoil: 'arenosol',
    soilNameFr: 'Sables fertiles d’El Goléa & grands périmètres Albien',
    soilNameAr: 'رمال القليعة العذبة ومحيطات الامتياز الفلاحي بالألبيان',
    textureFr: 'Sablo-limoneux fin',
    textureAr: 'رملية إلى رملية طميية',
    ph: 7.9,
    omPct: 0.4,
    limePct: 8.0,
    salinityEC: 1.6,
    whcMm: 60,
    salinityRisk: 'low',
    erosionRisk: 'severe',
    bioclimate: 'hyper_arid',
    rainfallMm: 45,
    tempSummer: 44,
    tempWinter: 9,
    et0: 6.5,
    frostDays: 2,
    siroccoDays: 36,
    dominantCrops: ['cereals', 'pivot_potato', 'arboriculture', 'greenhouses'],
    keyProduceFr: 'Blé stratégique sous pivots géants, Agrumes renommés d’El Goléa, Plants de pomme de terre',
    keyProduceAr: 'القمح الاستراتيجي بالري المحوري، حمضيات القليعة الحلوة، بذور البطاطا',
    agronomicHighlightFr: 'Grand pôle agricole du Sud bénéficiant d’une eau artésienne exceptionnellement douce.',
    agronomicHighlightAr: 'قطب فلاحي عملاق بالجنوب يتميز بعذوبة استثنائية لمياه طبقة الألبيان الارتوازية.',
    waterSourceFr: 'Forages artésiens de l’Albien de haute qualité (TDS < 1.2 g/L)',
    waterSourceAr: 'آبار ارتوازية عذبة من طبقة الألبيان (ملوحة منخفضة)',
    damOrBasinFr: 'Continental Intercalaire',
    svgCentroid: { x: 505, y: 390 },
  },
];
