// Crop-specific calculator packages: pre-fill calculators with research-backed defaults.
export interface CropPackage {
  id: string; name: string; icon: string;
  defaults: {
    plantPopulation?: { rowSpacing: number; plantSpacing: number; area: number };
    seedRate?: { targetPop: number; testWeight: number; germination: number; purity: number };
    fertilizer?: { nRate: number };
    etc?: { kc: number; et0: number };
    harvestIndex?: { economic: number; biological: number };
    irrigation?: { raw: number; etc: number };
    taw?: { fc: number; pwp: number; rootDepth: number };
  };
  typicalYield: string; growingSeason: string; description: string;
}

export const cropPackages: CropPackage[] = [
  { id: 'maize', name: 'Maize', icon: 'Sprout', defaults: { plantPopulation: { rowSpacing: 75, plantSpacing: 25, area: 10000 }, seedRate: { targetPop: 53333, testWeight: 350, germination: 90, purity: 98 }, fertilizer: { nRate: 120 }, etc: { kc: 1.15, et0: 5 }, harvestIndex: { economic: 5000, biological: 12000 }, irrigation: { raw: 60, etc: 5 }, taw: { fc: 0.30, pwp: 0.12, rootDepth: 0.6 } }, typicalYield: '5–12 t/ha', growingSeason: '90–120 days', description: 'High N demand. Critical stages: silking and grain fill.' },
  { id: 'wheat', name: 'Wheat', icon: 'Sprout', defaults: { plantPopulation: { rowSpacing: 15, plantSpacing: 5, area: 10000 }, seedRate: { targetPop: 350, testWeight: 40, germination: 90, purity: 98 }, fertilizer: { nRate: 100 }, etc: { kc: 1.15, et0: 4 }, harvestIndex: { economic: 4500, biological: 11000 }, irrigation: { raw: 55, etc: 4 }, taw: { fc: 0.28, pwp: 0.10, rootDepth: 0.5 } }, typicalYield: '3–8 t/ha', growingSeason: '110–150 days', description: 'Cool-season cereal. Critical stages: booting, flowering.' },
  { id: 'rice', name: 'Rice', icon: 'Sprout', defaults: { plantPopulation: { rowSpacing: 20, plantSpacing: 15, area: 10000 }, seedRate: { targetPop: 33333, testWeight: 25, germination: 85, purity: 98 }, fertilizer: { nRate: 90 }, etc: { kc: 1.20, et0: 5 }, harvestIndex: { economic: 4500, biological: 10000 }, irrigation: { raw: 70, etc: 5 }, taw: { fc: 0.35, pwp: 0.15, rootDepth: 0.4 } }, typicalYield: '4–8 t/ha', growingSeason: '100–130 days', description: 'High water demand. Critical stage: panicle initiation.' },
  { id: 'tomato', name: 'Tomato', icon: 'Sprout', defaults: { plantPopulation: { rowSpacing: 60, plantSpacing: 40, area: 10000 }, seedRate: { targetPop: 41667, testWeight: 3, germination: 85, purity: 98 }, fertilizer: { nRate: 150 }, etc: { kc: 1.15, et0: 5 }, harvestIndex: { economic: 40000, biological: 80000 }, irrigation: { raw: 40, etc: 5 }, taw: { fc: 0.25, pwp: 0.10, rootDepth: 0.5 } }, typicalYield: '30–60 t/ha', growingSeason: '90–120 days', description: 'High-value vegetable. Demanding on N and K.' },
  { id: 'potato', name: 'Potato', icon: 'Sprout', defaults: { plantPopulation: { rowSpacing: 75, plantSpacing: 30, area: 10000 }, seedRate: { targetPop: 44444, testWeight: 50, germination: 95, purity: 99 }, fertilizer: { nRate: 140 }, etc: { kc: 1.10, et0: 4.5 }, harvestIndex: { economic: 30000, biological: 60000 }, irrigation: { raw: 45, etc: 4.5 }, taw: { fc: 0.22, pwp: 0.08, rootDepth: 0.4 } }, typicalYield: '20–50 t/ha', growingSeason: '90–120 days', description: 'Shallow roots. High K demand. Critical: tuber bulking.' },
  { id: 'cotton', name: 'Cotton', icon: 'Sprout', defaults: { plantPopulation: { rowSpacing: 80, plantSpacing: 30, area: 10000 }, seedRate: { targetPop: 41667, testWeight: 100, germination: 80, purity: 98 }, fertilizer: { nRate: 120 }, etc: { kc: 1.10, et0: 5.5 }, harvestIndex: { economic: 2500, biological: 8000 }, irrigation: { raw: 65, etc: 5.5 }, taw: { fc: 0.28, pwp: 0.11, rootDepth: 0.9 } }, typicalYield: '1.5–3.5 t/ha', growingSeason: '150–180 days', description: 'Deep-rooted. Critical: flowering and boll development.' },
  { id: 'soybean', name: 'Soybean', icon: 'Sprout', defaults: { plantPopulation: { rowSpacing: 45, plantSpacing: 5, area: 10000 }, seedRate: { targetPop: 444444, testWeight: 180, germination: 90, purity: 98 }, fertilizer: { nRate: 30 }, etc: { kc: 1.10, et0: 4.5 }, harvestIndex: { economic: 3000, biological: 8000 }, irrigation: { raw: 55, etc: 4.5 }, taw: { fc: 0.27, pwp: 0.10, rootDepth: 0.6 } }, typicalYield: '2–4 t/ha', growingSeason: '100–130 days', description: 'N-fixing legume. Low N fertilizer need.' },
  { id: 'sorghum', name: 'Sorghum', icon: 'Sprout', defaults: { plantPopulation: { rowSpacing: 75, plantSpacing: 15, area: 10000 }, seedRate: { targetPop: 88889, testWeight: 30, germination: 85, purity: 98 }, fertilizer: { nRate: 80 }, etc: { kc: 1.05, et0: 5 }, harvestIndex: { economic: 3500, biological: 9000 }, irrigation: { raw: 55, etc: 4 }, taw: { fc: 0.25, pwp: 0.10, rootDepth: 0.8 } }, typicalYield: '2–5 t/ha', growingSeason: '90–120 days', description: 'Drought-tolerant. Deep roots. Critical: grain fill.' },
  { id: 'cassava', name: 'Cassava', icon: 'Sprout', defaults: { plantPopulation: { rowSpacing: 100, plantSpacing: 100, area: 10000 }, seedRate: { targetPop: 10000, testWeight: 500, germination: 90, purity: 99 }, fertilizer: { nRate: 50 }, etc: { kc: 0.90, et0: 4.5 }, harvestIndex: { economic: 25000, biological: 50000 }, irrigation: { raw: 80, etc: 4 }, taw: { fc: 0.20, pwp: 0.08, rootDepth: 1.0 } }, typicalYield: '15–40 t/ha', growingSeason: '8–12 months', description: 'Tropical tuber. Drought-tolerant. Low input.' },
  { id: 'sugarcane', name: 'Sugarcane', icon: 'Sprout', defaults: { plantPopulation: { rowSpacing: 90, plantSpacing: 30, area: 10000 }, seedRate: { targetPop: 37037, testWeight: 250, germination: 85, purity: 98 }, fertilizer: { nRate: 150 }, etc: { kc: 1.25, et0: 5 }, harvestIndex: { economic: 80000, biological: 120000 }, irrigation: { raw: 70, etc: 5 }, taw: { fc: 0.30, pwp: 0.12, rootDepth: 0.8 } }, typicalYield: '70–130 t/ha', growingSeason: '10–14 months', description: 'Very high N and K demand. Critical: tillering.' },
  { id: 'banana', name: 'Banana', icon: 'Sprout', defaults: { plantPopulation: { rowSpacing: 250, plantSpacing: 250, area: 10000 }, seedRate: { targetPop: 1600, testWeight: 1000, germination: 100, purity: 100 }, fertilizer: { nRate: 200 }, etc: { kc: 1.10, et0: 4.5 }, harvestIndex: { economic: 40000, biological: 80000 }, irrigation: { raw: 50, etc: 4.5 }, taw: { fc: 0.30, pwp: 0.12, rootDepth: 0.5 } }, typicalYield: '30–60 t/ha', growingSeason: '12–18 months', description: 'Extremely high K demand. Drip recommended.' },
  { id: 'coffee', name: 'Coffee', icon: 'Sprout', defaults: { plantPopulation: { rowSpacing: 250, plantSpacing: 200, area: 10000 }, seedRate: { targetPop: 2000, testWeight: 200, germination: 85, purity: 98 }, fertilizer: { nRate: 120 }, etc: { kc: 0.95, et0: 4 }, harvestIndex: { economic: 1200, biological: 4000 }, irrigation: { raw: 60, etc: 4 }, taw: { fc: 0.28, pwp: 0.10, rootDepth: 0.6 } }, typicalYield: '0.5–1.5 t/ha', growingSeason: 'Perennial', description: 'Perennial. Critical: flowering and cherry development.' },
];

export const calculatorFormulaCode: Record<string, string> = {
  plantPopulation: '2.1', seedRate: '2.2', fertilizer: '4.1', etc: 'IRR-10.4',
  harvestIndex: '8.9', irrigation: 'IRR-9.3', taw: 'IRR-11.9',
};
export type CropCalculatorKey = keyof typeof calculatorFormulaCode;
