/**
 * Irrigation crop data — BRL/COM irrigation memento (Bas-Rhône Languedoc / Compagnie Nationale d'Aménagement).
 *
 * 35 crops with annual water consumption (ETc) and net irrigation requirement,
 * plus an 18-value decadal (10-day) irrigation distribution covering Apr–Sep
 * (3 decades per month × 6 months). Decadal values are generated by a triangular
 * kernel centred on the crop's peak-demand month and normalised so the sum
 * approximates `annual_irrigation_mm`. Decades outside the crop's season are 0.
 *
 * Annual figures are taken verbatim from the BRL/COM memento. Per-crop season
 * windows and peak months are agronomic defaults (Mediterranean France).
 */

export type CropCategory = 'vegetable' | 'fruit' | 'cereal' | 'industrial' | 'forage';

export interface CropIrrigationData {
  id: string;
  name_fr: string;
  name_en: string;
  category: CropCategory;
  /** Total seasonal crop evapotranspiration (mm). */
  annual_consumption_mm: number;
  /** Net seasonal irrigation requirement (mm) = ETc − effective rainfall. */
  annual_irrigation_mm: number;
  /** 18 decadal irrigation depths (mm), Apr-D1 … Sep-D3, summing ≈ annual_irrigation_mm. */
  decadal_irrigation_mm: number[];
  /** Human-readable season window (e.g. "Apr–Sep"). */
  season_months: string;
  notes: string;
}

/** 18 decade labels: 3 per month for April through September. */
export const DECADAL_MONTHS = [
  'Apr-D1', 'Apr-D2', 'Apr-D3',
  'May-D1', 'May-D2', 'May-D3',
  'Jun-D1', 'Jun-D2', 'Jun-D3',
  'Jul-D1', 'Jul-D2', 'Jul-D3',
  'Aug-D1', 'Aug-D2', 'Aug-D3',
  'Sep-D1', 'Sep-D2', 'Sep-D3',
] as const;

/**
 * Build an 18-value decadal irrigation distribution using a triangular kernel.
 * The kernel rises linearly from `seasonStart` to `peak` and falls linearly
 * from `peak` to `seasonEnd`. Values outside [seasonStart, seasonEnd] are 0.
 * The kernel is then normalised so the rounded sum approximates `annual`.
 */
function buildDecadal(
  annual: number,
  seasonStart: number,
  seasonEnd: number,
  peak: number,
): number[] {
  const arr = new Array(18).fill(0);
  const leftSpan = Math.max(1, peak - seasonStart + 1);
  const rightSpan = Math.max(1, seasonEnd - peak + 1);
  let total = 0;
  for (let i = seasonStart; i <= seasonEnd; i++) {
    const w = i <= peak ? (i - seasonStart + 1) / leftSpan : (seasonEnd - i + 1) / rightSpan;
    arr[i] = w;
    total += w;
  }
  for (let i = 0; i < 18; i++) {
    arr[i] = total > 0 ? Math.round((annual * arr[i]) / total) : 0;
  }
  return arr;
}

export const CROP_IRRIGATION_DATA: CropIrrigationData[] = [
  // === Vegetables (18) ===
  { id: 'asparagus', name_fr: 'Asperge', name_en: 'Asparagus', category: 'vegetable',
    annual_consumption_mm: 548, annual_irrigation_mm: 364,
    decadal_irrigation_mm: buildDecadal(364, 0, 17, 7), season_months: 'Apr–Sep',
    notes: 'Perennial crown crop; maintain even moisture through spear harvest and fern development.' },
  { id: 'eggplant', name_fr: 'Aubergine', name_en: 'Eggplant', category: 'vegetable',
    annual_consumption_mm: 547, annual_irrigation_mm: 358,
    decadal_irrigation_mm: buildDecadal(358, 3, 17, 10), season_months: 'May–Sep',
    notes: 'Sensitive to water stress at flowering; drip irrigation recommended for fruit set.' },
  { id: 'summer_carrot', name_fr: 'Carotte d\'été', name_en: 'Summer Carrot', category: 'vegetable',
    annual_consumption_mm: 423, annual_irrigation_mm: 287,
    decadal_irrigation_mm: buildDecadal(287, 3, 17, 9), season_months: 'May–Sep',
    notes: 'Keep surface moist during emergence; reduce irrigation near harvest to avoid splitting.' },
  { id: 'zucchini', name_fr: 'Courgette', name_en: 'Zucchini', category: 'vegetable',
    annual_consumption_mm: 468, annual_irrigation_mm: 299,
    decadal_irrigation_mm: buildDecadal(299, 3, 17, 9), season_months: 'May–Sep',
    notes: 'Frequent light irrigation during fruit expansion; avoid overhead watering to limit mildew.' },
  { id: 'strawberry', name_fr: 'Fraisier', name_en: 'Strawberry', category: 'vegetable',
    annual_consumption_mm: 688, annual_irrigation_mm: 466,
    decadal_irrigation_mm: buildDecadal(466, 0, 11, 4), season_months: 'Apr–Jul',
    notes: 'Critical water needs at flowering and fruit ripening; drip + mulch to keep berries clean.' },
  { id: 'early_melon_tunnel', name_fr: 'Melon précoce (tunnel)', name_en: 'Early Melon (tunnel)', category: 'vegetable',
    annual_consumption_mm: 329, annual_irrigation_mm: 142,
    decadal_irrigation_mm: buildDecadal(142, 0, 11, 5), season_months: 'Apr–Jul',
    notes: 'Protected culture reduces ET; maintain soil moisture through fruit sizing.' },
  { id: 'season_melon_mulched', name_fr: 'Melon de saison (paillé)', name_en: 'Season Melon (mulched)', category: 'vegetable',
    annual_consumption_mm: 343, annual_irrigation_mm: 183,
    decadal_irrigation_mm: buildDecadal(183, 3, 14, 7), season_months: 'May–Aug',
    notes: 'Plastic mulch + drip; cut irrigation 7–10 days before harvest to raise sugar.' },
  { id: 'late_melon', name_fr: 'Melon tardif', name_en: 'Late Melon', category: 'vegetable',
    annual_consumption_mm: 401, annual_irrigation_mm: 291,
    decadal_irrigation_mm: buildDecadal(291, 6, 17, 10), season_months: 'Jun–Sep',
    notes: 'Open-field late crop; peak demand in July–August during fruit filling.' },
  { id: 'bell_pepper', name_fr: 'Poivron', name_en: 'Bell Pepper', category: 'vegetable',
    annual_consumption_mm: 509, annual_irrigation_mm: 335,
    decadal_irrigation_mm: buildDecadal(335, 3, 17, 10), season_months: 'May–Sep',
    notes: 'Avoid water stress at flowering; uneven moisture causes flower drop and blossom-end rot.' },
  { id: 'early_potato', name_fr: 'Pomme de terre précoce', name_en: 'Early Potato', category: 'vegetable',
    annual_consumption_mm: 287, annual_irrigation_mm: 94,
    decadal_irrigation_mm: buildDecadal(94, 0, 8, 4), season_months: 'Apr–Jun',
    notes: 'Short cycle; light irrigation at tuber initiation is sufficient in most years.' },
  { id: 'storage_potato', name_fr: 'Pomme de terre de conservation', name_en: 'Storage Potato', category: 'vegetable',
    annual_consumption_mm: 569, annual_irrigation_mm: 360,
    decadal_irrigation_mm: buildDecadal(360, 3, 17, 7), season_months: 'May–Sep',
    notes: 'Peak demand at tuber bulking (Jun–Jul); stop irrigation 2–3 weeks before desiccation.' },
  { id: 'summer_lettuce', name_fr: 'Laitue d\'été', name_en: 'Summer Lettuce', category: 'vegetable',
    annual_consumption_mm: 283, annual_irrigation_mm: 157,
    decadal_irrigation_mm: buildDecadal(157, 3, 14, 6), season_months: 'May–Aug',
    notes: 'Frequent light irrigation; brief water stress triggers tipburn and bolting.' },
  { id: 'field_tomato', name_fr: 'Tomate de plein champ', name_en: 'Field Tomato', category: 'vegetable',
    annual_consumption_mm: 583, annual_irrigation_mm: 395,
    decadal_irrigation_mm: buildDecadal(395, 3, 17, 10), season_months: 'May–Sep',
    notes: 'Critical at flowering and fruit sizing; deficit irrigation near harvest enhances flavour.' },
  { id: 'garlic', name_fr: 'Ail', name_en: 'Garlic', category: 'vegetable',
    annual_consumption_mm: 418, annual_irrigation_mm: 218,
    decadal_irrigation_mm: buildDecadal(218, 0, 8, 2), season_months: 'Apr–Jun',
    notes: 'Stop irrigation 2–3 weeks before harvest to allow bulbs to cure and store well.' },
  { id: 'shallot', name_fr: 'Échalote', name_en: 'Shallot', category: 'vegetable',
    annual_consumption_mm: 454, annual_irrigation_mm: 255,
    decadal_irrigation_mm: buildDecadal(255, 0, 11, 4), season_months: 'Apr–Jul',
    notes: 'Moderate demand through bulbing; reduce water as tops begin to lodge.' },
  { id: 'onion', name_fr: 'Oignon', name_en: 'Onion', category: 'vegetable',
    annual_consumption_mm: 526, annual_irrigation_mm: 331,
    decadal_irrigation_mm: buildDecadal(331, 0, 14, 7), season_months: 'Apr–Aug',
    notes: 'Shallow root system; maintain moisture through bulbing, then dry down for storage.' },
  { id: 'green_bean', name_fr: 'Haricot vert', name_en: 'Green Bean', category: 'vegetable',
    annual_consumption_mm: 471, annual_irrigation_mm: 294,
    decadal_irrigation_mm: buildDecadal(294, 3, 14, 7), season_months: 'May–Aug',
    notes: 'Critical at flowering and pod set; avoid overhead irrigation during bloom.' },
  { id: 'pea', name_fr: 'Pois', name_en: 'Pea', category: 'vegetable',
    annual_consumption_mm: 540, annual_irrigation_mm: 323,
    decadal_irrigation_mm: buildDecadal(323, 0, 8, 3), season_months: 'Apr–Jun',
    notes: 'Cool-season legume; irrigation at flowering prolongs pod fill and yield.' },

  // === Fruits & Orchards (7) ===
  { id: 'apricot', name_fr: 'Abricotier', name_en: 'Apricot', category: 'fruit',
    annual_consumption_mm: 437, annual_irrigation_mm: 235,
    decadal_irrigation_mm: buildDecadal(235, 0, 11, 4), season_months: 'Apr–Jul',
    notes: 'Irrigate after pit hardening and through final fruit swell; avoid excess near harvest.' },
  { id: 'apple', name_fr: 'Pommier', name_en: 'Apple', category: 'fruit',
    annual_consumption_mm: 1051, annual_irrigation_mm: 787,
    decadal_irrigation_mm: buildDecadal(787, 0, 17, 9), season_months: 'Apr–Sep',
    notes: 'High seasonal ET; critical stages are cell division (post-bloom) and fruit expansion.' },
  { id: 'cherry', name_fr: 'Cerisier', name_en: 'Cherry', category: 'fruit',
    annual_consumption_mm: 738, annual_irrigation_mm: 338,
    decadal_irrigation_mm: buildDecadal(338, 0, 11, 4), season_months: 'Apr–Jul',
    notes: 'Irrigate through fruit coloring; rapid swings cause cracking. Stop at harvest.' },
  { id: 'peach', name_fr: 'Pêcher', name_en: 'Peach', category: 'fruit',
    annual_consumption_mm: 778, annual_irrigation_mm: 539,
    decadal_irrigation_mm: buildDecadal(539, 0, 17, 9), season_months: 'Apr–Sep',
    notes: 'Peak demand during stage III fruit growth (final swell); RDI after pit hardening saves water.' },
  { id: 'vineyard', name_fr: 'Vigne', name_en: 'Vineyard', category: 'fruit',
    annual_consumption_mm: 838, annual_irrigation_mm: 601,
    decadal_irrigation_mm: buildDecadal(601, 0, 17, 10), season_months: 'Apr–Sep',
    notes: 'Regulated deficit irrigation between fruit set and véraison improves quality without hurting yield.' },
  { id: 'olive', name_fr: 'Olivier', name_en: 'Olive', category: 'fruit',
    annual_consumption_mm: 891, annual_irrigation_mm: 652,
    decadal_irrigation_mm: buildDecadal(652, 0, 17, 10), season_months: 'Apr–Sep',
    notes: 'Drought-tolerant but responds strongly to irrigation at pit hardening and oil accumulation.' },
  { id: 'citrus', name_fr: 'Agrumes', name_en: 'Citrus', category: 'fruit',
    annual_consumption_mm: 804, annual_irrigation_mm: 559,
    decadal_irrigation_mm: buildDecadal(559, 0, 17, 10), season_months: 'Apr–Sep',
    notes: 'Steady moisture through cell expansion; stress drops fruit size and quality.' },

  // === Cereals (5) ===
  { id: 'durum_wheat', name_fr: 'Blé dur', name_en: 'Durum Wheat', category: 'cereal',
    annual_consumption_mm: 308, annual_irrigation_mm: 159,
    decadal_irrigation_mm: buildDecadal(159, 0, 8, 1), season_months: 'Apr–Jun',
    notes: 'Winter cereal; spring irrigation supports stem elongation and grain fill.' },
  { id: 'soft_wheat', name_fr: 'Blé tendre', name_en: 'Soft Wheat', category: 'cereal',
    annual_consumption_mm: 430, annual_irrigation_mm: 139,
    decadal_irrigation_mm: buildDecadal(139, 0, 8, 1), season_months: 'Apr–Jun',
    notes: 'One or two spring irrigations at booting and anthesis typically maximise yield.' },
  { id: 'barley', name_fr: 'Orge', name_en: 'Barley', category: 'cereal',
    annual_consumption_mm: 663, annual_irrigation_mm: 229,
    decadal_irrigation_mm: buildDecadal(229, 0, 8, 1), season_months: 'Apr–Jun',
    notes: 'Earlier maturing than wheat; irrigation at booting is the highest-return application.' },
  { id: 'grain_maize', name_fr: 'Maïs grain', name_en: 'Grain Maize', category: 'cereal',
    annual_consumption_mm: 1342, annual_irrigation_mm: 773,
    decadal_irrigation_mm: buildDecadal(773, 3, 17, 10), season_months: 'May–Sep',
    notes: 'High-demand summer cereal; critical window is tasseling through grain fill.' },
  { id: 'sorghum', name_fr: 'Sorgho', name_en: 'Sorghum', category: 'cereal',
    annual_consumption_mm: 512, annual_irrigation_mm: 191,
    decadal_irrigation_mm: buildDecadal(191, 3, 17, 10), season_months: 'May–Sep',
    notes: 'Drought-tolerant C4; irrigation at booting and flowering protects yield in dry years.' },

  // === Forage (2) ===
  { id: 'forage_maize', name_fr: 'Maïs fourrage', name_en: 'Forage Maize', category: 'forage',
    annual_consumption_mm: 761, annual_irrigation_mm: 473,
    decadal_irrigation_mm: buildDecadal(473, 3, 17, 10), season_months: 'May–Sep',
    notes: 'Whole-plant silage; high biomass production drives high water demand through summer.' },
  { id: 'alfalfa', name_fr: 'Luzerne', name_en: 'Alfalfa', category: 'forage',
    annual_consumption_mm: 554, annual_irrigation_mm: 309,
    decadal_irrigation_mm: buildDecadal(309, 0, 17, 8), season_months: 'Apr–Sep',
    notes: 'Deep-rooted perennial; irrigate after each cut to regrow the canopy before the next.' },

  // === Industrial Crops (3) ===
  { id: 'soybean', name_fr: 'Soja', name_en: 'Soybean', category: 'industrial',
    annual_consumption_mm: 1118, annual_irrigation_mm: 626,
    decadal_irrigation_mm: buildDecadal(626, 3, 17, 10), season_months: 'May–Sep',
    notes: 'Critical at flowering and pod fill; water stress at pod set causes major yield loss.' },
  { id: 'sunflower', name_fr: 'Tournesol', name_en: 'Sunflower', category: 'industrial',
    annual_consumption_mm: 530, annual_irrigation_mm: 298,
    decadal_irrigation_mm: buildDecadal(298, 0, 14, 7), season_months: 'Apr–Aug',
    notes: 'Deep taproot tolerates moderate stress; irrigation from bud to flowering raises oil yield.' },
  { id: 'rapeseed', name_fr: 'Colza', name_en: 'Rapeseed', category: 'industrial',
    annual_consumption_mm: 603, annual_irrigation_mm: 341,
    decadal_irrigation_mm: buildDecadal(341, 0, 8, 1), season_months: 'Apr–Jun',
    notes: 'Winter crop; spring irrigation supports stem elongation and pod fill before harvest.' },
];

/** Lookup a single crop by id. */
export function getCropIrrigation(id: string): CropIrrigationData | undefined {
  return CROP_IRRIGATION_DATA.find((c) => c.id === id);
}

/** Filter crops by category. */
export function getCropsByCategory(category: CropCategory): CropIrrigationData[] {
  return CROP_IRRIGATION_DATA.filter((c) => c.category === category);
}
