/**
 * Professional report generator — combines data from all app features
 * into a single multi-page branded PDF report.
 *
 * Pulls from: soil history, season plan, irrigation program, scouting log,
 * financial dashboard, sustainability scorecard, and weather forecast.
 */

export interface ReportConfig {
  farmName: string;
  farmerName: string;
  reportDate: string;
  reportType: 'season_plan' | 'soil_analysis' | 'financial' | 'comprehensive' | 'irrigation';
  includeSections: {
    farmSummary: boolean;
    soilAnalysis: boolean;
    irrigationPlan: boolean;
    seasonPlan: boolean;
    scoutingLog: boolean;
    financialSummary: boolean;
    sustainabilityScore: boolean;
    weatherForecast: boolean;
    recommendations: boolean;
  };
}

export const DEFAULT_CONFIG: ReportConfig = {
  farmName: 'My Farm',
  farmerName: 'Farmer',
  reportDate: new Date().toISOString().slice(0, 10),
  reportType: 'comprehensive',
  includeSections: {
    farmSummary: true,
    soilAnalysis: true,
    irrigationPlan: true,
    seasonPlan: true,
    scoutingLog: true,
    financialSummary: true,
    sustainabilityScore: true,
    weatherForecast: true,
    recommendations: true,
  },
};

/** Generate a professional multi-page HTML report for printing to PDF. */
export function generateReport(
  config: ReportConfig,
  data: {
    soilLatest?: { ph: number; om: number; cec: number; ca: number; mg: number; k: number; p: number; na: number };
    soilTrends?: { label: string; current: number; direction: string; status: string; recommendation: string }[];
    irrigation?: { crop: string; annualMm: number; volumeM3: number; peakMm: number };
    seasonPlan?: { crop: string; weeks: number; totalN: number; totalP: number; totalK: number; totalIrrigation: number };
    scouting?: { total: number; critical: number; warnings: number; recentNotes: string[] };
    financial?: { costs: number; revenue: number; margin: number; roi: number; breakEvenYield: number };
    sustainability?: { nue: number; waterProd: number; carbon: number; soilHealth: number; grade: string };
    weather?: { currentTemp: number; forecast: string; frostRisk: boolean; sprayWindow: string };
    recommendations?: string[];
  }
): string {
  const sections: string[] = [];

  // Cover page
  sections.push(`
    <div class="page cover">
      <div class="cover-content">
        <div class="logo">🌱 Formula Atlas</div>
        <h1>${config.farmName}</h1>
        <h2>${reportTypeLabel(config.reportType)} Report</h2>
        <div class="cover-meta">
          <p>Prepared for: ${config.farmerName}</p>
          <p>Date: ${config.reportDate}</p>
          <p>Generated by: Formula Atlas Agronomy Platform</p>
        </div>
        <div class="cover-footer">This report was generated automatically using the Formula Atlas agronomy platform. All calculations are based on user-input data and internationally recognized agronomic standards (FAO-56, USDA-NRCS, NRC 2021, IPCC 2019).</div>
      </div>
    </div>
  `);

  // Farm Summary
  if (config.includeSections.farmSummary) {
    sections.push(`
      <div class="page">
        <h1>📋 Farm Summary</h1>
        <table class="summary-table">
          <tr><td>Farm Name</td><td>${config.farmName}</td></tr>
          <tr><td>Farmer</td><td>${config.farmerName}</td></tr>
          <tr><td>Report Date</td><td>${config.reportDate}</td></tr>
          <tr><td>Report Type</td><td>${reportTypeLabel(config.reportType)}</td></tr>
        </table>
        ${data.soilLatest ? `
        <h2>Latest Soil Test</h2>
        <table class="data-table">
          <tr><th>pH</th><th>OM%</th><th>CEC</th><th>Ca</th><th>Mg</th><th>K</th><th>P</th><th>Na</th></tr>
          <tr><td>${data.soilLatest.ph}</td><td>${data.soilLatest.om}</td><td>${data.soilLatest.cec}</td><td>${data.soilLatest.ca}</td><td>${data.soilLatest.mg}</td><td>${data.soilLatest.k}</td><td>${data.soilLatest.p}</td><td>${data.soilLatest.na}</td></tr>
        </table>` : ''}
        ${data.financial ? `
        <h2>Financial Snapshot</h2>
        <div class="stat-grid">
          <div class="stat"><div class="stat-label">Total Costs</div><div class="stat-value neg">$${data.financial.costs.toFixed(0)}/ha</div></div>
          <div class="stat"><div class="stat-label">Total Revenue</div><div class="stat-value pos">$${data.financial.revenue.toFixed(0)}/ha</div></div>
          <div class="stat"><div class="stat-label">Gross Margin</div><div class="stat-value ${data.financial.margin >= 0 ? 'pos' : 'neg'}">$${data.financial.margin.toFixed(0)}/ha</div></div>
          <div class="stat"><div class="stat-label">ROI</div><div class="stat-value ${data.financial.roi >= 0 ? 'pos' : 'neg'}">${data.financial.roi.toFixed(0)}%</div></div>
        </div>` : ''}
      </div>
    `);
  }

  // Soil Analysis
  if (config.includeSections.soilAnalysis && data.soilTrends) {
    const trendRows = data.soilTrends.map(t => `
      <tr><td>${t.label}</td><td style="text-align:center">${t.current}</td><td style="text-transform:capitalize">${t.direction}</td><td style="text-transform:capitalize">${t.status}</td><td>${t.recommendation}</td></tr>
    `).join('');
    sections.push(`
      <div class="page">
        <h1>🧪 Soil Analysis & Trends</h1>
        <table class="data-table full">
          <thead><tr><th>Parameter</th><th>Current</th><th>Trend</th><th>Status</th><th>Recommendation</th></tr></thead>
          <tbody>${trendRows}</tbody>
        </table>
      </div>
    `);
  }

  // Irrigation Plan
  if (config.includeSections.irrigationPlan && data.irrigation) {
    sections.push(`
      <div class="page">
        <h1>💧 Irrigation Plan</h1>
        <div class="stat-grid">
          <div class="stat"><div class="stat-label">Crop</div><div class="stat-value">${data.irrigation.crop}</div></div>
          <div class="stat"><div class="stat-label">Annual Irrigation</div><div class="stat-value">${data.irrigation.annualMm} mm</div></div>
          <div class="stat"><div class="stat-label">Total Volume</div><div class="stat-value">${data.irrigation.volumeM3} m³/ha</div></div>
          <div class="stat"><div class="stat-label">Peak Daily</div><div class="stat-value">${data.irrigation.peakMm} mm/day</div></div>
        </div>
        <p>See the Irrigation Program Generator tool for the full 10-day schedule with decadal breakdown.</p>
      </div>
    `);
  }

  // Season Plan
  if (config.includeSections.seasonPlan && data.seasonPlan) {
    sections.push(`
      <div class="page">
        <h1>📅 Season Plan Summary</h1>
        <div class="stat-grid">
          <div class="stat"><div class="stat-label">Crop</div><div class="stat-value">${data.seasonPlan.crop}</div></div>
          <div class="stat"><div class="stat-label">Plan Length</div><div class="stat-value">${data.seasonPlan.weeks} weeks</div></div>
          <div class="stat"><div class="stat-label">Total N</div><div class="stat-value">${data.seasonPlan.totalN} kg/ha</div></div>
          <div class="stat"><div class="stat-label">Total P</div><div class="stat-value">${data.seasonPlan.totalP} kg/ha</div></div>
          <div class="stat"><div class="stat-label">Total K</div><div class="stat-value">${data.seasonPlan.totalK} kg/ha</div></div>
          <div class="stat"><div class="stat-label">Irrigation</div><div class="stat-value">${data.seasonPlan.totalIrrigation} m³/ha</div></div>
        </div>
        <p>See the Season Plan Generator tool for the full 52-week schedule with fertigation recipes.</p>
      </div>
    `);
  }

  // Scouting Log
  if (config.includeSections.scoutingLog && data.scouting) {
    const notes = data.scouting.recentNotes.map(n => `<li>${n}</li>`).join('');
    sections.push(`
      <div class="page">
        <h1>🔍 Field Scouting Summary</h1>
        <div class="stat-grid">
          <div class="stat"><div class="stat-label">Total Entries</div><div class="stat-value">${data.scouting.total}</div></div>
          <div class="stat"><div class="stat-label">Critical</div><div class="stat-value neg">${data.scouting.critical}</div></div>
          <div class="stat"><div class="stat-label">Warnings</div><div class="stat-value warn">${data.scouting.warnings}</div></div>
        </div>
        ${notes ? `<h2>Recent Observations</h2><ul class="notes">${notes}</ul>` : '<p>No scouting entries recorded.</p>'}
      </div>
    `);
  }

  // Financial Summary
  if (config.includeSections.financialSummary && data.financial) {
    sections.push(`
      <div class="page">
        <h1>💰 Financial Summary</h1>
        <div class="stat-grid">
          <div class="stat"><div class="stat-label">Total Costs</div><div class="stat-value neg">$${data.financial.costs.toFixed(0)}/ha</div></div>
          <div class="stat"><div class="stat-label">Total Revenue</div><div class="stat-value pos">$${data.financial.revenue.toFixed(0)}/ha</div></div>
          <div class="stat"><div class="stat-label">Gross Margin</div><div class="stat-value ${data.financial.margin >= 0 ? 'pos' : 'neg'}">$${data.financial.margin.toFixed(0)}/ha</div></div>
          <div class="stat"><div class="stat-label">ROI</div><div class="stat-value ${data.financial.roi >= 0 ? 'pos' : 'neg'}">${data.financial.roi.toFixed(0)}%</div></div>
          <div class="stat"><div class="stat-label">Break-even Yield</div><div class="stat-value">${data.financial.breakEvenYield.toFixed(2)} t/ha</div></div>
        </div>
      </div>
    `);
  }

  // Sustainability Score
  if (config.includeSections.sustainabilityScore && data.sustainability) {
    sections.push(`
      <div class="page">
        <h1>🌿 Sustainability Scorecard</h1>
        <div class="grade-badge ${data.sustainability.grade}">Grade: ${data.sustainability.grade}</div>
        <table class="data-table full">
          <thead><tr><th>Metric</th><th>Value</th><th>Unit</th></tr></thead>
          <tbody>
            <tr><td>Nitrogen Use Efficiency</td><td>${data.sustainability.nue}</td><td>%</td></tr>
            <tr><td>Water Productivity</td><td>${data.sustainability.waterProd}</td><td>kg/m³</td></tr>
            <tr><td>Carbon Footprint</td><td>${data.sustainability.carbon}</td><td>kg CO₂e/kg</td></tr>
            <tr><td>Soil Health Score</td><td>${data.sustainability.soilHealth}</td><td>/100</td></tr>
          </tbody>
        </table>
      </div>
    `);
  }

  // Weather Forecast
  if (config.includeSections.weatherForecast && data.weather) {
    sections.push(`
      <div class="page">
        <h1>🌤️ Weather Forecast</h1>
        <div class="stat-grid">
          <div class="stat"><div class="stat-label">Current Temp</div><div class="stat-value">${data.weather.currentTemp}°C</div></div>
          <div class="stat"><div class="stat-label">7-Day Outlook</div><div class="stat-value" style="font-size:14px">${data.weather.forecast}</div></div>
          <div class="stat"><div class="stat-label">Frost Risk</div><div class="stat-value ${data.weather.frostRisk ? 'neg' : 'pos'}">${data.weather.frostRisk ? '⚠️ Yes' : '✅ No'}</div></div>
        </div>
        <p><strong>Spray Window:</strong> ${data.weather.sprayWindow}</p>
      </div>
    `);
  }

  // Recommendations
  if (config.includeSections.recommendations && data.recommendations) {
    const recs = data.recommendations.map(r => `<li>${r}</li>`).join('');
    sections.push(`
      <div class="page">
        <h1>💡 AI Recommendations</h1>
        <ul class="recommendations">${recs}</ul>
        <div class="disclaimer">These recommendations are generated by the Formula Atlas AI engine based on the data provided. Always validate with local agronomic expertise and field observation before making critical management decisions.</div>
      </div>
    `);
  }

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${config.farmName} — ${reportTypeLabel(config.reportType)} Report</title><style>
    @page { size: A4; margin: 20mm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, system-ui, 'Segoe UI', Roboto, sans-serif; color: #1e293b; font-size: 12px; line-height: 1.6; }
    .page { page-break-after: always; min-height: 100vh; padding: 20px; }
    .page:last-child { page-break-after: auto; }

    /* Cover */
    .cover { display: flex; align-items: center; justify-content: center; text-align: center; background: linear-gradient(135deg, #16a34a 0%, #0891b2 100%); color: white; }
    .cover-content { max-width: 500px; }
    .logo { font-size: 36px; font-weight: bold; margin-bottom: 20px; }
    .cover h1 { font-size: 32px; margin-bottom: 8px; }
    .cover h2 { font-size: 18px; font-weight: 400; opacity: 0.9; margin-bottom: 40px; }
    .cover-meta { font-size: 14px; opacity: 0.8; margin-bottom: 40px; }
    .cover-meta p { margin: 4px 0; }
    .cover-footer { font-size: 10px; opacity: 0.6; margin-top: 60px; max-width: 400px; margin-left: auto; margin-right: auto; }

    /* Headers */
    h1 { font-size: 20px; color: #16a34a; margin-bottom: 16px; border-bottom: 2px solid #bbf7d0; padding-bottom: 8px; }
    h2 { font-size: 14px; color: #475569; margin: 16px 0 8px; }

    /* Tables */
    table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
    th { background: #ecfdf5; color: #047857; padding: 8px; border: 1px solid #a7f3d0; text-align: left; font-size: 11px; }
    td { padding: 6px 8px; border: 1px solid #d1fae5; font-size: 11px; }
    .summary-table td:first-child { font-weight: 600; color: #475569; width: 40%; }
    .data-table.full th, .data-table.full td { text-align: left; }

    /* Stats */
    .stat-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin-bottom: 16px; }
    .stat { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px; text-align: center; }
    .stat-label { font-size: 9px; color: #64748b; text-transform: uppercase; font-weight: 600; }
    .stat-value { font-size: 18px; font-weight: bold; margin-top: 4px; }
    .pos { color: #16a34a; }
    .neg { color: #dc2626; }
    .warn { color: #ea580c; }

    /* Grade badge */
    .grade-badge { display: inline-block; font-size: 28px; font-weight: bold; padding: 8px 24px; border-radius: 8px; margin-bottom: 16px; }
    .grade-badge.A { background: #dcfce7; color: #16a34a; }
    .grade-badge.B { background: #fef9c3; color: #ca8a04; }
    .grade-badge.C { background: #fed7aa; color: #ea580c; }
    .grade-badge.D { background: #fecaca; color: #dc2626; }

    /* Lists */
    ul.notes, ul.recommendations { padding-left: 20px; }
    ul.notes li, ul.recommendations li { margin-bottom: 6px; font-size: 11px; }
    ul.recommendations li { padding: 6px; background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 4px; margin-bottom: 4px; list-style: none; }

    .disclaimer { font-size: 9px; color: #94a3b8; margin-top: 20px; font-style: italic; border-top: 1px solid #e2e8f0; padding-top: 8px; }
  </style></head><body>${sections.join('')}</body></html>`;
}

function reportTypeLabel(type: ReportConfig['reportType']): string {
  const labels: Record<string, string> = {
    season_plan: 'Season Plan',
    soil_analysis: 'Soil Analysis',
    financial: 'Financial',
    comprehensive: 'Comprehensive Farm',
    irrigation: 'Irrigation',
  };
  return labels[type] || 'Farm';
}

/** Generate AI recommendations combining all data sources. */
export function generateRecommendations(data: {
  soilLatest?: { ph: number; om: number; k: number; p: number };
  financial?: { margin: number; roi: number };
  sustainability?: { nue: number; waterProd: number; soilHealth: number };
  scouting?: { critical: number };
  weather?: { frostRisk: boolean };
}): string[] {
  const recs: string[] = [];

  if (data.soilLatest) {
    if (data.soilLatest.ph < 6.0) recs.push(`🔴 Soil pH ${data.soilLatest.ph} is acidic — apply agricultural lime at 1-2 t/ha before next planting.`);
    else if (data.soilLatest.ph > 7.5) recs.push(`🟡 Soil pH ${data.soilLatest.ph} is alkaline — consider sulfur amendment or acidifying fertigation.`);
    else recs.push(`✅ Soil pH ${data.soilLatest.ph} is optimal — maintain current management.`);

    if (data.soilLatest.om < 2.0) recs.push(`🔴 Organic matter ${data.soilLatest.om}% is low — plant cover crops + apply compost (10-20 t/ha). Target +0.3%/year.`);
    if (data.soilLatest.k < 0.3) recs.push(`🔴 Potassium ${data.soilLatest.k} meq/100g is low — apply K₂O at 80-120 kg/ha (MOP or SOP).`);
    if (data.soilLatest.p < 15) recs.push(`🟡 Phosphorus ${data.soilLatest.p} ppm is low — apply 40-60 kg P₂O₅/ha as DAP or MAP at planting.`);
    else if (data.soilLatest.p > 50) recs.push(`🟡 Phosphorus ${data.soilLatest.p} ppm is high — skip P fertilizer to save cost and prevent runoff.`);
  }

  if (data.financial) {
    if (data.financial.margin < 0) recs.push(`🔴 Operating at a loss ($${data.financial.margin.toFixed(0)}/ha) — reduce costs or increase yield. Focus on the biggest cost categories.`);
    else if (data.financial.roi > 50) recs.push(`💰 Strong ROI (${data.financial.roi.toFixed(0)}%) — consider reinvesting in irrigation or soil improvement for further gains.`);
  }

  if (data.sustainability) {
    if (data.sustainability.nue < 50) recs.push(`🟡 NUE ${data.sustainability.nue}% is below target — split N applications, use inhibitors, or add legumes to rotation.`);
    if (data.sustainability.waterProd < 1.0) recs.push(`🟡 Water productivity ${data.sustainability.waterProd} kg/m³ is low — consider drip irrigation or mulching.`);
    if (data.sustainability.soilHealth < 50) recs.push(`🔴 Soil health score ${data.sustainability.soilHealth}/100 is low — implement cover crops + reduced tillage + compost.`);
  }

  if (data.scouting && data.scouting.critical > 0) {
    recs.push(`🔴 ${data.scouting.critical} critical scouting entries — immediate field visit required.`);
  }

  if (data.weather?.frostRisk) {
    recs.push(`❄️ Frost risk in 7-day forecast — prepare frost cloth or overhead irrigation for protection.`);
  }

  if (recs.length === 0) recs.push('✅ All indicators are in good shape. Continue routine monitoring and management.');

  return recs;
}
