/**
 * WUR crop × substrate matrices
 *
 * Ported verbatim from crops_wur.json — 24 crops × 47 crop×substrate matrices
 * with full NPK + micro targets.
 *
 * Source: Van der Lugt, G. et al. (2020). "Nutrient Solutions for Greenhouse
 * Crops", Version 4. ISBN 9789464021844. Section B (crop pages).
 *
 * `high_water` is deliberately NOT a growth stage. The manual prints it as a
 * fourth adjustment column, but agronomically it is an orthogonal condition —
 * supply above 5 L/m²/day — that can coincide with any stage. It is therefore
 * stored separately as `high_water_adjustment` and driven by its own flag.
 */

import type { WURCrop, WURCropMatrix } from "./wur-types";
import { bi } from "./wur-types";
import { registerCropLookup } from "./wur-fertilizer-catalogue";

// ---------------------------------------------------------------------------
// Substrate labels (基质类型)
// ---------------------------------------------------------------------------
export const SUBSTRATE_TYPES = [
  "INERT_SUBSTRATE",
  "ORGANIC_MATERIAL",
  "SOIL",
] as const;

export const DEFAULT_SUBSTRATE = "INERT_SUBSTRATE";

export const SUBSTRATE_LABELS: Record<string, string> = {
  INERT_SUBSTRATE: bi("Inert Substrate", "岩棉/惰性基质"),
  ORGANIC_MATERIAL: bi("Organic Material", "椰糠/泥炭有机基质"),
  SOIL: bi("Soil", "土壤栽培"),
};

export const EXTRACT_METHODS: Record<string, string> = {
  INERT_SUBSTRATE: "direct",
  ORGANIC_MATERIAL: "1:1.5_volume",
  SOIL: "1:2_volume",
};

export const EXTRACT_METHOD_LABELS: Record<string, string> = {
  direct: bi("Direct solution sample", "直接取根际溶液"),
  "1:1.5_volume": bi("1:1.5 volume water extract", "1:1.5 体积水浸提"),
  "1:2_volume": bi("1:2 volume water extract", "1:2 体积水浸提"),
};

// ---------------------------------------------------------------------------
// Crop categories
// ---------------------------------------------------------------------------
export const CROP_CATEGORIES = [
  "fruiting_vegetables",
  "soft_fruits",
  "leafy_vegetables",
  "cut_flowers",
  "potted_plants",
] as const;

export const CROP_CATEGORY_LABELS: Record<string, string> = {
  fruiting_vegetables: bi("Fruiting Vegetables", "果菜类"),
  soft_fruits: bi("Soft Fruits / Berries", "浆果类"),
  leafy_vegetables: bi("Leafy Vegetables", "叶菜类"),
  cut_flowers: bi("Cut Flowers", "切花类"),
  potted_plants: bi("Potted Plants", "盆栽植物"),
};

// ---------------------------------------------------------------------------
// Growth stage labels
// ---------------------------------------------------------------------------
export const GROWTH_STAGE_LABELS: Record<string, [string, string]> = {
  start: ["Start / Rooting", "定植期 / 生根期"],
  vegetative: ["Vegetative", "营养生长期"],
  flowering: ["Flowering", "花期"],
  fruit_set: ["Fruit Set", "坐果期"],
  production: ["Heavy Bearing / Production", "盛产期"],
  end_season: ["Final Phase / End of Season", "生育末期"],
  winter: ["Winter", "冬季"],
};

export const FRUIT_SET_NOTE_EN =
  "Fruit-set adjustment may vary 0.25-2 mmol/L for K and 0.2-0.75 mmol/L for Ca.";
export const FRUIT_SET_NOTE_ZH =
  "坐果期调整幅度：K 可在 0.25-2 mmol/L、Ca 可在 0.2-0.75 mmol/L 范围内变动。";

export const HIGH_WATER_NOTE_EN =
  "Adjustments for high water supply are recommended when water supply exceeds 5 l/m2/day.";
export const HIGH_WATER_NOTE_ZH =
  "当供水量超过 5 升/平方米/天时，建议进行高供水调整。";

export const END_SEASON_NOTE_EN =
  "End of the crop, after removal of the growth point. Mostly in autumn as the last fruits ripen.";
export const END_SEASON_NOTE_ZH =
  "生育末期，摘心之后；多在秋季末批果实成熟期。";

// ---------------------------------------------------------------------------
// Crop × substrate library
// ---------------------------------------------------------------------------

export const WUR_CROPS: Record<string, WURCrop> = {
  "cucumber": {
    crop_id: "cucumber",
    name_en: "Cucumber",
    name_zh: "\u9ec4\u74dc",
    category: "fruiting_vegetables",
    botanical: "Cucumis sativus",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 41,
        extract_method: "direct",
        ph_root_zone: [5.2, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 3.0,
        ec_fertigation: 2.2,
        root_zone_targets: {
          "Cl": 6.0,
          "NH4": 0.5,
          "K": 8.0,
          "Ca": 6.5,
          "Mg": 3.0,
          "NO3": 18.0,
          "S": 3.5,
          "P": 0.9,
          "Fe": 30.0,
          "Mn": 7.0,
          "Zn": 7.0,
          "B": 50.0,
          "Cu": 1.5,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 1.25,
          "K": 8.0,
          "Ca": 4.0,
          "Mg": 1.375,
          "NO3": 16.0,
          "S": 1.375,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 15.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 25.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 6.0,
        cl_max_root_zone: 6.0,
        growth_stages: {
          "start": {
            "NH4": -0.5,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.25,
            "Fe": 10.0,
            "B": 10.0,
          },
          "end_season": {
            "NH4": -1.0,
            "P": -1.0,
          },
          "fruit_set": {
            "K": 1.0,
            "NO3": 1.0,
          },
        },
        high_water_adjustment: {
          "K": -1.0,
          "Ca": 0.5,
        },
      },
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 42,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.2, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.4,
        ec_fertigation: 2.2,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.5,
          "K": 3.0,
          "Ca": 3.0,
          "Mg": 1.5,
          "NO3": 8.0,
          "S": 1.5,
          "P": 0.7,
          "Fe": 10.0,
          "Mn": 3.0,
          "Zn": 4.0,
          "B": 20.0,
          "Cu": 1.0,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 1.0,
          "K": 8.0,
          "Ca": 4.5,
          "Mg": 1.5,
          "NO3": 16.75,
          "S": 1.5,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 30.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 25.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
          "start": {
            "NH4": -0.5,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.25,
            "Fe": 10.0,
            "B": 10.0,
          },
          "end_season": {
            "NH4": -1.0,
            "P": -1.0,
          },
          "fruit_set": {
            "K": 1.0,
            "NO3": 1.0,
          },
        },
        high_water_adjustment: {
          "K": -1.0,
          "Ca": 0.5,
        },
      },
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 43,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.0,
        ec_fertigation: 1.0,
        root_zone_targets: {
          "Cl": 3.0,
          "NH4": 0.1,
          "K": 1.8,
          "Ca": 2.2,
          "Mg": 1.2,
          "NO3": 4.0,
          "S": 1.5,
          "P": 0.1,
          "Fe": 8.0,
          "Mn": 1.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.9,
          "K": 3.5,
          "Ca": 2.0,
          "Mg": 1.0,
          "NO3": 7.9,
          "S": 1.0,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 2.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.3,
          "Mo": 0.0,
        },
        na_max_root_zone: 3.0,
        cl_max_root_zone: 3.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "eggplant": {
    crop_id: "eggplant",
    name_en: "Eggplant",
    name_zh: "\u8304\u5b50",
    category: "fruiting_vegetables",
    botanical: "Solanum melongena",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 44,
        extract_method: "direct",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 3.0,
        ec_fertigation: 2.1,
        root_zone_targets: {
          "Cl": 6.0,
          "NH4": 0.5,
          "K": 6.2,
          "Ca": 6.2,
          "Mg": 4.5,
          "NO3": 20.0,
          "S": 3.0,
          "P": 0.9,
          "Fe": 25.0,
          "Mn": 7.0,
          "Zn": 7.0,
          "B": 80.0,
          "Cu": 0.7,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 1.5,
          "K": 6.75,
          "Ca": 3.25,
          "Mg": 2.5,
          "NO3": 15.5,
          "S": 1.5,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 15.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 35.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 6.0,
        cl_max_root_zone: 6.0,
        growth_stages: {
          "start": {
            "NH4": -1.0,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.5,
            "Fe": 10.0,
            "B": 10.0,
          },
          "end_season": {
            "NH4": -1.0,
            "P": -1.0,
          },
          "fruit_set": {
            "K": 1.0,
            "NO3": 1.0,
          },
        },
        high_water_adjustment: {
          "K": -1.0,
          "Ca": 0.5,
        },
      },
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 45,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 5.5],
        ph_fertigation: 5.3,
        ec_root_zone: 1.2,
        ec_fertigation: 2.1,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.1,
          "K": 2.5,
          "Ca": 2.5,
          "Mg": 1.5,
          "NO3": 8.0,
          "S": 1.0,
          "P": 0.5,
          "Fe": 15.0,
          "Mn": 3.0,
          "Zn": 4.0,
          "B": 25.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.75,
          "K": 6.0,
          "Ca": 3.75,
          "Mg": 2.75,
          "NO3": 15.5,
          "S": 1.5,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 15.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 35.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
          "start": {
            "NH4": -0.5,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.25,
            "Fe": 10.0,
            "B": 10.0,
          },
          "end_season": {
            "NH4": -0.5,
            "P": -0.5,
          },
          "fruit_set": {
            "K": 1.0,
            "NO3": 1.0,
          },
        },
        high_water_adjustment: {
          "K": -1.0,
          "Ca": 0.5,
        },
      },
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 46,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.2,
        ec_fertigation: 1.0,
        root_zone_targets: {
          "Cl": 3.0,
          "NH4": 0.1,
          "K": 1.8,
          "Ca": 2.0,
          "Mg": 1.5,
          "NO3": 4.5,
          "S": 2.0,
          "P": 0.1,
          "Fe": 8.0,
          "Mn": 1.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.9,
          "K": 3.5,
          "Ca": 2.0,
          "Mg": 1.0,
          "NO3": 7.9,
          "S": 1.0,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 2.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.3,
          "Mo": 0.0,
        },
        na_max_root_zone: 3.0,
        cl_max_root_zone: 3.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "melon": {
    crop_id: "melon",
    name_en: "Melon",
    name_zh: "\u751c\u74dc",
    category: "fruiting_vegetables",
    botanical: "Cucumis melo",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 47,
        extract_method: "direct",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 3.0,
        ec_fertigation: 2.2,
        root_zone_targets: {
          "Cl": 6.0,
          "NH4": 0.5,
          "K": 7.0,
          "Ca": 7.0,
          "Mg": 2.5,
          "NO3": 20.0,
          "S": 3.5,
          "P": 0.8,
          "Fe": 25.0,
          "Mn": 5.0,
          "Zn": 7.0,
          "B": 50.0,
          "Cu": 1.0,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 1.25,
          "K": 8.0,
          "Ca": 4.0,
          "Mg": 1.4,
          "NO3": 16.0,
          "Cl": 0.0,
          "S": 1.4,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 15.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 25.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 6.0,
        cl_max_root_zone: 6.0,
        growth_stages: {
          "start": {
            "NH4": -1.0,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.5,
            "Fe": 10.0,
            "B": 10.0,
          },
          "end_season": {
            "NH4": -1.0,
            "P": -1.0,
          },
          "fruit_set": {
            "K": 1.0,
            "Ca": -0.5,
          },
        },
        high_water_adjustment: {
          "K": -1.0,
          "Ca": 0.5,
        },
      },
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 48,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.8, 5.8],
        ph_fertigation: 5.3,
        ec_root_zone: 1.7,
        ec_fertigation: 2.2,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.1,
          "K": 3.8,
          "Ca": 3.8,
          "Mg": 1.5,
          "NO3": 7.0,
          "S": 2.5,
          "P": 0.5,
          "Fe": 10.0,
          "Mn": 2.0,
          "Zn": 3.0,
          "B": 20.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 1.0,
          "K": 7.5,
          "Ca": 4.75,
          "Mg": 1.25,
          "NO3": 16.25,
          "Cl": 0.0,
          "S": 1.5,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 15.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 25.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
          "start": {
            "NH4": -1.0,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.5,
            "Fe": 10.0,
            "B": 10.0,
          },
          "end_season": {
            "NH4": -1.0,
            "P": -1.0,
          },
          "fruit_set": {
            "K": 1.0,
            "Ca": -0.5,
          },
        },
        high_water_adjustment: {
          "K": -1.0,
          "Ca": 0.5,
        },
      },
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 49,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.0,
        ec_fertigation: 1.0,
        root_zone_targets: {
          "Cl": 3.0,
          "NH4": 0.1,
          "K": 1.8,
          "Ca": 2.2,
          "Mg": 1.2,
          "NO3": 4.0,
          "S": 1.5,
          "P": 0.1,
          "Fe": 8.0,
          "Mn": 1.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.8,
          "K": 4.0,
          "Ca": 1.5,
          "Mg": 1.0,
          "NO3": 7.3,
          "S": 1.0,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 2.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.3,
          "Mo": 0.0,
        },
        na_max_root_zone: 3.0,
        cl_max_root_zone: 3.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "sweet_pepper": {
    crop_id: "sweet_pepper",
    name_en: "Sweet Pepper",
    name_zh: "\u751c\u6912",
    category: "fruiting_vegetables",
    botanical: "Capsicum annuum",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 50,
        extract_method: "direct",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 3.0,
        ec_fertigation: 2.2,
        root_zone_targets: {
          "Cl": 6.0,
          "NH4": 0.5,
          "K": 5.0,
          "Ca": 8.5,
          "Mg": 3.0,
          "NO3": 17.0,
          "S": 3.0,
          "P": 1.2,
          "Fe": 25.0,
          "Mn": 5.0,
          "Zn": 7.0,
          "B": 80.0,
          "Cu": 0.7,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 1.0,
          "K": 6.75,
          "Ca": 5.0,
          "Mg": 1.5,
          "NO3": 16.0,
          "S": 1.75,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 15.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 30.0,
          "Cu": 1.0,
          "Mo": 0.5,
        },
        na_max_root_zone: 6.0,
        cl_max_root_zone: 6.0,
        growth_stages: {
          "start": {
            "NH4": -0.5,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.25,
            "Fe": 10.0,
            "B": 10.0,
          },
          "end_season": {
            "NH4": -1.0,
            "P": -1.0,
          },
          "fruit_set": {
            "K": 1.0,
            "NO3": 1.0,
          },
        },
        high_water_adjustment: {
          "K": -1.0,
          "Ca": 0.5,
        },
      },
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 51,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.8, 5.8],
        ph_fertigation: 5.3,
        ec_root_zone: 1.4,
        ec_fertigation: 2.1,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.1,
          "K": 3.0,
          "Ca": 3.0,
          "Mg": 1.5,
          "NO3": 8.0,
          "S": 1.5,
          "P": 0.7,
          "Fe": 10.0,
          "Mn": 3.0,
          "Zn": 4.0,
          "B": 25.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 1.05,
          "K": 6.2,
          "Ca": 5.25,
          "Mg": 1.5,
          "NO3": 16.0,
          "S": 1.75,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 30.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 30.0,
          "Cu": 1.0,
          "Mo": 0.5,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
          "start": {
            "NH4": -0.5,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.25,
            "Fe": 10.0,
            "B": 10.0,
          },
          "end_season": {
            "NH4": -1.0,
            "P": -1.0,
          },
          "fruit_set": {
            "K": 1.0,
            "NO3": 1.0,
          },
        },
        high_water_adjustment: {
          "K": -1.0,
          "Ca": 0.5,
        },
      },
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 52,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.1,
        ec_fertigation: 1.1,
        root_zone_targets: {
          "Cl": 3.0,
          "NH4": 0.1,
          "K": 2.0,
          "Ca": 2.5,
          "Mg": 1.2,
          "NO3": 4.5,
          "S": 2.0,
          "P": 0.1,
          "Fe": 8.0,
          "Mn": 1.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.9,
          "K": 4.0,
          "Ca": 2.0,
          "Mg": 1.0,
          "NO3": 8.4,
          "S": 1.0,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 2.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.3,
          "Mo": 0.0,
        },
        na_max_root_zone: 3.0,
        cl_max_root_zone: 3.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "tomato": {
    crop_id: "tomato",
    name_en: "Tomato",
    name_zh: "\u756a\u8304",
    category: "fruiting_vegetables",
    botanical: "Solanum lycopersicum",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 53,
        extract_method: "direct",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 4.0,
        ec_fertigation: 2.6,
        root_zone_targets: {
          "Cl": 8.0,
          "NH4": 0.5,
          "K": 8.0,
          "Ca": 10.0,
          "Mg": 4.5,
          "NO3": 22.0,
          "S": 6.8,
          "P": 1.0,
          "Fe": 35.0,
          "Mn": 5.0,
          "Zn": 7.0,
          "B": 50.0,
          "Cu": 0.7,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 1.2,
          "K": 9.5,
          "Ca": 5.4,
          "Mg": 2.4,
          "NO3": 15.0,
          "Cl": 1.0,
          "S": 4.4,
          "P": 1.5,
        },
        micro_fertigation: {
          "Fe": 15.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 30.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 8.0,
        cl_max_root_zone: 8.0,
        growth_stages: {
          "start": {
            "NH4": -1.0,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.5,
            "Fe": 10.0,
            "B": 10.0,
          },
          "end_season": {
            "NH4": -1.0,
            "P": -1.0,
          },
          "fruit_set": {
            "K": 1.5,
            "Ca": -0.5,
            "Mg": -0.25,
          },
        },
        high_water_adjustment: {
          "K": -1.0,
          "Ca": 0.5,
        },
      },
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 54,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.8, 5.8],
        ph_fertigation: 5.3,
        ec_root_zone: 1.5,
        ec_fertigation: 2.6,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.1,
          "K": 2.8,
          "Ca": 3.8,
          "Mg": 1.8,
          "NO3": 8.25,
          "S": 2.5,
          "P": 0.5,
          "Fe": 15.0,
          "Mn": 2.0,
          "Zn": 5.0,
          "B": 25.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 1.0,
          "K": 9.3,
          "Ca": 5.5,
          "Mg": 2.4,
          "NO3": 14.8,
          "Cl": 1.0,
          "S": 4.4,
          "P": 1.5,
        },
        micro_fertigation: {
          "Fe": 30.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 30.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
          "start": {
            "NH4": -1.0,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.5,
            "Fe": 10.0,
            "B": 10.0,
          },
          "end_season": {
            "NH4": -1.0,
            "P": -1.0,
          },
          "fruit_set": {
            "K": 1.5,
            "Ca": -0.5,
            "Mg": -0.25,
          },
        },
        high_water_adjustment: {
          "K": -1.0,
          "Ca": 0.5,
        },
      },
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 55,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.4,
        ec_fertigation: 1.3,
        root_zone_targets: {
          "Cl": 8.0,
          "NH4": 0.1,
          "K": 2.2,
          "Ca": 2.5,
          "Mg": 1.7,
          "NO3": 5.0,
          "S": 2.5,
          "P": 0.1,
          "Fe": 8.0,
          "Mn": 1.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.9,
          "K": 5.0,
          "Ca": 2.0,
          "Mg": 1.5,
          "NO3": 9.4,
          "S": 1.5,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 2.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.3,
          "Mo": 0.0,
        },
        na_max_root_zone: 8.0,
        cl_max_root_zone: 8.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "blueberry": {
    crop_id: "blueberry",
    name_en: "Blueberry",
    name_zh: "\u84dd\u8393",
    category: "soft_fruits",
    botanical: "",
    matrices: {
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 57,
        extract_method: "1:1.5_volume",
        ph_root_zone: [4.8, 4.8],
        ph_fertigation: 5.3,
        ec_root_zone: 0.7,
        ec_fertigation: 1.3,
        root_zone_targets: {
          "Cl": 4.0,
          "NH4": 0.1,
          "K": 1.1,
          "Ca": 1.4,
          "Mg": 0.8,
          "NO3": 3.0,
          "S": 1.1,
          "P": 0.3,
          "Fe": 7.0,
          "Mn": 0.8,
          "Zn": 1.0,
          "B": 7.0,
          "Cu": 0.7,
          "Mo": 0.1,
        },
        fertigation: {
          "NH4": 1.0,
          "K": 2.6,
          "Ca": 3.0,
          "Mg": 1.1,
          "NO3": 8.5,
          "S": 1.0,
          "P": 1.1,
        },
        micro_fertigation: {
          "Fe": 18.0,
          "Mn": 7.5,
          "Zn": 4.0,
          "B": 20.0,
          "Cu": 1.0,
          "Mo": 0.5,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 4.0,
        growth_stages: {
          "fruit_set": {
            "K": 1.4,
            "Ca": -0.8,
            "Mg": 0.1,
            "S": 0.1,
            "P": -0.2,
          },
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "raspberry": {
    crop_id: "raspberry",
    name_en: "Raspberry",
    name_zh: "\u8986\u76c6\u5b50",
    category: "soft_fruits",
    botanical: "",
    matrices: {
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 58,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 5.5],
        ph_fertigation: 5.3,
        ec_root_zone: 1.0,
        ec_fertigation: 2.0,
        root_zone_targets: {
          "Cl": 4.0,
          "K": 2.25,
          "Ca": 2.25,
          "Mg": 1.0,
          "NO3": 5.0,
          "S": 1.5,
          "P": 0.4,
          "Fe": 10.0,
          "Mn": 2.0,
          "Zn": 5.0,
          "B": 10.0,
          "Cu": 0.5,
          "Mo": 0.1,
        },
        fertigation: {
          "NH4": 0.9,
          "K": 5.35,
          "Ca": 4.5,
          "Mg": 1.75,
          "NO3": 13.5,
          "S": 2.0,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 20.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 10.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 4.0,
        cl_max_root_zone: 4.0,
        growth_stages: {
          "fruit_set": {
            "K": 0.5,
            "Ca": -0.5,
            "NO3": -0.5,
          },
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "strawberry": {
    crop_id: "strawberry",
    name_en: "Strawberry",
    name_zh: "\u8349\u8393",
    category: "soft_fruits",
    botanical: "Fragaria x ananassa",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 59,
        extract_method: "direct",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 2.0,
        ec_fertigation: 1.6,
        root_zone_targets: {
          "Cl": 4.0,
          "NH4": 0.5,
          "K": 5.0,
          "Ca": 4.5,
          "Mg": 2.0,
          "NO3": 12.0,
          "S": 2.5,
          "P": 0.7,
          "Fe": 35.0,
          "Mn": 7.0,
          "Zn": 7.0,
          "B": 20.0,
          "Cu": 0.7,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 1.0,
          "K": 4.8,
          "Ca": 3.6,
          "Mg": 1.5,
          "NO3": 12.0,
          "S": 1.5,
          "P": 1.0,
        },
        micro_fertigation: {
          "Fe": 30.0,
          "Mn": 10.0,
          "Zn": 7.0,
          "B": 10.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 4.0,
        cl_max_root_zone: 4.0,
        growth_stages: {
          "fruit_set": {
            "NH4": -0.5,
            "K": 2.0,
            "NO3": 1.5,
          },
          "start": {
            "Ca": 1.0,
            "NO3": 1.75,
            "P": 0.25,
            "Fe": 10.0,
            "Mn": 5.0,
            "B": 10.0,
          },
        },
        high_water_adjustment: {
        },
      },
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 60,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.0,
        ec_fertigation: 1.6,
        root_zone_targets: {
          "Cl": 1.5,
          "NH4": 0.1,
          "K": 1.7,
          "Ca": 1.7,
          "Mg": 0.7,
          "NO3": 3.8,
          "S": 1.25,
          "P": 0.3,
          "Fe": 8.0,
          "Mn": 2.0,
          "Zn": 6.0,
          "B": 4.0,
          "Cu": 0.7,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.75,
          "K": 4.5,
          "Ca": 3.75,
          "Mg": 1.5,
          "NO3": 11.75,
          "S": 1.5,
          "P": 1.0,
        },
        micro_fertigation: {
          "Fe": 30.0,
          "Mn": 10.0,
          "Zn": 7.0,
          "B": 10.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 1.5,
        cl_max_root_zone: 1.5,
        growth_stages: {
          "fruit_set": {
            "NH4": -0.5,
            "K": 2.0,
            "NO3": 1.5,
          },
          "start": {
            "Ca": 1.0,
            "NO3": 1.75,
            "P": 0.25,
            "Fe": 10.0,
            "Mn": 5.0,
            "B": 10.0,
          },
        },
        high_water_adjustment: {
        },
      },
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 61,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.7,
        ec_root_zone: 0.8,
        ec_fertigation: 1.0,
        root_zone_targets: {
          "Cl": 1.5,
          "NH4": 0.1,
          "K": 1.0,
          "Ca": 1.5,
          "Mg": 1.0,
          "NO3": 2.0,
          "S": 1.5,
          "P": 0.1,
          "Fe": 8.0,
          "Mn": 1.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.8,
          "K": 3.0,
          "Ca": 2.0,
          "Mg": 1.0,
          "NO3": 7.3,
          "S": 1.0,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 2.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.3,
          "Mo": 0.0,
        },
        na_max_root_zone: 1.5,
        cl_max_root_zone: 1.5,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "herbs": {
    crop_id: "herbs",
    name_en: "Herbs",
    name_zh: "\u9999\u8349\u7c7b",
    category: "leafy_vegetables",
    botanical: "",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 64,
        extract_method: "direct",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 3.0,
        ec_fertigation: 2.4,
        root_zone_targets: {
          "Cl": 4.0,
          "NH4": 0.5,
          "K": 7.0,
          "Ca": 7.0,
          "Mg": 2.5,
          "NO3": 20.0,
          "S": 3.5,
          "P": 0.8,
          "Fe": 25.0,
          "Mn": 5.0,
          "Zn": 7.0,
          "B": 50.0,
          "Cu": 1.0,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 1.25,
          "K": 6.75,
          "Ca": 4.5,
          "Mg": 3.0,
          "NO3": 16.75,
          "S": 2.5,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 25.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 35.0,
          "Cu": 1.0,
          "Mo": 0.5,
        },
        na_max_root_zone: 4.0,
        cl_max_root_zone: 4.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 65,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 0.8,
        ec_fertigation: 1.7,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.1,
          "K": 1.6,
          "Ca": 1.2,
          "Mg": 0.5,
          "NO3": 4.0,
          "S": 0.8,
          "P": 0.5,
          "Fe": 10.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 10.0,
          "Cu": 0.7,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 1.2,
          "K": 6.1,
          "Ca": 3.3,
          "Mg": 0.85,
          "NO3": 12.1,
          "S": 1.2,
          "P": 1.1,
        },
        micro_fertigation: {
          "Fe": 20.0,
          "Mn": 5.0,
          "Zn": 3.0,
          "B": 10.0,
          "Cu": 0.5,
          "Mo": 0.5,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "lettuce": {
    crop_id: "lettuce",
    name_en: "Lettuce",
    name_zh: "\u751f\u83dc",
    category: "leafy_vegetables",
    botanical: "Lactuca sativa",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 66,
        extract_method: "direct",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 2.5,
        ec_fertigation: 2.2,
        root_zone_targets: {
          "Cl": 6.0,
          "NH4": 0.5,
          "K": 6.0,
          "Ca": 6.0,
          "Mg": 2.0,
          "NO3": 14.0,
          "S": 2.0,
          "P": 2.0,
          "Fe": 40.0,
          "Mn": 8.0,
          "Zn": 8.0,
          "B": 50.0,
          "Cu": 1.5,
          "Mo": 1.5,
        },
        fertigation: {
          "NH4": 1.0,
          "K": 9.5,
          "Ca": 4.5,
          "Mg": 1.0,
          "NO3": 16.0,
          "S": 2.0,
          "P": 1.5,
        },
        micro_fertigation: {
          "Fe": 40.0,
          "Mn": 7.0,
          "Zn": 7.0,
          "B": 40.0,
          "Cu": 1.0,
          "Mo": 1.0,
        },
        na_max_root_zone: 6.0,
        cl_max_root_zone: 6.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 67,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 6.0,
        ec_root_zone: 1.0,
        ec_fertigation: 1.2,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.1,
          "K": 2.5,
          "Ca": 3.25,
          "Mg": 1.0,
          "NO3": 4.0,
          "S": 3.5,
          "P": 0.1,
          "Fe": 5.0,
          "Mn": 0.5,
          "Zn": 0.5,
          "B": 10.0,
          "Cu": 0.3,
          "Mo": 0.2,
        },
        fertigation: {
          "NH4": 0.1,
          "K": 3.0,
          "Ca": 3.25,
          "Mg": 1.0,
          "NO3": 5.0,
          "Cl": 2.0,
          "S": 3.5,
          "P": 0.1,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 0.5,
          "Zn": 0.5,
          "B": 10.0,
          "Cu": 0.3,
          "Mo": 0.2,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "microgreens": {
    crop_id: "microgreens",
    name_en: "Microgreens",
    name_zh: "\u82bd\u82d7\u83dc",
    category: "leafy_vegetables",
    botanical: "",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 68,
        extract_method: "direct",
        ph_root_zone: [5.5, 5.5],
        ph_fertigation: 5.3,
        ec_root_zone: 2.5,
        ec_fertigation: 2.0,
        root_zone_targets: {
          "Cl": 4.0,
          "NH4": 0.5,
          "K": 6.0,
          "Mg": 3.0,
          "NO3": 18.0,
          "S": 3.0,
          "P": 1.0,
          "Fe": 25.0,
          "Mn": 5.0,
          "Zn": 7.0,
          "B": 50.0,
          "Cu": 1.0,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 0.85,
          "K": 5.4,
          "Ca": 4.25,
          "Mg": 2.75,
          "NO3": 14.5,
          "S": 2.25,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 35.0,
          "Mn": 10.0,
          "Zn": 5.0,
          "B": 35.0,
          "Cu": 1.0,
          "Mo": 1.0,
        },
        na_max_root_zone: 4.0,
        cl_max_root_zone: 4.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "alstroemeria": {
    crop_id: "alstroemeria",
    name_en: "Alstroemeria",
    name_zh: "\u516d\u51fa\u82b1",
    category: "cut_flowers",
    botanical: "",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 70,
        extract_method: "direct",
        ph_root_zone: [5.5, 5.5],
        ph_fertigation: 5.3,
        ec_root_zone: 2.8,
        ec_fertigation: 3.0,
        root_zone_targets: {
          "Cl": 2.5,
          "NH4": 0.5,
          "K": 8.0,
          "Ca": 10.0,
          "Mg": 3.0,
          "NO3": 20.0,
          "S": 6.5,
          "P": 1.0,
          "Fe": 30.0,
          "Mn": 3.0,
          "Zn": 2.0,
          "B": 20.0,
          "Cu": 1.0,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 1.5,
          "K": 10.0,
          "Ca": 7.5,
          "Mg": 2.0,
          "NO3": 20.75,
          "S": 4.0,
          "P": 1.75,
        },
        micro_fertigation: {
          "Fe": 50.0,
          "Mn": 7.0,
          "Zn": 3.0,
          "B": 30.0,
          "Cu": 1.0,
          "Mo": 0.7,
        },
        na_max_root_zone: 2.5,
        cl_max_root_zone: 2.5,
        growth_stages: {
          "start": {
            "NH4": -0.5,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.25,
            "Fe": 10.03,
            "B": 9.99,
          },
        },
        high_water_adjustment: {
        },
      },
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 71,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.0,
        ec_fertigation: 3.0,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.1,
          "K": 3.0,
          "Ca": 2.5,
          "Mg": 1.0,
          "NO3": 7.0,
          "S": 1.0,
          "P": 1.0,
          "Fe": 15.0,
          "Mn": 3.0,
          "Zn": 1.0,
          "B": 30.0,
          "Cu": 0.3,
          "Mo": 0.2,
        },
        fertigation: {
          "NH4": 1.5,
          "K": 10.0,
          "Ca": 7.5,
          "Mg": 2.0,
          "NO3": 20.75,
          "S": 4.0,
          "P": 1.75,
        },
        micro_fertigation: {
          "Fe": 50.0,
          "Mn": 7.0,
          "Zn": 3.0,
          "B": 30.0,
          "Cu": 1.0,
          "Mo": 0.7,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
          "start": {
            "NH4": -0.5,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.25,
            "Fe": 10.03,
            "B": 9.99,
          },
        },
        high_water_adjustment: {
        },
      },
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 72,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.0,
        ec_fertigation: 1.0,
        root_zone_targets: {
          "Cl": 3.0,
          "NH4": 0.1,
          "K": 1.5,
          "Ca": 2.0,
          "Mg": 1.2,
          "NO3": 4.0,
          "S": 1.5,
          "P": 0.1,
          "Fe": 8.0,
          "Mn": 1.0,
          "Zn": 1.0,
          "B": 20.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.9,
          "K": 4.0,
          "Ca": 2.0,
          "Mg": 1.0,
          "NO3": 8.0,
          "S": 1.2,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 2.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.3,
        },
        na_max_root_zone: 3.0,
        cl_max_root_zone: 3.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "anthurium": {
    crop_id: "anthurium",
    name_en: "Anthurium",
    name_zh: "\u7ea2\u638c",
    category: "potted_plants",
    botanical: "Anthurium scherzerianum",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 73,
        extract_method: "direct",
        ph_root_zone: [5.2, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.0,
        ec_fertigation: 0.9,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.5,
          "K": 3.0,
          "Ca": 2.0,
          "Mg": 1.2,
          "NO3": 5.0,
          "S": 1.5,
          "P": 0.75,
          "Fe": 15.0,
          "Mn": 2.0,
          "Zn": 4.0,
          "B": 40.0,
          "Cu": 1.0,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 0.3,
          "K": 3.9,
          "Ca": 1.3,
          "Mg": 1.0,
          "NO3": 6.4,
          "S": 0.8,
          "P": 0.8,
        },
        micro_fertigation: {
          "Fe": 15.0,
          "Mn": 0.0,
          "Zn": 3.0,
          "B": 30.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
          "start": {
            "NH4": -0.29,
            "K": 0.56,
            "Ca": -0.5,
            "NO3": -0.79,
            "Fe": 5.01,
            "B": 54.0,
          },
        },
        high_water_adjustment: {
        },
      },
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 74,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.2, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.0,
        ec_fertigation: 0.8,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.5,
          "K": 3.0,
          "Ca": 2.0,
          "Mg": 1.2,
          "NO3": 5.0,
          "S": 1.5,
          "P": 0.75,
          "Fe": 15.0,
          "Mn": 2.0,
          "Zn": 4.0,
          "B": 40.0,
          "Cu": 1.0,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 0.8,
          "K": 3.0,
          "Ca": 1.0,
          "Mg": 0.7,
          "NO3": 4.5,
          "S": 1.0,
          "P": 0.7,
        },
        micro_fertigation: {
          "Fe": 15.0,
          "Mn": 0.0,
          "Zn": 3.0,
          "B": 20.0,
          "Cu": 0.5,
          "Mo": 0.5,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "carnation": {
    crop_id: "carnation",
    name_en: "Carnation",
    name_zh: "\u5eb7\u4e43\u99a8",
    category: "cut_flowers",
    botanical: "Dianthus caryophyllus",
    matrices: {
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 76,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.3,
        ec_fertigation: 1.8,
        root_zone_targets: {
          "Cl": 1.7,
          "NH4": 0.1,
          "K": 3.0,
          "Ca": 3.0,
          "Mg": 1.5,
          "NO3": 6.0,
          "S": 2.0,
          "P": 0.8,
          "Fe": 15.0,
          "Mn": 1.0,
          "Zn": 2.0,
          "B": 25.0,
          "Cu": 1.0,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 1.0,
          "K": 6.25,
          "Ca": 3.75,
          "Mg": 1.0,
          "NO3": 13.0,
          "S": 1.25,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 25.0,
          "Mn": 10.0,
          "Zn": 4.0,
          "B": 30.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 1.7,
        cl_max_root_zone: 1.7,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 77,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 2.2,
        ec_fertigation: 1.2,
        root_zone_targets: {
          "Cl": 3.0,
          "NH4": 0.1,
          "K": 1.5,
          "Ca": 2.5,
          "Mg": 1.2,
          "NO3": 4.0,
          "S": 1.5,
          "P": 0.1,
          "Fe": 8.0,
          "Mn": 1.0,
          "Zn": 1.0,
          "B": 15.0,
          "Cu": 0.5,
          "Mo": 43.0,
        },
        fertigation: {
          "NH4": 0.9,
          "K": 4.0,
          "Ca": 2.0,
          "Mg": 1.0,
          "NO3": 8.4,
          "S": 1.0,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 10.0,
          "Cu": 0.3,
        },
        na_max_root_zone: 3.0,
        cl_max_root_zone: 3.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "chrysanthemum": {
    crop_id: "chrysanthemum",
    name_en: "Chrysanthemum",
    name_zh: "\u83ca\u82b1",
    category: "cut_flowers",
    botanical: "",
    matrices: {
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 78,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 0.8,
        ec_fertigation: 1.2,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.1,
          "K": 1.0,
          "Ca": 1.5,
          "Mg": 0.8,
          "NO3": 2.0,
          "S": 1.5,
          "P": 0.1,
          "Fe": 8.0,
          "Mn": 1.0,
          "Zn": 1.0,
          "B": 15.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.4,
          "K": 4.0,
          "Ca": 2.0,
          "Mg": 1.0,
          "NO3": 7.9,
          "S": 1.0,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 2.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.3,
          "Mo": 0.0,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
          "start": {
            "NH4": -0.43,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.21,
            "Fe": 10.03,
            "B": 9.99,
          },
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "gerbera": {
    crop_id: "gerbera",
    name_en: "Gerbera",
    name_zh: "\u975e\u6d32\u83ca",
    category: "cut_flowers",
    botanical: "Gerbera jamesonii",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 79,
        extract_method: "direct",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 2.0,
        ec_fertigation: 1.6,
        root_zone_targets: {
          "Cl": 6.0,
          "NH4": 0.5,
          "K": 6.0,
          "Ca": 5.0,
          "Mg": 2.0,
          "NO3": 13.0,
          "S": 2.5,
          "P": 1.0,
          "Fe": 40.0,
          "Mn": 3.0,
          "Zn": 5.0,
          "B": 40.0,
          "Cu": 1.0,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 1.5,
          "K": 5.5,
          "Ca": 3.0,
          "Mg": 1.0,
          "NO3": 10.25,
          "Cl": 1.0,
          "S": 1.25,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 35.0,
          "Mn": 5.0,
          "Zn": 4.0,
          "B": 30.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 6.0,
        cl_max_root_zone: 6.0,
        growth_stages: {
          "start": {
            "NH4": -0.5,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.25,
            "Fe": 10.0,
            "B": 10.0,
          },
          "flowering": {
            "K": 1.0,
            "NO3": 1.0,
          },
        },
        high_water_adjustment: {
        },
      },
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 80,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 0.8,
        ec_fertigation: 1.6,
        root_zone_targets: {
          "Cl": 1.5,
          "NH4": 0.1,
          "K": 2.2,
          "Ca": 2.0,
          "Mg": 0.8,
          "NO3": 5.0,
          "S": 1.0,
          "P": 0.75,
          "Fe": 15.0,
          "Mn": 1.0,
          "Zn": 2.0,
          "B": 20.0,
          "Cu": 1.0,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.75,
          "K": 5.0,
          "Ca": 3.25,
          "Mg": 1.25,
          "NO3": 10.0,
          "Cl": 0.5,
          "S": 1.5,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 35.0,
          "Mn": 5.0,
          "Zn": 4.0,
          "B": 30.0,
          "Cu": 0.75,
          "Mo": 0.5,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 1.5,
        growth_stages: {
          "start": {
            "NH4": -0.5,
            "K": -1.0,
            "Ca": 0.5,
            "Mg": 0.25,
            "Fe": 10.0,
            "B": 10.0,
          },
          "flowering": {
            "K": 1.0,
            "NO3": 1.0,
          },
        },
        high_water_adjustment: {
        },
      },
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 81,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.0,
        ec_fertigation: 1.2,
        root_zone_targets: {
          "Cl": 3.0,
          "NH4": 0.1,
          "K": 1.5,
          "Ca": 2.0,
          "Mg": 1.2,
          "NO3": 4.0,
          "S": 1.5,
          "P": 0.1,
          "Fe": 8.0,
          "Mn": 1.0,
          "Zn": 1.0,
          "B": 20.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.9,
          "K": 3.5,
          "Ca": 2.0,
          "Mg": 1.1,
          "NO3": 7.9,
          "S": 1.1,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 10.0,
          "Cu": 0.3,
          "Mo": 0.0,
        },
        na_max_root_zone: 3.0,
        cl_max_root_zone: 3.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "rose": {
    crop_id: "rose",
    name_en: "Rose",
    name_zh: "\u6708\u5b63",
    category: "cut_flowers",
    botanical: "",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 82,
        extract_method: "direct",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 2.2,
        ec_fertigation: 1.6,
        root_zone_targets: {
          "Cl": 6.0,
          "NH4": 0.5,
          "K": 4.8,
          "Ca": 4.8,
          "Mg": 2.5,
          "NO3": 12.7,
          "S": 2.6,
          "P": 1.1,
          "Fe": 40.0,
          "Mn": 4.0,
          "Zn": 5.0,
          "B": 20.0,
          "Cu": 1.5,
          "Mo": 0.8,
        },
        fertigation: {
          "NH4": 0.7,
          "K": 4.5,
          "Ca": 3.4,
          "Mg": 1.6,
          "NO3": 10.75,
          "S": 1.6,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 35.0,
          "Mn": 7.0,
          "Zn": 3.5,
          "B": 35.0,
          "Cu": 1.1,
          "Mo": 1.0,
        },
        na_max_root_zone: 6.0,
        cl_max_root_zone: 6.0,
        growth_stages: {
          "winter": {
            "NH4": -0.5,
            "NO3": -0.5,
          },
          "start": {
            "K": -1.0,
            "Ca": 0.5,
            "Fe": 10.0,
            "B": 10.0,
          },
          "flowering": {
            "K": 1.0,
            "NO3": 1.0,
          },
        },
        high_water_adjustment: {
          "K": -1.0,
          "Ca": 0.5,
        },
      },
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 83,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.0,
        ec_fertigation: 1.6,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.1,
          "K": 2.3,
          "Ca": 2.3,
          "Mg": 1.1,
          "NO3": 5.0,
          "S": 1.7,
          "P": 0.8,
          "Fe": 15.0,
          "Mn": 1.3,
          "Zn": 1.4,
          "B": 15.0,
          "Cu": 1.0,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 0.75,
          "K": 4.25,
          "Ca": 3.75,
          "Mg": 1.75,
          "NO3": 11.25,
          "S": 1.75,
          "P": 1.25,
        },
        micro_fertigation: {
          "Fe": 35.0,
          "Mn": 7.0,
          "Zn": 3.5,
          "B": 35.0,
          "Cu": 1.1,
          "Mo": 1.0,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
          "winter": {
            "NH4": -0.5,
            "NO3": -0.5,
          },
          "start": {
            "K": -1.0,
            "Ca": 0.5,
            "Fe": 10.0,
            "B": 10.0,
          },
          "flowering": {
            "K": 1.0,
            "NO3": 1.0,
          },
        },
        high_water_adjustment: {
          "K": -1.0,
          "Ca": 0.5,
        },
      },
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 84,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.0,
        ec_fertigation: 1.2,
        root_zone_targets: {
          "Cl": 3.0,
          "NH4": 0.1,
          "K": 1.5,
          "Ca": 2.0,
          "Mg": 1.2,
          "NO3": 4.0,
          "S": 1.5,
          "P": 0.1,
          "Fe": 8.0,
          "Mn": 1.0,
          "Zn": 1.0,
          "B": 20.0,
          "Cu": 0.5,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.9,
          "K": 3.5,
          "Ca": 2.0,
          "Mg": 1.1,
          "NO3": 7.9,
          "S": 1.1,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 10.0,
          "Cu": 0.3,
          "Mo": 0.0,
        },
        na_max_root_zone: 3.0,
        cl_max_root_zone: 3.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "zantedeschia": {
    crop_id: "zantedeschia",
    name_en: "Zantedeschia",
    name_zh: "\u9a6c\u8e44\u83b2",
    category: "cut_flowers",
    botanical: "",
    matrices: {
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 85,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 0.9,
        ec_fertigation: 0.7,
        root_zone_targets: {
          "Cl": 2.5,
          "NH4": 0.1,
          "K": 2.4,
          "Ca": 1.4,
          "Mg": 0.6,
          "NO3": 6.0,
          "S": 1.4,
          "P": 0.5,
          "Fe": 8.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 15.0,
          "Cu": 0.7,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.1,
          "K": 2.5,
          "Ca": 1.0,
          "Mg": 0.5,
          "NO3": 3.5,
          "Cl": 2.5,
          "S": 1.4,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 8.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 15.0,
          "Cu": 0.7,
          "Mo": 0.3,
        },
        na_max_root_zone: 2.5,
        cl_max_root_zone: 2.5,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
      "SOIL": {
        substrate_type: "SOIL",
        source_page: 87,
        extract_method: "1:2_volume",
        ph_root_zone: [6.0, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 0.9,
        ec_fertigation: 1.0,
        root_zone_targets: {
          "Cl": 3.0,
          "NH4": 0.1,
          "K": 1.8,
          "Ca": 1.8,
          "Mg": 1.0,
          "NO3": 3.0,
          "S": 1.5,
          "P": 0.1,
          "Fe": 5.0,
          "Mn": 1.0,
          "Zn": 1.0,
          "B": 10.0,
          "Cu": 0.5,
          "Mo": 0.1,
        },
        fertigation: {
          "NH4": 0.9,
          "K": 3.5,
          "Ca": 1.8,
          "Mg": 1.0,
          "NO3": 7.3,
          "S": 1.1,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 1.0,
          "Zn": 0.5,
          "B": 10.0,
          "Cu": 0.3,
          "Mo": 0.0,
        },
        na_max_root_zone: 3.0,
        cl_max_root_zone: 3.0,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "bedding_plants": {
    crop_id: "bedding_plants",
    name_en: "Bedding Plants",
    name_zh: "\u82b1\u575b\u690d\u7269",
    category: "potted_plants",
    botanical: "",
    matrices: {
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 89,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 0.6,
        ec_fertigation: 0.6,
        root_zone_targets: {
          "Cl": 2.5,
          "NH4": 0.1,
          "K": 1.2,
          "Ca": 1.0,
          "Mg": 0.3,
          "NO3": 2.5,
          "S": 0.6,
          "P": 0.5,
          "Fe": 8.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 15.0,
          "Cu": 0.7,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.1,
          "K": 1.3,
          "Ca": 0.9,
          "Mg": 0.5,
          "NO3": 2.0,
          "Cl": 4.0,
          "S": 1.0,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 8.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 15.0,
          "Cu": 0.7,
          "Mo": 0.3,
        },
        na_max_root_zone: 2.5,
        cl_max_root_zone: 2.5,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "poinsettia": {
    crop_id: "poinsettia",
    name_en: "Poinsettia",
    name_zh: "\u4e00\u54c1\u7ea2",
    category: "potted_plants",
    botanical: "Euphorbia pulcherrima",
    matrices: {
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 90,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 0.7,
        ec_fertigation: 1.8,
        root_zone_targets: {
          "Cl": 2.5,
          "NH4": 0.1,
          "K": 1.6,
          "Ca": 1.4,
          "Mg": 0.6,
          "NO3": 4.0,
          "S": 0.8,
          "P": 0.5,
          "Fe": 8.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 15.0,
          "Cu": 0.7,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 1.75,
          "K": 3.5,
          "Ca": 3.75,
          "Mg": 1.0,
          "NO3": 11.75,
          "S": 1.0,
          "P": 1.0,
        },
        micro_fertigation: {
          "Fe": 15.0,
          "Mn": 5.0,
          "Zn": 3.0,
          "B": 10.0,
          "Cu": 0.5,
          "Mo": 0.5,
        },
        na_max_root_zone: 2.5,
        cl_max_root_zone: 2.5,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "flowering_plants": {
    crop_id: "flowering_plants",
    name_en: "Flowering Plants",
    name_zh: "\u89c2\u82b1\u76c6\u683d",
    category: "potted_plants",
    botanical: "",
    matrices: {
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 91,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 1.0,
        ec_fertigation: 0.8,
        root_zone_targets: {
          "Cl": 3.5,
          "NH4": 0.1,
          "K": 2.4,
          "Ca": 1.4,
          "Mg": 0.6,
          "NO3": 6.0,
          "S": 1.0,
          "P": 0.5,
          "Fe": 10.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 10.0,
          "Cu": 0.7,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.1,
          "K": 2.5,
          "Ca": 1.0,
          "Mg": 0.5,
          "NO3": 3.5,
          "Cl": 3.5,
          "S": 1.4,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 8.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 15.0,
          "Cu": 0.7,
          "Mo": 0.3,
        },
        na_max_root_zone: 3.5,
        cl_max_root_zone: 3.5,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "foliage_plants": {
    crop_id: "foliage_plants",
    name_en: "Foliage Plants",
    name_zh: "\u89c2\u53f6\u76c6\u683d",
    category: "potted_plants",
    botanical: "",
    matrices: {
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 92,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 0.0,
        ec_fertigation: 1.2,
        root_zone_targets: {
        },
        fertigation: {
          "NH4": 0.1,
          "K": 4.0,
          "Ca": 2.0,
          "Mg": 0.7,
          "NO3": 7.5,
          "Cl": 2.5,
          "S": 1.5,
          "P": 0.5,
        },
        micro_fertigation: {
          "Fe": 10.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 10.0,
          "Cu": 0.7,
          "Mo": 0.3,
        },
        na_max_root_zone: null,
        cl_max_root_zone: null,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "phalaenopsis": {
    crop_id: "phalaenopsis",
    name_en: "Phalaenopsis",
    name_zh: "\u8774\u8776\u5170",
    category: "potted_plants",
    botanical: "",
    matrices: {
      "INERT_SUBSTRATE": {
        substrate_type: "INERT_SUBSTRATE",
        source_page: 93,
        extract_method: "direct",
        ph_root_zone: [5.1, 5.1],
        ph_fertigation: 5.5,
        ec_root_zone: 1.2,
        ec_fertigation: 1.1,
        root_zone_targets: {
          "NH4": 0.5,
          "K": 3.6,
          "Ca": 2.5,
          "Mg": 1.5,
          "NO3": 7.7,
          "S": 1.7,
          "P": 1.0,
          "Fe": 5.0,
          "Mn": 15.0,
          "Zn": 4.0,
          "B": 15.0,
          "Cu": 0.5,
          "Mo": 0.5,
        },
        fertigation: {
          "NH4": 0.4,
          "K": 4.6,
          "Ca": 1.7,
          "Mg": 1.2,
          "NO3": 6.0,
          "S": 1.9,
          "P": 1.0,
        },
        micro_fertigation: {
          "Fe": 5.0,
          "Mn": 15.0,
          "Zn": 4.0,
          "B": 15.0,
          "Cu": 0.5,
          "Mo": 0.5,
        },
        na_max_root_zone: null,
        cl_max_root_zone: null,
        growth_stages: {
        },
        high_water_adjustment: {
        },
      },
    },
  },
  "orchids_other": {
    crop_id: "orchids_other",
    name_en: "Orchids (other)",
    name_zh: "\u5176\u4ed6\u5170\u82b1",
    category: "potted_plants",
    botanical: "",
    matrices: {
      "ORGANIC_MATERIAL": {
        substrate_type: "ORGANIC_MATERIAL",
        source_page: 94,
        extract_method: "1:1.5_volume",
        ph_root_zone: [5.5, 6.0],
        ph_fertigation: 5.3,
        ec_root_zone: 0.7,
        ec_fertigation: 1.1,
        root_zone_targets: {
          "Cl": 2.0,
          "NH4": 0.1,
          "K": 1.2,
          "Ca": 1.0,
          "Mg": 0.3,
          "NO3": 2.5,
          "S": 0.6,
          "P": 0.5,
          "Fe": 8.0,
          "Mn": 2.0,
          "Zn": 2.0,
          "B": 15.0,
          "Cu": 0.7,
          "Mo": 0.3,
        },
        fertigation: {
          "NH4": 0.8,
          "K": 3.7,
          "Ca": 2.0,
          "Mg": 0.5,
          "NO3": 7.1,
          "S": 0.7,
          "P": 1.0,
        },
        micro_fertigation: {
          "Fe": 15.0,
          "Mn": 5.0,
          "Zn": 3.0,
          "B": 10.0,
          "Cu": 0.5,
          "Mo": 0.5,
        },
        na_max_root_zone: 2.0,
        cl_max_root_zone: 2.0,
        growth_stages: {
          "flowering": {
            "NH4": -0.2,
            "K": 0.7,
            "Ca": -0.3,
            "Mg": 0.2,
            "NO3": -1.0,
            "S": 0.35,
          },
        },
        high_water_adjustment: {
        },
      },
    },
  },
};


// ---------------------------------------------------------------------------
// Convenience resolvers
// ---------------------------------------------------------------------------

/**
 * Build StageAdjustment records for a matrix (in the canonical GROWTH_STAGE
 * order). Mirrors the Python `_build_recipe` from constants.py.
 */
export function buildStageAdjustments(
  matrix: WURCropMatrix,
): Array<{
  stage: string;
  label_en: string;
  label_zh: string;
  deltas: Record<string, number>;
  note_en: string;
  note_zh: string;
}> {
  const order = Object.keys(GROWTH_STAGE_LABELS);
  const stages = Object.entries(matrix.growth_stages).map(([stage, deltas]) => {
    const label = GROWTH_STAGE_LABELS[stage] ?? [stage, stage];
    let noteEn = "";
    let noteZh = "";
    if (stage === "fruit_set") {
      noteEn = FRUIT_SET_NOTE_EN;
      noteZh = FRUIT_SET_NOTE_ZH;
    } else if (stage === "end_season") {
      noteEn = END_SEASON_NOTE_EN;
      noteZh = END_SEASON_NOTE_ZH;
    }
    return {
      stage,
      label_en: label[0],
      label_zh: label[1],
      deltas: { ...deltas },
      note_en: noteEn,
      note_zh: noteZh,
    };
  });
  stages.sort(
    (a, b) => {
      const ai = order.indexOf(a.stage);
      const bi = order.indexOf(b.stage);
      return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
    },
  );
  return stages;
}

/**
 * Resolve one crop × substrate matrix. Returns null when the pairing has no
 * published table, so callers can raise a specific error rather than silently
 * substituting the wrong medium's targets.
 */
export function getCrop(
  cropId: string,
  substrateType: string = DEFAULT_SUBSTRATE,
): WURCropMatrix | null {
  const crop = WUR_CROPS[cropId];
  if (!crop) return null;
  return crop.matrices[substrateType as keyof typeof crop.matrices] ?? null;
}

/** All crop ids in the canonical library order. */
export function cropIds(): string[] {
  return Object.keys(WUR_CROPS);
}

/** Substrates published for the given crop. */
export function substratesFor(cropId: string): string[] {
  const crop = WUR_CROPS[cropId];
  if (!crop) return [];
  return SUBSTRATE_TYPES.filter(
    (s) => crop.matrices[s as keyof typeof crop.matrices] != null,
  );
}

/** Crop ids whose category matches. */
export function cropsInCategory(category: string): string[] {
  return Object.values(WUR_CROPS)
    .filter((c) => c.category === category)
    .map((c) => c.crop_id);
}

/** Crop meta (id / names / category / botanical). */
export function cropMeta(cropId: string): {
  crop_id: string;
  name_en: string;
  name_zh: string;
  category: string;
  botanical: string;
} | null {
  const c = WUR_CROPS[cropId];
  if (!c) return null;
  return {
    crop_id: c.crop_id,
    name_en: c.name_en,
    name_zh: c.name_zh,
    category: c.category,
    botanical: c.botanical,
  };
}

/** Stage ids with published adjustments. Never includes `high_water`. */
export function growthStagesFor(
  cropId: string,
  substrateType: string = DEFAULT_SUBSTRATE,
): string[] {
  const matrix = getCrop(cropId, substrateType);
  if (!matrix) return [];
  return Object.keys(matrix.growth_stages);
}

// Register the crop lookup with the fertiliser catalogue so it can fall back
// to category-level reference irrigation volumes without a circular import.
registerCropLookup((cropId) => {
  const meta = cropMeta(cropId);
  return meta ? { category: meta.category } : null;
});

