'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import {
  ClipboardCopy, FileText, FileSpreadsheet, Share2, Check,
} from 'lucide-react';
import type { ToolMeta } from './FreeToolsSection';

/**
 * Global CustomEvent name dispatched by FreeToolsSection's keyboard shortcut
 * listener (Ctrl+E / Cmd+E) to trigger this bar's Copy action programmatically.
 */
export const EXPORT_COPY_EVENT = 'nutri:export-copy';

export interface ToolExportBarProps {
  tool: ToolMeta;
}

const pad2 = (n: number) => n.toString().padStart(2, '0');

function nowStamp() {
  const d = new Date();
  return {
    display: d.toLocaleString(),
    file: `${d.getFullYear()}${pad2(d.getMonth() + 1)}${pad2(d.getDate())}-${pad2(d.getHours())}${pad2(d.getMinutes())}`,
  };
}

function buildSummary(tool: ToolMeta): string {
  return [
    `NutriPlant PRO — ${tool.name}`,
    `Category: ${tool.category}`,
    `Description: ${tool.description}`,
    `Benefit: ${tool.benefit}`,
    `How to use:`,
    ...tool.howToUse.map((s, i) => `${i + 1}. ${s}`),
    `Generated: ${nowStamp().display}`,
  ].join('\n');
}

function buildCsv(tool: ToolMeta): string {
  const rows: Array<[string, string]> = [
    ['Tool', tool.name],
    ['Category', tool.category],
    ['Description', tool.description],
    ['Benefit', tool.benefit],
    ...tool.howToUse.map((s, i) => [`How-to step ${i + 1}`, s] as [string, string]),
    ['Generated', nowStamp().display],
  ];
  const esc = (v: string) => `"${String(v).replace(/"/g, '""')}"`;
  return ['Field,Value', ...rows.map(([f, v]) => `${esc(f)},${esc(v)}`)].join('\r\n');
}

function downloadBlob(filename: string, content: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function exportPdf(tool: ToolMeta) {
  const ts = nowStamp().display;
  const w = window.open('', '_blank', 'width=900,height=1200');
  if (!w) return;
  const steps = tool.howToUse.map(s => `<li>${s}</li>`).join('');
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${tool.name} — Report</title>
<style>
body{font:14px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;color:#111;padding:32px;max-width:780px;margin:auto}
h1{font-size:22px;color:#15803d;margin:0 0 6px}
.cat{display:inline-block;background:#dcfce7;color:#166534;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600;margin-bottom:12px}
.label{font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:#666;margin:14px 0 4px}
ol{margin:0;padding-left:20px}
.foot{margin-top:24px;font-size:11px;color:#888;border-top:1px solid #eee;padding-top:8px}
</style></head><body>
<h1>${tool.name}</h1><span class="cat">${tool.category}</span>
<div class="label">Description</div><p>${tool.description}</p>
<div class="label">Benefit</div><p>${tool.benefit}</p>
<div class="label">How to use</div><ol>${steps}</ol>
<div class="foot">Generated by NutriPlant PRO · ${ts}</div>
<script>window.onload=function(){setTimeout(function(){window.print()},300)}<\/script>
</body></html>`);
  w.document.close();
}

export function ToolExportBar({ tool }: ToolExportBarProps) {
  const [copied, setCopied] = useState<'copy' | 'share' | null>(null);
  const flash = (k: 'copy' | 'share') => {
    setCopied(k);
    setTimeout(() => setCopied(prev => (prev === k ? null : prev)), 2000);
  };

  const onCopy = async () => {
    try { await navigator.clipboard.writeText(buildSummary(tool)); flash('copy'); } catch { /* clipboard blocked */ }
  };
  const onCsv = () => {
    downloadBlob(`nutriplant-${tool.id}-${nowStamp().file}.csv`, buildCsv(tool), 'text/csv;charset=utf-8');
  };
  const onPdf = () => exportPdf(tool);
  const onShare = async () => {
    const url = `${window.location.origin}${window.location.pathname}#tool=${tool.id}`;
    try { await navigator.clipboard.writeText(url); flash('share'); } catch { /* clipboard blocked */ }
  };

  // Listen for the global "trigger copy" CustomEvent dispatched by FreeToolsSection's
  // Ctrl+E / Cmd+E keyboard shortcut. Re-subscribes whenever `tool` changes so the
  // handler closure always references the latest tool summary.
  useEffect(() => {
    const handler = () => { void onCopy(); };
    window.addEventListener(EXPORT_COPY_EVENT, handler);
    return () => window.removeEventListener(EXPORT_COPY_EVENT, handler);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tool]);

  return (
    <div className="sticky top-0 z-10 -mx-1 mb-2 flex flex-wrap items-center gap-1.5 rounded-lg border border-border bg-background/95 backdrop-blur p-2 shadow-sm">
      <Button size="sm" variant="outline" onClick={onCopy} className="h-8 gap-1.5 text-xs">
        {copied === 'copy' ? <Check className="h-3.5 w-3.5 text-emerald-600" /> : <ClipboardCopy className="h-3.5 w-3.5" />}
        {copied === 'copy' ? 'Copied!' : 'Copy'}
      </Button>
      <Button size="sm" variant="outline" onClick={onCsv} className="h-8 gap-1.5 text-xs">
        <FileSpreadsheet className="h-3.5 w-3.5" /> CSV
      </Button>
      <Button size="sm" variant="outline" onClick={onPdf} className="h-8 gap-1.5 text-xs">
        <FileText className="h-3.5 w-3.5" /> PDF
      </Button>
      <Button size="sm" variant="outline" onClick={onShare} className="h-8 gap-1.5 text-xs">
        {copied === 'share' ? <Check className="h-3.5 w-3.5 text-emerald-600" /> : <Share2 className="h-3.5 w-3.5" />}
        {copied === 'share' ? 'Copied!' : 'Share'}
      </Button>
    </div>
  );
}
