#!/usr/bin/env python3
"""Add 68 new formulas across 9 new parts."""
import json
from pathlib import Path

DATA_PATH = Path('/home/z/my-project/src/data/agri_formulas.json')

NEW_PARTS = [
    # ========================================================================
    # 1. AGRICULTURAL METEOROLOGY (10)
    # ========================================================================
    {
        "roman": "XXXII", "title": "Agricultural Meteorology",
        "chapters": [{
            "number": 32, "title": "Thermal Time & Chill Accumulation",
            "intro": "Temperature drives plant development. Growing degree days (GDD), chill hours, and heat units are the foundation of phenology forecasting — predicting when crops will flower, mature, or be ready for harvest.",
            "sub_sections": [],
            "formulas": [
                {"code": "AM.1", "name": "Growing Degree Days (GDD)", "formula": "GDD = ((Tmax + Tmin) / 2) − Tbase", "variables": "Tmax = daily max temp (°C)\nTmin = daily min temp\nTbase = crop-specific base temp (e.g. maize 10°C, wheat 0°C)", "purpose": "Accumulate thermal time to predict growth stages. Each crop needs a specific cumulative GDD to reach flowering, maturity, etc.", "example": "Maize (Tbase=10): Tmax=28, Tmin=14 → GDD = (28+14)/2 − 10 = 11 GDD. Needs ~1500 GDD to mature.", "pitfall": "If (Tmax+Tmin)/2 < Tbase, GDD = 0 (no negative GDD). Some models cap Tmax at 30°C.", "decision": "Use GDD to schedule irrigation, fertilizer, and harvest — more accurate than calendar days.", "notes": "Also called 'heat units' or 'thermal time'. McMaster & Wilhelm (1997).", "name_ar": "وحدات النمو الحرارية", "purpose_ar": "تجميع الوقت الحراري للتنبؤ بمراحل النمو.", "variables_ar": "Tmax = الحرارة العظمى\nTmin = الحرارة الصغرى\nTbase = الحرارة الأساسية"},
                {"code": "AM.2", "name": "Chill Hours (Fruit Tree Dormancy)", "formula": "CH = Σ hours where 0 ≤ T ≤ 7°C", "variables": "T = hourly temperature\nRange: 0–7°C (standard model)", "purpose": "Accumulate winter chill for fruit tree dormancy breaking. Apples need 800-1200 CH, peaches 400-800, almonds 200-500.", "example": "Apple orchard: Nov–Feb averages 12 hr/day at 0-7°C → 12 × 120 = 1440 CH. Sufficient for most cultivars.", "pitfall": "Chill portions (dynamic model) more accurate than hours — accounts for negation by warm spells.", "decision": "Choose cultivars whose chill requirement matches your local accumulation.", "notes": "Richardson et al. (1974). Utah Model uses 0-7°C; Dynamic Model uses 0-14°C weighted.", "name_ar": "ساعات البرودة", "purpose_ar": "تجميع البرودة الشتوية لكسر سكون الأشجار المثمرة.", "variables_ar": "T = الحرارة بالساعة"},
                {"code": "AM.3", "name": "Corn Growing Degree Days (Modified)", "formula": "GDD = [(Tmax_capped + Tmin_capped) / 2] − Tbase\nTmax_capped = min(Tmax, 30)\nTmin_capped = max(Tmin, 10)", "variables": "Tmax capped at 30°C\nTmin floored at 10°C\nTbase = 10°C for corn", "purpose": "Modified GDD for corn — caps extremes because corn development slows above 30°C and stops below 10°C.", "example": "Tmax=35, Tmin=8: capped to Tmax=30, Tmin=10 → GDD = (30+10)/2 − 10 = 10. Without caps: (35+8)/2−10 = 11.5 (overstates).", "pitfall": "Different from standard GDD — always specify which model when communicating.", "decision": "Corn needs ~2700 GDD (hybrid dependent) to reach black layer (maturity).", "notes": "Iowa State University. Used by US corn belt extension services.", "name_ar": "وحدات النمو للذرة (معدلة)", "purpose_ar": "GDD معدلة للذرة مع تحديد الحدود.", "variables_ar": "Tmax محدد بـ30°\nTmin محدد بـ10°"},
                {"code": "AM.4", "name": "Heat Index (Livestock)", "formula": "HI = −8.78 + 1.61×T + 2.34×RH − 0.146×T×RH − 1.23e-2×T² − 1.64e-2×RH² + 2.21e-3×T²×RH + 7.25e-4×T×RH² − 3.58e-5×T²×RH²", "variables": "T = temperature (°C)\nRH = relative humidity (%)", "purpose": "Calculate perceived temperature for livestock heat stress. Above 32°C HI, cattle reduce feed intake; above 41°C, mortality risk.", "example": "T=35, RH=60%: HI ≈ 41°C. Severe heat stress. Activate cooling: shade + fans + water spray.", "pitfall": "Direct sun adds 3-5°C to perceived temperature. Solar radiation not in formula.", "decision": "THI (Temperature-Humidity Index) is alternative: THI = T − (0.55 − 0.0055×RH)×(T − 14.4).", "notes": "NWS Rothfusz (1990). LIVESTOCK: Cattle >32 HI = danger, >41 = emergency.", "name_ar": "مؤشر الحرارة (المواشي)", "purpose_ar": "حساب الحرارة المحسوسة لإجهاد حراري للمواشي.", "variables_ar": "T = الحرارة\nRH = الرطوبة"},
                {"code": "AM.5", "name": "Photothermal Time", "formula": "PTT = GDD × daylength_hours", "variables": "GDD = growing degree days\ndaylength = hours of daylight", "purpose": "Some crops (wheat, barley) need long days to flower. PTT accounts for both temperature and photoperiod — better predictor than GDD alone for photoperiod-sensitive crops.", "example": "Wheat at 10 GDD, 14 hr day: PTT = 140. At 10 GDD, 10 hr day: PTT = 100. Development is 40% faster in long days.", "pitfall": "Daylength varies by latitude. Use astronomical tables or NOAA calculator.", "decision": "For wheat variety selection: match PTT requirement to your latitude's photoperiod.", "notes": "Major (1980). Critical for winter cereals and soybean maturity groups.", "name_ar": "الوقف الضوئي الحراري", "purpose_ar": "يأخذ في الاعتبار الحرارة وطول النهار معاً.", "variables_ar": "GDD = وحدات النمو\ndaylength = ساعات النهار"},
                {"code": "AM.6", "name": "Frost Return Period (Gumbel)", "formula": "T_return = 1 / (1 − P)\nP = exp(−exp(−(x − μ) / β))", "variables": "T_return = return period (years)\nP = probability of exceeding temp x\nμ, β = Gumbel parameters from historical data", "purpose": "Estimate how often a given minimum temperature occurs. Helps choose: frost protection investment, planting dates, cultivar selection.", "example": "−3°C spring frost has P=0.1 → T_return = 10 years. Expect 1 in 10 years. Worth investing in protection for high-value crops.", "pitfall": "Gumbel assumes stationary climate. Climate change shifts distribution — use 30-yr rolling window.", "decision": "T_return < 5 years: invest in active protection. >10 years: risk acceptable for most crops.", "notes": "Gumbel (1958). Standard for engineering + agricultural risk assessment.", "name_ar": "فترة عودة الصقيع (Gumbel)", "purpose_ar": "تقدير تكرار حدوث صقيع بدرجة حرارة معينة.", "variables_ar": "T_return = فترة العودة\nP = الاحتمال"},
                {"code": "AM.7", "name": "Hargreaves ET₀ (Temperature-Based)", "formula": "ET₀ = 0.0023 × (Tmean + 17.8) × (Tmax − Tmin)^0.5 × Ra", "variables": "Tmean = mean daily temp (°C)\nTmax, Tmin = max/min temp\nRa = extraterrestrial radiation (MJ/m²/day)", "purpose": "Estimate ET₀ from temperature only — when solar radiation, wind, humidity data are unavailable. Less accurate than Penman-Monteith but usable everywhere.", "example": "Tmax=30, Tmin=15, Ra=30: ET₀ = 0.0023 × 22.8 × √15 × 30 = 6.1 mm/day. Similar to Penman-Monteith (~5.8).", "pitfall": "Overestimates in humid areas, underestimates in windy. Add 10% in arid zones.", "decision": "Use Hargreaves when only T data available. Upgrade to PM when full weather station exists.", "notes": "Hargreaves & Samani (1985). Ra from FAO-56 Annex 2 or astronomical equations.", "name_ar": "ET₀ لهارجريفز (حراري)", "purpose_ar": "تقدير ET₀ من درجة الحرارة فقط.", "variables_ar": "Tmean = الحرارة المتوسطة\nRa = الإشعاع الخارجي"},
                {"code": "AM.8", "name": "Crop Heat Units (CHU) — Canada", "formula": "CHU = [(Ymax + Ymin) / 2]\nYmax = 9.5×(Tmax − 4.4) for Tmax > 10\nYmin = 1.85×(Tmin − 4.4) for Tmin > 4.4", "variables": "Tmax, Tmin = daily max/min temp (°C)", "purpose": "Canadian corn heat unit system — alternative to GDD, specifically calibrated for corn + soybean in Canada/northern US.", "example": "Tmax=25, Tmin=12: Ymax=9.5×20.6=195.7, Ymin=1.85×7.6=14.1. CHU = (195.7+14.1)/2 = 104.9 CHU/day.", "pitfall": "CHU values differ from GDD — don't mix. 2700 CHU ≈ 1500 GDD for same hybrid.", "decision": "Use CHU for Ontario/Quebec corn. Use GDD everywhere else.", "notes": "Ontario Ministry of Agriculture. CHU map is the standard for Canadian corn hybrid selection.", "name_ar": "وحدات الحرارة للمحاصيل (كندا)", "purpose_ar": "نظام كندي لوحدات الحرارة للذرة.", "variables_ar": "Tmax, Tmin = الحرارة العظمى والصغرى"},
                {"code": "AM.9", "name": "Cumulative GDD from Planting", "formula": "GDD_cumulative = Σ GDD_daily from planting to current date", "variables": "GDD_daily = daily GDD (see AM.1)", "purpose": "Track thermal time accumulation from planting date. Predict growth stage transitions: emergence, tillering, flowering, maturity.", "example": "Maize planted April 15. 30 days × 12 GDD/day average = 360 GDD → V6 stage (about 350 GDD).", "pitfall": "GDD accumulation pauses on cold days (below Tbase). Calendar days overstate progress in cool periods.", "decision": "Use GDD to schedule: herbicide application (V4-V6), side-dress N (V6), fungicide (VT-silking).", "notes": "Most extension services publish daily GDD accumulations. Build your own from weather data.", "name_ar": "المجموع التراكمي للـGDD", "purpose_ar": "تتبع تراكم الوقت الحراري من تاريخ الزراعة.", "variables_ar": "GDD_daily = اليومي"},
                {"code": "AM.10", "name": "Vernalization Requirement (Winter Cereals)", "formula": "V = Σ VU_daily\nVU = max(0, 1 − 0.5×|T − 4.4| / 4.4) for 0 ≤ T ≤ 10", "variables": "T = daily mean temperature (°C)\nVU = vernalization units\nRange: 0-10°C, optimal at 4.4°C", "purpose": "Calculate vernalization (cold requirement) for winter wheat/ barley. Without sufficient vernalization, plants won't flower — they stay vegetative indefinitely.", "example": "Winter wheat needs V=50-60 days of vernalization. At 5°C average for 60 days: VU ≈ 0.95 × 60 = 57. Sufficient.", "pitfall": "High temps (>15°C) can reverse (de-vernalize) accumulated units. Use 7-day running mean.", "decision": "If vernalization insufficient by spring, crop won't head. Plant earlier or choose spring variety.", "notes": "Trione & Metzger (1970). Some modern varieties have reduced vernalization requirements.", "name_ar": "متطلبات التنضيد (الحبوب الشتوية)", "purpose_ar": "حساب البرودة اللازمة لإزهار القمح الشتوي.", "variables_ar": "T = الحرارة اليومية"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: GDD-based scheduling reduces unnecessary pesticide + fertilizer applications — apply only when crop is at the right stage."],
            "decision_boxes": ["▲  Decision: Track GDD from planting date. Most extension services publish daily GDD online — bookmark your local station."],
        }],
    },

    # ========================================================================
    # 2. AQUACULTURE & FISH FARMING (12)
    # ========================================================================
    {
        "roman": "XXXIII", "title": "Aquaculture & Fish Farming",
        "chapters": [{
            "number": 33, "title": "Fish Production Systems",
            "intro": "Aquaculture is the fastest-growing food production sector globally. These formulas cover stocking density, feeding, water quality, and economics — the core math for profitable fish farming.",
            "sub_sections": [],
            "formulas": [
                {"code": "AQ.1", "name": "Fish Stocking Density", "formula": "SD = (Biomass_target) / (Volume × DO_safety)", "variables": "Biomass = kg fish at harvest\nVolume = pond/tank volume (m³)\nDO_safety = dissolved O₂ safety factor (0.6-0.8)", "purpose": "Calculate safe stocking density based on oxygen availability. Overstocking → O₂ depletion → fish kill.", "example": "Tilapia pond 100 m³, target 500 kg. DO safety 0.7: SD = 500/(100×0.7) = 7.1 kg/m³. Moderate — needs aeration above 5 kg/m³.", "pitfall": "DO varies diurnally — lowest at dawn. Size for worst case, not average.", "decision": "Above 5 kg/m³: install paddlewheel aerators. Above 10: pure O₂ injection.", "notes": "FAO Aquaculture Manual. Tilapia can tolerate 3 mg/L DO; trout need >6.", "name_ar": "كثافة تخزين الأسماك", "purpose_ar": "حساب كثافة التخزين الآمنة بناءً على الأكسجين.", "variables_ar": "Biomass = كتلة السمك\nVolume = الحجم"},
                {"code": "AQ.2", "name": "Feed Conversion Ratio (FCR)", "formula": "FCR = Feed_given / Weight_gain", "variables": "Feed_given = kg feed (dry)\nWeight_gain = kg fish gained", "purpose": "Measure feed efficiency. Lower FCR = better. Carnivorous fish (salmon): ~1.2. Omnivorous (tilapia): ~1.5-2.0. Above 2.5: problem.", "example": "Fed 50 kg feed, fish gained 30 kg: FCR = 50/30 = 1.67. Good for tilapia.", "pitfall": "FCR increases with fish size — large fish convert less efficiently. Track by size class.", "decision": "If FCR >2.5: check feed quality, water temp, DO, disease.", "notes": "Economic FCR includes feed cost: $/kg fish = FCR × $/kg feed.", "name_ar": "معامل تحويل الغذاء", "purpose_ar": "قياس كفاءة الغذاء. الأقل = أفضل.", "variables_ar": "Feed = الغذاء المعطى\nWeight_gain = الزيادة في الوزن"},
                {"code": "AQ.3", "name": "Dissolved O₂ Saturation", "formula": "DO_sat = 14.65 − 0.410×T + 0.008×T² − 0.0001×T³ − 0.039×altitude_factor", "variables": "T = water temperature (°C)\naltitude_factor = elevation/300 (m)", "purpose": "Calculate max dissolved O₂ at given water temp + altitude. Warm water holds less O₂ — critical in summer.", "example": "Water at 28°C, sea level: DO_sat = 14.65 − 11.5 + 6.3 − 2.2 = 7.8 mg/L. Fish need 5+ mg/L — margin is thin.", "pitfall": "Salinity reduces DO saturation by ~5% per 10 ppt. Account for seawater.", "decision": "If DO <4 mg/L: start emergency aeration. Target >5 for warm-water, >6 for cold-water fish.", "notes": "Benson & Krause (1984). EPA Standard Methods.", "name_ar": "تشبع الأكسجين المذاب", "purpose_ar": "حساب أقصى أكسجين مذاب عند حرارة معينة.", "variables_ar": "T = حرارة الماء"},
                {"code": "AQ.4", "name": "Ammonia Toxicity (Un-ionized NH₃)", "formula": "NH₃ = TAN × (1 / (1 + 10^(pKa − pH)))\npKa = 9.24 + 0.0302×T", "variables": "TAN = total ammonia nitrogen (mg/L)\npH = water pH\nT = temperature (°C)", "purpose": "Calculate toxic un-ionized ammonia fraction. NH₃ (not NH₄⁺) is lethal to fish at 0.02 mg/L. Higher pH + temp → more toxic NH₃.", "example": "TAN=2 mg/L, pH=8.5, T=25°C: pKa=8.49. NH₃ = 2 × (1/(1+10^(8.49-8.5))) = 2 × 0.51 = 1.02 mg/L. Lethal — emergency water change.", "pitfall": "Afternoon pH peaks (algae photosynthesis) create ammonia spikes. Test at dawn + afternoon.", "decision": "If NH₃ >0.02 mg/L: reduce feeding, exchange water, add biofilter bacteria.", "notes": "Emerson et al. (1975). Critical threshold: trout 0.01, tilapia 0.05 mg/L NH₃-N.", "name_ar": "سمية الأمونيا", "purpose_ar": "حساب جزء الأمونيا السام غير المتأين.", "variables_ar": "TAN = إجمالي أمونيا النيتروجين\npH = الحموضة"},
                {"code": "AQ.5", "name": "Water Exchange Rate", "formula": "R = Q / V\nTurnover = 24 / R (hours per exchange)", "variables": "Q = flow rate (m³/hr)\nV = pond/tank volume (m³)\nR = exchanges per hour", "purpose": "Size water exchange for ammonia control. Minimum 1 exchange/day for static ponds; 4-6/day for intensive RAS.", "example": "100 m³ pond, pump 10 m³/hr: R = 10/100 = 0.1/hr. Turnover = 24/0.1 = 240 hr = 10 days. Too slow for intensive farming.", "pitfall": "Exchange rate doesn't equal flushing efficiency — short-circuiting (water bypasses pond) reduces effective exchange.", "decision": "Intensive (≥20 kg/m³): 4+ exchanges/day. Semi-intensive: 1-2/day. Static: rely on biofiltration.", "notes": "Timmons & Ebeling (2010) Recirculating Aquaculture.", "name_ar": "معدل تبادل المياه", "purpose_ar": "تحديد معدل تبادل المياه للسيطرة على الأمونيا.", "variables_ar": "Q = معدل التدفق\nV = الحجم"},
                {"code": "AQ.6", "name": "Biofilter Sizing (Nitrification)", "formula": "A_biofilter = (Feed × protein × 0.092) / (NLR × 24)", "variables": "Feed = daily feed (kg/day)\nprotein = feed protein % (e.g. 0.32)\nNLR = nitrification loading rate (g N/m²/day)\n0.092 = fraction of protein-N excreted as ammonia", "purpose": "Size biofilter surface area for ammonia removal. Biofilter bacteria convert NH₃ → NO₂⁻ → NO₃⁻ (nontoxic). Under-sized biofilter → ammonia kills.", "example": "Feeding 5 kg/day at 32% protein. NLR=0.5 g/m²/day: A = (5×0.32×0.092)/(0.5×24) = 0.012 m²... scale by 1000 for media → 12 m² media surface.", "pitfall": "Nitrification needs O₂ + alkalinity. Add 4.57 g O₂ per g NH₃-N oxidized + 7.14 g alkalinity.", "decision": "Use plastic bio-balls (500 m²/m³) or Kaldnes K1 (800 m²/m³). Size for peak feed, not average.", "notes": "Chen et al. (2006). RAS design standard. Monitor NO₂⁻ spike during startup.", "name_ar": "حجم المرشح الحيوي", "purpose_ar": "تحديد مساحة المرشح الحيوي لإزالة الأمونيا.", "variables_ar": "Feed = الغذاء اليومي\nprotein = نسبة البروتين\nNLR = معدل التحميل"},
                {"code": "AQ.7", "name": "Protein Retention Efficiency", "formula": "PRE = (fish_P_final − fish_P_initial) / feed_P × 100", "variables": "fish_P = protein mass in fish (kg)\nfeed_P = protein mass in feed (kg)", "purpose": "Measure how efficiently fish convert dietary protein to biomass. Good: 30-40%. Below 20%: protein wasted (expensive + polluting).", "example": "Fed 10 kg protein, fish gained 3 kg protein: PRE = 3/10 = 30%. Industry standard for tilapia.", "pitfall": "Protein digestibility varies by ingredient. Fish meal ~90%, plant protein ~70-80%.", "decision": "Optimize: balanced amino acid profile reduces protein waste. Replace fish meal with soybean meal + synthetic amino acids.", "notes": "NRC (2011) Nutrient Requirements of Fish and Shrimp.", "name_ar": "كفاءة الاحتفاظ بالبروتين", "purpose_ar": "قياس كفاءة تحويل البروتين الغذائي إلى كتلة حيوية.", "variables_ar": "fish_P = بروتين السمك\nfeed_P = بروتين الغذاء"},
                {"code": "AQ.8", "name": "Pond Carrying Capacity", "formula": "CC = (DO_available) / (DO_consumption_per_kg × safety_factor)", "variables": "DO_available = O₂ supply (mg/L × volume)\nDO_consumption = ~200 mg O₂/kg fish/hr\nsafety_factor = 2-3", "purpose": "Maximum fish biomass a pond can support without aeration. Beyond CC → fish kill. Increases with aeration, flow, shallow depth.", "example": "100 m³ pond, DO_sat=8 mg/L, no aeration: available=800,000 mg O₂. CC = 800000/(200×3) = 1333 kg. Realistic: ~500 kg/ha (static pond).", "pitfall": "DO varies diurnally — algae adds O₂ by day, consumes by night. Design for dawn minimum.", "decision": "Aeration multiplies CC by 2-5×. Paddlewheel: 1 HP per 200 kg fish above CC.", "notes": "Boyd (1998). Standard aquaculture pond management text.", "name_ar": "سعة التحميل للبركة", "purpose_ar": "أقصى كتلة سمك تدعمها البركة بدون تهوية.", "variables_ar": "DO_available = إمداد الأكسجين"},
                {"code": "AQ.9", "name": "Thermal Growth Coefficient (Q10)", "formula": "Q10 = (R2/R1)^(10/(T2-T1))", "variables": "R1, R2 = metabolic rates at temps T1, T2\nQ10 = typically 2-3 for fish", "purpose": "Predict growth rate change with temperature. Fish are poikilothermic — a 10°C rise roughly doubles metabolic rate + growth.", "example": "Tilapia grows 1.0 g/day at 25°C. At 30°C (Q10=2.5): R2 = 1.0 × 2.5^(5/10) = 1.58 g/day. 58% faster growth at 30°C.", "pitfall": "Above optimal temp, growth declines (stress). Tilapia optimal: 28-30°C, above 35°C: death.", "decision": "Choose species matching your water temperature. Heat water for subtropical species in cold climates.", "notes": "Brett (1979). Q10 varies by species + acclimation temperature.", "name_ar": "معامل النمو الحراري (Q10)", "purpose_ar": "التنبؤ بتغير معدل النمو مع درجة الحرارة.", "variables_ar": "R1, R2 = معدلات الأيض"},
                {"code": "AQ.10", "name": "Specific Growth Rate (SGR)", "formula": "SGR = ((ln W2 − ln W1) / t) × 100", "variables": "W1, W2 = initial/final weight (g)\nt = days between measurements", "purpose": "Measure daily growth rate as % body weight. Standard metric for comparing fish growth across studies + farms.", "example": "Fish grew from 10 g to 50 g in 30 days: SGR = (ln50 − ln10)/30 × 100 = (3.91−2.30)/30 × 100 = 5.4%/day. Excellent.", "pitfall": "SGR decreases with fish size — small fish grow faster (% basis). Always specify size range.", "decision": "Tilapia SCR target: 3-5%/day (fingerlings), 1-2%/day (adults). Below 1%: check system.", "notes": "Ricker (1979). Used in all aquaculture research papers.", "name_ar": "معدل النمو النوعي", "purpose_ar": "قياس معدل النمو اليومي كنسبة من وزن الجسم.", "variables_ar": "W1, W2 = الوزن الأولي والنهائي"},
                {"code": "AQ.11", "name": "Break-Even Fish Price", "formula": "P_BE = (Feed_cost + Fingerling + Fixed + Variable) / Production_kg", "variables": "Feed_cost = FCR × $/kg feed × kg produced\nFingerling = cost of seed\nFixed = depreciation + interest + insurance\nVariable = labor + electricity + water + chemicals", "purpose": "Calculate minimum price per kg fish to cover all costs. Below this price, lose money. Essential for investment decisions.", "example": "Produce 5,000 kg tilapia. Feed $3,000, fingerlings $500, fixed $1,000, variable $500. P_BE = 5000/5000 = $1.00/kg. Market price $2.50: $7,500 profit.", "pitfall": "FCR drives 50-70% of cost. Small FCR improvement has big economic impact.", "decision": "If market price < P_BE: reduce FCR (better feed, aeration, grading) or increase scale.", "notes": "Engle (2010) Aquaculture Economics. Compare to market price for go/no-go.", "name_ar": "سعر التعادل للسمك", "purpose_ar": "حساب الحد الأدنى للسعر لتغطية التكاليف.", "variables_ar": "Feed_cost = تكلفة الغذاء"},
                {"code": "AQ.12", "name": "Sludge Production", "formula": "S = Feed × (1 − digestibility) × 0.25 + Feed × digestibility × 0.15", "variables": "Feed = daily feed (kg/day)\ndigestibility = feed digestibility (0.75-0.85)\n0.25 = undigested solids fraction\n0.15 = metabolic waste solids", "purpose": "Estimate solid waste (sludge) production. Sizing settling tanks, sludge collectors, and disposal. Critical for RAS design.", "example": "Feeding 10 kg/day at 80% digestibility: S = 10×0.2×0.25 + 10×0.8×0.15 = 0.5 + 1.2 = 1.7 kg sludge/day.", "pitfall": "Sludge volume is 5-10× mass (water content). Size tanks by volume, not mass.", "decision": "Remove sludge daily. Compost with carbon (C:N 30:1) or anaerobic digest for biogas.", "notes": "Chen et al. (1997). Solids management is #1 challenge in RAS.", "name_ar": "إنتاج الحمأة", "purpose_ar": "تقدير النفايات الصلبة (الحمأة) في نظام الاستزراع.", "variables_ar": "Feed = الغذاء اليومي\ndigestibility = الهضم"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: Aquaculture has lower carbon footprint than terrestrial meat. FCR 1.5 for fish vs 6-10 for beef."],
            "decision_boxes": ["▲  Decision: Monitor DO + NH₃ daily at dawn. Keep a log — trends warn of problems before fish die."],
        }],
    },

    # ========================================================================
    # 3. AGROFORESTRY (8)
    # ========================================================================
    {
        "roman": "XXXIV", "title": "Agroforestry",
        "chapters": [{
            "number": 34, "title": "Tree-Crop Integration",
            "intro": "Agroforestry integrates trees with crops + livestock for multiple products, ecosystem services, and climate resilience. Key for sustainable intensification in arid regions.",
            "sub_sections": [],
            "formulas": [
                {"code": "AGR.1", "name": "Alley Cropping Light Competition", "formula": "L_reduction = (1 − exp(−k × LAI × (1 − d/H))) × 100", "variables": "k = light extinction coeff (0.4-0.6)\nLAI = tree leaf area index\nd = distance from tree row (m)\nH = tree height (m)", "purpose": "Estimate light reduction at crop level as function of distance from tree row. Design alley width to minimize competition.", "example": "Tree H=8m, LAI=3, k=0.5. At d=4m: L = (1−exp(−0.5×3×0.5))×100 = 53% light reduction. Too much — widen alley.", "pitfall": "Light varies by tree species + pruning. Deciduous trees lose leaves in winter (light for winter crop).", "decision": "Minimum alley width = 1× tree height for acceptable light (>50%).", "notes": "Jackson & Wallace (1999). Pruning reduces LAI and competition.", "name_ar": "منافسة الضوء في الزراعة البينية", "purpose_ar": "تقدير تقليل الضوء عند مستوى المحصول حسب المسافة من شجرة.", "variables_ar": "k = معامل انقراض الضوء\nLAI = مؤشر مساحة الأوراق"},
                {"code": "AGR.2", "name": "Windbreak Protection Zone", "formula": "Z = 10 × H × porosity_factor\nporosity_factor = 1 − density (0.2-0.6)", "variables": "H = windbreak height (m)\nporosity = 0.4 optimal (40% density)", "purpose": "Calculate downwind protected zone. Windbreaks reduce wind speed by 50-70%, reducing erosion + evapotranspiration + crop lodging.", "example": "Windbreak H=6m, density 40% (porosity_factor=0.6): Z = 10 × 6 × 0.6 = 36m protected downwind.", "pitfall": "Dense windbreaks (>60%) create turbulence downwind — less protection. 40% is optimal.", "decision": "Space windbreaks every 15-20× height. Plant perpendicular to prevailing wind.", "notes": "Caborn (1965). Multi-row: outer row dense (conifer), inner porous (deciduous).", "name_ar": "منطقة حماية مصد الرياح", "purpose_ar": "حساب المنطقة المحمية مهب الريح.", "variables_ar": "H = ارتفاع المصد\nporosity = النفاذية"},
                {"code": "AGR.3", "name": "Tree-Crop Root Competition Zone", "formula": "R = 1.5 × canopy_radius", "variables": "canopy_radius = tree canopy spread (m)\nR = root competition radius", "purpose": "Estimate zone of below-ground competition. Tree roots compete with crops for water + nutrients up to 1.5× canopy radius.", "example": "Tree canopy radius 3m: R = 4.5m. Crops within 4.5m of trunk will have reduced yield.", "pitfall": "Root pruning (trenching) reduces competition but can destabilize tree.", "decision": "Apply fertilizer + irrigation in crop zone beyond R. Root-prune annually at canopy edge.", "notes": "Ong et al. (1991). Competition is worst in dry climates — trees mine deep water.", "name_ar": "منطقة منافسة الجذور", "purpose_ar": "تقدير منطقة المنافسة تحت الأرض.", "variables_ar": "canopy_radius = نصف قطر التاج"},
                {"code": "AGR.4", "name": "Carbon Sequestration (Agroforestry)", "formula": "C_seq = (tree_biomass × 0.5 + soil_C_gain) × area × years", "variables": "tree_biomass = t DM/ha/yr\n0.5 = carbon fraction of biomass\nsoil_C_gain = t C/ha/yr from leaf litter + roots", "purpose": "Estimate total carbon sequestration from agroforestry. Higher than monoculture — qualifies for carbon credits.", "example": "Leucaena 8 t DM/ha/yr, soil gain 0.5 t C: C_seq = (8×0.5 + 0.5) = 4.5 t C/ha/yr = 16.5 t CO₂e/ha/yr.", "pitfall": "Tree harvest releases stored C. Long-term C requires permanent trees + regrowth.", "decision": "Choose fast-growing N-fixing trees (Leucaena, Gliricidia) for max C + N.", "notes": "IPCC 2006. Agroforestry C rates: 2-10 t CO₂e/ha/yr depending on system.", "name_ar": "عزل الكربون في الحراج الزراعي", "purpose_ar": "تقدير إجمالي الكربون المختزن.", "variables_ar": "tree_biomass = الكتلة الحيوية"},
                {"code": "AGR.5", "name": "Fodder Tree Carrying Capacity", "formula": "CC = (biomass × utilization × protein) / (intake × protein_req × grazing_days)", "variables": "biomass = edible DM production (kg/ha)\nutilization = safe utilization rate (0.5-0.7)\nintake = 3% BW (kg DM/day)\nprotein_req = protein requirement (g/day)", "purpose": "Estimate livestock carrying capacity for fodder trees (Leucaena, Acacia). Enables rotational browsing.", "example": "Leucaena produces 4000 kg DM/ha, 25% protein. 400 kg cow, 3% BW = 12 kg/day: CC = (4000×0.6×0.25)/(12×0.12×180) = 2.3 cows/ha for 6 months.", "pitfall": "Some fodder trees contain anti-nutritional factors (mimosine in Leucaena). Limit to 30% of diet.", "decision": "Supplement with grass — trees provide protein, grass provides energy.", "notes": "Gutteridge & Shelton (1994). Leucaena + grass pasture = 2× carrying capacity of grass alone.", "name_ar": "السعة الاستيعابية لأشجار العلف", "purpose_ar": "تقدير السعة لرعي المواشي على أشجار العلف.", "variables_ar": "biomass = الإنتاج الصالح للأكل"},
                {"code": "AGR.6", "name": "Shade Effect on Understory Yield", "formula": "Y_loss = shade% × crop_sensitivity", "variables": "shade% = percent light reduction (0-1)\ncrop_sensitivity = 0.3 (tolerant) to 1.2 (sensitive)", "purpose": "Predict yield loss of understory crop due to tree shade. Shade-tolerant crops (coffee, cacao) lose less than cereals.", "example": "Maize under 30% shade, sensitivity 1.0: Y_loss = 0.30 × 1.0 = 30% yield reduction. Coffee under 30% shade, sensitivity 0.2: 6% loss — shade beneficial (reduces heat stress).", "pitfall": "Some crops benefit from shade in hot climates. Shade reduces temperature + evapotranspiration.", "decision": "Match crop to shade level. Coffee: 30-50% shade. Maize: 0-10%. Choose shade-tolerant varieties.", "notes": "Mead & Willey (1980). Light × water × nutrient interactions are complex — test locally.", "name_ar": "تأثير الظل على إنتاج المحصول", "purpose_ar": "التنبؤ بخسارة إنتاج المحصول بسبب ظل الأشجار.", "variables_ar": "shade% = نسبة تقليل الضوء"},
                {"code": "AGR.7", "name": "Nitrogen Fixation by Tree Legumes", "formula": "N_fix = tree_biomass × N_content × BNF_fraction", "variables": "tree_biomass = annual DM production (kg/ha)\nN_content = nitrogen % of biomass (3-4% for legumes)\nBNF_fraction = fraction from biological fixation (0.5-0.8)", "purpose": "Estimate N contributed to system by tree legumes. Reduces fertilizer need for companion crop. Key benefit of agroforestry.", "example": "Leucaena 5000 kg DM/ha, 3.5% N, 70% BNF: N_fix = 5000 × 0.035 × 0.7 = 122 kg N/ha/yr. Equivalent to 265 kg urea.", "pitfall": "N is released slowly (decomposition). Immediate crop availability is 20-40% of total.", "decision": "Plant N-fixing trees as green manure — coppice + spread leaves on crop zone.", "notes": "Peoples et al. (1995). Acacia, Leucaena, Gliricidia, Calliandra are top N-fixers.", "name_ar": "تثبيت النيتروجين بأشجار البقول", "purpose_ar": "تقدير النيتروجين المقدم من أشجار البقول للنظام.", "variables_ar": "tree_biomass = الإنتاج السنوي"},
                {"code": "AGR.8", "name": "Economic Rotation Age (NPV Max)", "formula": "Maximize NPV = Σ (Rt − Ct)/(1+r)^t + (timber_value at harvest)/(1+r)^T", "variables": "Rt = annual revenue (crops + fodder + fruit)\nCt = annual cost\nr = discount rate\nT = rotation age (years)", "purpose": "Determine optimal tree harvest age that maximizes combined NPV of tree products + companion crops. Longer rotations ≠ more profit — opportunity cost of land.", "example": "Poplar agroforestry: crop revenue $500/yr, timber $15,000 at year 12. r=6%. NPV = Σ500/(1.06)^t + 15000/(1.06)^12. Try different T — optimum at year 14.", "pitfall": "Timber prices fluctuate. Use 10-year rolling average. Carbon credit revenue extends optimal rotation.", "decision": "Include non-timber products (fruit, fodder, honey) — they shift optimum to longer rotations.", "notes": "Pearce (1994). Faustmann formula modified for agroforestry.", "name_ar": "العمر الاقتصادي للدورة", "purpose_ar": "تحديد العمر الأمثل لقطع الأشجار لزيادة NPV.", "variables_ar": "Rt = الدخل السنوي\nr = معدل الخصم"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: Agroforestry sequesters 2-10× more carbon than monoculture while maintaining food production."],
            "decision_boxes": ["▲  Decision: Start with N-fixing fodder trees (Leucaena, Gliricidia) — immediate benefit (fodder + N) + long-term timber."],
        }],
    },

    # ========================================================================
    # 4. BIOENERGY (8)
    # ========================================================================
    {
        "roman": "XXXV", "title": "Bioenergy",
        "chapters": [{
            "number": 35, "title": "Biogas & Biomass Energy",
            "intro": "Bioenergy converts agricultural waste to usable energy — biogas from anaerobic digestion, heat from biomass combustion. Reduces fossil fuel dependency + waste disposal costs.",
            "sub_sections": [],
            "formulas": [
                {"code": "BE.1", "name": "Biogas Yield by Substrate", "formula": "V_biogas = VS × BMP", "variables": "VS = volatile solids (kg)\nBMP = biochemical methane potential (L CH₄/kg VS)", "purpose": "Estimate biogas production from given substrate. BMP varies: manure 200-400, food waste 400-600, crop residue 150-350 L/kg VS.", "example": "100 kg cattle manure, 80% VS, BMP=250: V = 80 × 250 = 20,000 L = 20 m³ biogas. At 60% CH₄ = 12 m³ CH₄.", "pitfall": "BMP is lab maximum. Field digester achieves 60-80% of BMP (retention time + temp limited).", "decision": "Co-digestion (manure + food waste) increases yield 2-3× vs manure alone.", "notes": "Angelidaki et al. (2009). BMP database: www.bioenergy.au.dk.", "name_ar": "إنتاج الغاز الحيوي", "purpose_ar": "تقدير إنتاج الغاز الحيوي من مادة معينة.", "variables_ar": "VS = المواد الصلبة المتطايرة\nBMP = إنتاج الميثان الحيوي"},
                {"code": "BE.2", "name": "Methane Content (%)", "formula": "CH₄% = (VS_digestible × 0.35 × 0.9) / V_biogas × 100", "variables": "VS_digestible = fraction of VS actually digested (0.4-0.7)\n0.35 = m³ CH₄ per kg VS at STP\n0.9 = methanogen efficiency", "purpose": "Estimate methane concentration in biogas. CH₄ is the energy carrier — higher % = more valuable. Good: 55-65%. Below 50%: digester problem.", "example": "100 kg VS, 60% digested: CH₄ = 100×0.6×0.35×0.9 = 18.9 m³ CH₄. If total biogas = 30 m³: CH₄% = 63%. Excellent.", "pitfall": "High sulfate in substrate → H₂S competes with CH₄ (reduces quality + corrodes engines).", "decision": "If CH₄ <50%: check C:N (should be 20-30:1), temperature (35°C mesophilic), mixing.", "notes": "Buswell & Mueller (1952). Stoichiometric formula for CH₄ prediction.", "name_ar": "محتوى الميثان (%)", "purpose_ar": "تقدير تركيز الميثان في الغاز الحيوي.", "variables_ar": "VS_digestible = المواد المهضومة"},
                {"code": "BE.3", "name": "Digester Sizing (m³)", "formula": "V_digestor = Q_daily × HRT", "variables": "Q_daily = daily feed volume (m³/day)\nHRT = hydraulic retention time (days)\nMesophilic: 20-30 days, Thermophilic: 10-15", "purpose": "Size anaerobic digester volume for given feed rate + temperature. Too small = incomplete digestion + low yield. Too large = expensive.", "example": "50 kg/day manure at 10% solids = 0.5 m³/day. Mesophilic HRT=25: V = 0.5 × 25 = 12.5 m³ digester.", "pitfall": "HRT depends on temperature: mesophilic (35°C) needs 20-30 days, thermophilic (55°C) 10-15 but is harder to maintain.", "decision": "Size digester for 1.2× calculated volume (safety factor). Use mesophilic for reliability.", "notes": "Nijaguna (2006). Indian floating-dome (KVIC) vs Chinese fixed-dome designs.", "name_ar": "حجم المهضم", "purpose_ar": "تحديد حجم المهضم اللاهوائي.", "variables_ar": "Q_daily = التغذية اليومية\nHRT = زمن البقاء"},
                {"code": "BE.4", "name": "Hydraulic Retention Time", "formula": "HRT = V_digestor / Q_daily", "variables": "V = digester working volume (m³)\nQ = daily inflow rate (m³/day)", "purpose": "Calculate how long feed stays in digester. Longer HRT = more complete digestion but lower throughput. Balance yield vs. volume.", "example": "10 m³ digester, 0.4 m³/day feed: HRT = 10/0.4 = 25 days. Optimal for mesophilic.", "pitfall": "Too short HRT washes out methanogens (slow-growing). Below 10 days at 35°C = digester failure.", "decision": "If HRT <15: reduce feed rate or increase volume. Monitor VFA (volatile fatty acids) — above 2000 mg/L = overload.", "notes": "SRT (solids retention time) can exceed HRT in digesters with solids recycling — increases efficiency.", "name_ar": "زمن البقاء الهيدروليكي", "purpose_ar": "حساب مدة بقاء التغذية في المهضم.", "variables_ar": "V = الحجم الفعال\nQ = معدل التدفق"},
                {"code": "BE.5", "name": "C:N Ratio for Anaerobic Digestion", "formula": "C:N_mix = Σ(Cᵢ × Wᵢ) / Σ(Nᵢ × Wᵢ)\nOptimal: 20-30:1", "variables": "Cᵢ = carbon % of each substrate\nNᵢ = nitrogen %\nWᵢ = weight", "purpose": "Optimize C:N for anaerobic digestion. Below 15:1 → NH₃ toxicity to methanogens. Above 35:1 → N-limited (slow digestion).", "example": "Mix 80 kg manure (C:N=18:1) + 20 kg crop residue (C:N=60:1): C:N = (80×45+20×48)/(80×2.5+20×0.8) = 4560/216 = 21.1. Optimal.", "pitfall": "Lignin is not digestible. Reduce effective C for high-lignin substrates (straw, wood).", "decision": "Co-digest high-N (manure) with high-C (straw, food waste) to hit 25:1.", "notes": "Same mixing formula as composting — but AD target is 20-30 vs composting 25-30.", "name_ar": "نسبة C:N للهضم اللاهوائي", "purpose_ar": "تحسين نسبة C:N للهضم اللاهوائي.", "variables_ar": "C = كربون\nN = نيتروجين\nW = وزن"},
                {"code": "BE.6", "name": "Energy Content of Biogas (kWh)", "formula": "E = V_biogas × CH₄% × 9.94 / 100", "variables": "V_biogas = volume (m³)\nCH₄% = methane fraction (%)\n9.94 = kWh per m³ pure CH₄", "purpose": "Convert biogas volume to usable energy. At 60% CH₄: 1 m³ biogas ≈ 6 kWh. For comparison: 1 L diesel = 10 kWh, 1 kg LPG = 14 kWh.", "example": "20 m³ biogas at 60% CH₄: E = 20 × 60 × 9.94 / 100 = 119 kWh. Equivalent to 12 L diesel or 8.5 kg LPG.", "pitfall": "Only 30-40% of biogas energy converts to electricity (generator efficiency). Rest is heat — use for hot water + space heating.", "decision": "CHP (combined heat + power) is most efficient: 35% electricity + 50% heat. Surplus electricity can be sold to grid.", "notes": "Lower heating value of CH₄ = 9.94 kWh/m³. Higher heating value = 11.0 (includes condensation heat).", "name_ar": "محتوى الطاقة في الغاز الحيوي", "purpose_ar": "تحويل حجم الغاز الحيوي إلى طاقة قابلة للاستخدام.", "variables_ar": "V_biogas = الحجم\nCH₄% = نسبة الميثان"},
                {"code": "BE.7", "name": "Energy Return on Investment (EROI)", "formula": "EROI = Energy_output / Energy_input", "variables": "Energy_output = biofuel energy content (MJ/ha)\nEnergy_input = fuel + fertilizer + machinery + processing (MJ/ha)", "purpose": "Evaluate energy efficiency of biofuel crops. EROI >1: positive energy balance. Corn ethanol EROI ≈ 1.3, sugarcane ethanol ≈ 8, biodiesel ≈ 3.", "example": "Canola biodiesel: output = 50 GJ/ha, input = 15 GJ (fertilizer 8 + fuel 3 + processing 4): EROI = 50/15 = 3.3. Positive but modest.", "pitfall": "N fertilizer is energy-intensive (natural gas for Haber-Bosch). Low-N crops (switchgrass) have higher EROI.", "decision": "EROI >3: viable. 1-3: marginal (depends on policy support). <1: energy sink.", "notes": "Hall et al. (2014). EROI debate: some argue corn ethanol EROI <1 if indirect land use included.", "name_ar": "عائد الطاقة على الاستثمار", "purpose_ar": "تقييم كفاءة الطاقة لمحاصيل الوقود الحيوي.", "variables_ar": "Energy_output = إنتاج الطاقة\nEnergy_input = مدخلات الطاقة"},
                {"code": "BE.8", "name": "Biomass Heating Value (MJ/kg)", "formula": "HHV = 0.3491×C + 1.1783×H − 0.1034×O − 0.0211×A + 0.1005×S − 0.0151×N", "variables": "C, H, O, S, N = elemental composition (% dry)\nA = ash content (%)", "purpose": "Estimate higher heating value from biomass composition. Dry wood ≈ 19 MJ/kg, straw ≈ 17, manure ≈ 15. Moisture reduces usable energy.", "example": "Wood pellets: C=50%, H=6%, O=43%, A=0.5%, S=0.01, N=0.1: HHV = 17.5 + 7.1 − 4.4 − 0.01 + 0.001 − 0.002 = 20.1 MJ/kg. Matches lab.", "pitfall": "Net heating value (LHV) = HHV − 2.45 × (9×H + M)/100 (subtract water vaporization). LHV is what you actually use.", "decision": "Dry biomass to <20% moisture for combustion. Each 10% moisture reduces net energy by ~2 MJ/kg.", "notes": "Boie (1957). Dulong-Berthelot and Channiwala-Parikh are alternative formulas.", "name_ar": "القيمة الحرارية للكتلة الحيوية", "purpose_ar": "تقدير القيمة الحرارية العالية من التركيب العنصري.", "variables_ar": "C = كربون\nH = هيدروجين\nO = أكسجين\nA = رماد"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: Biogas is carbon-neutral (biogenic CO₂) + reduces methane emissions from manure + produces organic fertilizer (digestate)."],
            "decision_boxes": ["▲  Decision: For small farms: 6-10 m³ plug-flow digester. Payback 3-5 years from cooking gas + fertilizer savings."],
        }],
    },

    # ========================================================================
    # 5. PLANT BREEDING & GENETICS (8)
    # ========================================================================
    {
        "roman": "XXXVI", "title": "Plant Breeding & Genetics",
        "chapters": [{
            "number": 36, "title": "Selection & Genetic Gain",
            "intro": "Plant breeding quantitative genetics — heritability, response to selection, and genetic gain. These formulas guide breeding program design for maximum improvement per cycle.",
            "sub_sections": [],
            "formulas": [
                {"code": "PB.1", "name": "Broad-Sense Heritability (H²)", "formula": "H² = Vg / Vp = Vg / (Vg + Ve)", "variables": "Vg = genetic variance\nVe = environmental variance\nVp = phenotypic variance", "purpose": "Estimate proportion of phenotypic variation due to genetics. High H² (>0.5) → selection effective. Low H² (<0.2) → environment dominates.", "example": "Wheat yield: Vp=2.5, Vg=1.0, Ve=1.5: H² = 1.0/2.5 = 0.40. Moderate heritability — selection moderately effective.", "pitfall": "H² is population + environment specific. Same trait can have H²=0.8 in one trial and 0.2 in another.", "decision": "If H² <0.3: use replicated trials + BLUP to improve selection accuracy.", "notes": "Nyquist (1991). H² includes additive + dominance + epistatic variance.", "name_ar": "قابلية التوريث الواسعة", "purpose_ar": "تقدير نسبة التباين الوراثي في التباين المظهري.", "variables_ar": "Vg = التباين الوراثي\nVe = التباين البيئي"},
                {"code": "PB.2", "name": "Narrow-Sense Heritability (h²)", "formula": "h² = Va / Vp = Va / (Va + Vd + Vi + Ve)", "variables": "Va = additive genetic variance\nVd = dominance variance\nVi = epistatic variance\nVe = environmental variance", "purpose": "Estimate proportion of variation that is heritable + fixable by selection. h² determines response to selection — more actionable than H².", "example": "Maize yield: Va=0.8, Vd=0.3, Vi=0.1, Ve=1.3: h² = 0.8/2.5 = 0.32. Selection will capture 32% of observed variation.", "pitfall": "h² ≤ H² always. h² can be estimated from parent-offspring regression: h² = 2 × slope (half-sib) or 1 × slope (full-sib).", "decision": "Select for traits with h² >0.3 for reliable improvement. Below 0.15: use indirect selection or markers.", "notes": "Falconer & Mackay (1996). h² is the key parameter for breeder's equation.", "name_ar": "قابلية التوريث الضيقة", "purpose_ar": "تقدير الجزء القابل للتوريث والثابت بالانتخاب.", "variables_ar": "Va = التباين المضاف"},
                {"code": "PB.3", "name": "Response to Selection (Breeder's Equation)", "formula": "R = h² × S", "variables": "R = response (change in mean per generation)\nh² = narrow-sense heritability\nS = selection differential (selected mean − population mean)", "purpose": "Predict genetic gain per generation. Core equation of plant breeding. Higher h² or stronger selection → more gain.", "example": "Wheat protein, h²=0.4, select top 20% (S=3% above mean): R = 0.4 × 3 = 1.2% gain per generation. 5 generations → 6% increase.", "pitfall": "S decreases as selection intensity increases (fewer selected). Genetic variance is depleted over cycles.", "decision": "Balance selection intensity (S) with genetic diversity (avoid inbreeding).", "notes": "Lush (1937). Called 'realized heritability' when computed from actual response: h² = R/S.", "name_ar": "الاستجابة للانتخاب (معادلة المربي)", "purpose_ar": "التنبؤ بالكسب الوراثي لكل جيل.", "variables_ar": "R = الاستجابة\nh² = القابلية\nS = التفاضل الانتخابي"},
                {"code": "PB.4", "name": "Genetic Gain per Cycle", "formula": "ΔG = (i × h² × σp) / L", "variables": "i = selection intensity (1.4 for 20% selected, 2.1 for 5%)\nh² = narrow-sense heritability\nσp = phenotypic standard deviation\nL = length of breeding cycle (years)", "purpose": "Annual genetic gain — accounts for cycle time. Fast-cycling crops (1 yr) can gain 10× more per year than trees (10 yr cycle).", "example": "Wheat: i=1.4 (top 20%), h²=0.3, σp=0.5 t/ha, L=4 yr: ΔG = (1.4×0.3×0.5)/4 = 0.053 t/ha/yr = 53 kg/ha/yr.", "pitfall": "Speed breeding (off-season nurseries + greenhouse) reduces L → faster gain.", "decision": "Invest in reducing L: shuttle breeding, speed breeding, genomic selection.", "notes": "Eberhart (1970). Annual gain = ΔG. Compare crops: maize ~1%/yr, wheat ~0.5%, trees ~0.1%.", "name_ar": "الكسب الوراثي لكل دورة", "purpose_ar": "الكسب الوراثي السنوي.", "variables_ar": "i = شدة الانتخاب\nσp = الانحراف المعياري"},
                {"code": "PB.5", "name": "Heterosis (Hybrid Vigor)", "formula": "H = (F1 − MP) / MP × 100", "variables": "F1 = hybrid mean\nMP = mid-parent average = (P1 + P2) / 2", "purpose": "Measure hybrid vigor — % superiority of F1 over parent average. Corn hybrids show 15-25% heterosis. Basis of hybrid seed industry.", "example": "Parent A = 6 t/ha, Parent B = 4 t/ha, F1 = 8 t/ha: H = (8 − 5)/5 × 100 = 60%. Exceptional heterosis.", "pitfall": "Heterosis declines in F2 (Mendelian segregation). Farmers must buy new hybrid seed each season.", "decision": "Exploit heterosis in cross-pollinated crops (corn, sorghum, sunflower). Less in self-pollinated (wheat, rice).", "notes": "Shull (1908). Heterotic groups in corn: Reid Yellow Dent × Lancaster Sure Crop.", "name_ar": "قوة الهجين", "purpose_ar": "قياس تفوق الهجين على متوسط الوالدين.", "variables_ar": "F1 = متوسط الهجين\nMP = متوسط الوالدين"},
                {"code": "PB.6", "name": "Inbreeding Coefficient (F)", "formula": "F_t = 1 − (1 − F_{t-1}) × (1 − 1/(2N))\nFor random mating: F = 1/(2N) per generation", "variables": "N = effective population size\nF = probability of identical alleles by descent", "purpose": "Track inbreeding accumulation. Small populations → inbreeding depression (reduced vigor, fertility). F >0.1: noticeable decline.", "example": "Breeding population N=50: per generation F increase = 1/100 = 1%. After 10 generations: F ≈ 0.10 (10% inbred). Manageable.", "pitfall": "Effective N is often much smaller than census N (unequal sex ratio, variance in family size).", "decision": "Maintain N ≥100 to keep F <1%/generation. Use recurrent selection to maintain diversity.", "notes": "Wright (1922). Inbreeding depression: yield drops ~5% per 10% increase in F.", "name_ar": "معامل زواج الأقارب", "purpose_ar": "تتبع تراكم زواج الأقارب في التجمعات الصغيرة.", "variables_ar": "N = الحجم الفعال"},
                {"code": "PB.7", "name": "Selection Index (Multi-Trait)", "formula": "I = b1×X1 + b2×X2 + ... + bn×Xn\nb = P⁻¹Ga (optimal weights)", "variables": "Xi = trait values\nb = index weights\nP = phenotypic variance-covariance matrix\nG = genetic variance-covariance matrix\na = economic weights", "purpose": "Select for multiple traits simultaneously (yield + quality + disease resistance). Optimal weights maximize economic response. Standard in modern breeding.", "example": "Select wheat for yield (a=$200/t) + protein (a=$10/%): compute P⁻¹Ga → get b1, b2. Rank lines by I = b1×yield + b2×protein.", "pitfall": "Requires estimates of G + P matrices — often unreliable with small trials.", "decision": "Use simpler independent culling levels if data is limited. Reserve index selection for advanced programs.", "notes": "Smith (1936) + Hazel (1943). Modern: genomic selection uses genome-wide markers.", "name_ar": "مؤشر الانتخاب (متعدد الصفات)", "purpose_ar": "الانتخاب لصفات متعددة في وقت واحد.", "variables_ar": "Xi = قيم الصفات\nb = أوزان المؤشر"},
                {"code": "PB.8", "name": "Genetic Correlation", "formula": "rA = Cov_A(X,Y) / √(V_A(X) × V_A(Y))", "variables": "Cov_A = additive genetic covariance\nV_A = additive genetic variance for each trait", "purpose": "Measure genetic linkage between traits. Positive rA: selecting for one improves both. Negative rA: selecting for one worsens the other (trade-off).", "example": "Yield vs protein in wheat: rA = −0.5. Selecting for yield reduces protein. Need to balance — use selection index.", "pitfall": "Genetic correlation ≠ molecular linkage. Can be due to pleiotropy (one gene affects both traits) or LD.", "decision": "If rA <−0.3: use multi-trait selection. If rA >0.5: indirect selection is efficient.", "notes": "Falconer & Mackay (1996). rA is environment-specific — test across target environments.", "name_ar": "الارتباط الوراثي", "purpose_ar": "قياس الارتباط الوراثي بين صفتين.", "variables_ar": "Cov_A = التغاير الوراثي"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: Genetic gain (1%/yr yield increase) has prevented 100s of millions of hectares of land conversion. Breeding = most sustainable intensification."],
            "decision_boxes": ["▲  Decision: Invest in reducing breeding cycle time (L) — speed breeding + genomic selection can halve L, doubling annual gain."],
        }],
    },

    # ========================================================================
    # 6. WATER HARVESTING (6)
    # ========================================================================
    {
        "roman": "XXXVII", "title": "Water Harvesting",
        "chapters": [{
            "number": 37, "title": "Rainwater Collection & Storage",
            "intro": "Water harvesting captures rainfall for dry-season use — critical for arid + semi-arid agriculture. These formulas cover rooftop collection, cistern sizing, and micro-catchment design.",
            "sub_sections": [],
            "formulas": [
                {"code": "WH.1", "name": "Rooftop Rainwater Harvesting Volume", "formula": "V = A × R × C_r", "variables": "A = catchment area (m²)\nR = rainfall (mm)\nC_r = runoff coefficient (0.8 roof, 0.3 compacted soil, 0.1 vegetation)", "purpose": "Estimate harvestable rainwater from rooftop or catchment surface. Foundation of water harvesting system design.", "example": "100 m² metal roof, 400 mm annual rainfall: V = 100 × 0.4 × 0.8 = 32 m³ = 32,000 L/year. Enough for 87 L/day — sufficient for household + small garden.", "pitfall": "First flush (first 0.5 mm of rain) is dirty — divert with first-flush diverter. Reduces effective yield by ~5%.", "decision": "Metal/concrete roofs: C=0.8-0.9. Thatch: C=0.2-0.3 (contaminated).", "notes": "Pacey & Cullis (1986). WHO guidelines: rainwater safe for drinking if filtered + chlorinated.", "name_ar": "حصاد مياه الأمطار من الأسطح", "purpose_ar": "تقدير المياه القابلة للحصاد من سطح السقف.", "variables_ar": "A = مساحة الصرف\nR = المطر\nC_r = معامل الجريان"},
                {"code": "WH.2", "name": "Cistern Sizing (Monthly Balance)", "formula": "V_cistern = max(S_i) where S_i = Σ(Supply_j − Demand_j) for j=1 to i\nS_0 = 0, S_i ≥ 0", "variables": "Supply = monthly rainwater harvested (m³)\nDemand = monthly water demand (m³)\nS_i = cumulative storage at month i", "purpose": "Size cistern to bridge dry season. Track cumulative supply vs demand — cistern = peak storage needed. Oversizing wastes money; undersizing runs dry.", "example": "Monthly supply: [5, 8, 3, 0, 0, 0, 2, 6, 8]. Demand: 3 m³/month. Cumulative surplus: [2, 7, 7, 4, 1, -2...]. Max storage = 7 m³ (March). Cistern = 7 m³.", "pitfall": "Account for evaporation (open cisterns: 10-20% loss). Use covered tanks.", "decision": "Size for 1-in-5 dry year (use 80th percentile rainfall, not average).", "notes": "Task Force on Rainwater Harvesting (2009). Curve number method for more precise runoff.", "name_ar": "حجم الخزان", "purpose_ar": "تحديد حجم الخزان لجسر الموسم الجاف.", "variables_ar": "Supply = العرض الشهري\nDemand = الطلب الشهري"},
                {"code": "WH.3", "name": "Catchment-to-Crop Ratio", "formula": "R_catch = Crop_water_demand / Effective_rainfall", "variables": "Crop_water_demand = ETc (mm/season) on crop area\nEffective_rainfall = rainfall × 0.7 (mm) on catchment", "purpose": "Calculate catchment area needed per hectare of crop. In arid zones (200 mm rain, 600 mm ETc): need 3-4× more catchment than crop.", "example": "Tomatoes need 500 mm ETc, area gets 200 mm rain. R = 500/(200×0.7) = 3.6. Need 3.6 ha catchment per 1 ha crop. Large but feasible with micro-catchments.", "pitfall": "Runoff coefficient varies by surface + intensity. High-intensity rain → more runoff but also more erosion.", "decision": "Use micro-catchments (contour bunds, half-moons) to concentrate rainfall at plant root zone.", "notes": "Critchley & Siegert (1991) FAO Manual. Water harvesting is ancient — Nabataean systems in Petra.", "name_ar": "نسبة المساحة الماصة للمحصول", "purpose_ar": "حساب مساحة الصرف المطلوبة لكل هكتار محصول.", "variables_ar": "Crop_water_demand = احتياج المحصول\nEffective_rainfall = المطر الفعال"},
                {"code": "WH.4", "name": "Runoff Coefficient by Surface", "formula": "C = 1 − (I / R) × k", "variables": "I = infiltration rate (mm/hr)\nR = rainfall intensity (mm/hr)\nk = surface factor (0.8 roof, 0.5 compacted, 0.2 vegetated)", "purpose": "Estimate fraction of rainfall that runs off (harvestable). Metal roof: 0.85. Bare soil: 0.3. Grass: 0.1. Critical for catchment design.", "example": "Sandy loam, I=15 mm/hr, rain 30 mm/hr, k=0.5: C = 1−(15/30)×0.5 = 0.625. 62.5% runs off — good catchment.", "pitfall": "Infiltration decreases with soil crusting + compaction over time. Re-measure seasonally.", "decision": "Treat catchment surface: wax, sodium chloride, or Bitumen for higher C. Or compact bare soil.", "notes": "SCS Curve Number method is more rigorous — uses soil group + AMC + land use.", "name_ar": "معامل الجريان حسب السطح", "purpose_ar": "تقدير جزء المطر الذي يجري.", "variables_ar": "I = معدل الترشيح\nR = شدة المطر"},
                {"code": "WH.5", "name": "Swale/Infiltration Sizing", "formula": "V_swale = A_catch × R × C_r × safety_factor", "variables": "A_catch = upslope catchment area (m²)\nR = design rainfall event (m)\nC_r = runoff coefficient\nsafety_factor = 1.2", "purpose": "Size infiltration swale to capture + infiltrate design storm. Swales slow runoff + recharge groundwater + reduce erosion.", "example": "500 m² catchment, 50 mm design storm, C=0.4: V = 500 × 0.05 × 0.4 × 1.2 = 12 m³. Swale: 1m wide × 0.3m deep × 40m long = 12 m³ capacity.", "pitfall": "Swale overflows in extreme events. Design spillway for 1-in-10 storm.", "decision": "Swales + trees (agroforestry) = multi-benefit: water harvesting + carbon + fodder.", "notes": "Lancaster (2006) Rainwater Harvesting for Drylands. Keyline design by Yeomans.", "name_ar": "حجم الخندق", "purpose_ar": "تحديد حجم الخندق لالتقاط وتسريب العواصف.", "variables_ar": "A_catch = مساحة الصرف\nR = مطر التصميم"},
                {"code": "WH.6", "name": "Micro-Catchment Design (Contour Bund)", "formula": "D = √(V_plant / (R × C_r × 10))", "variables": "V_plant = water needed per plant (L/season)\nR = seasonal rainfall (mm)\nC_r = runoff coefficient\nD = catchment side length (m)", "purpose": "Design micro-catchment (negarim, half-moon, contour bund) per tree or plant. Concentrates runoff at root zone — enables tree planting in arid zones.", "example": "Olive tree needs 1500 L/season. Rainfall 250 mm, C=0.5: D = √(1500/(250×0.5×10)) = √1.2 = 1.1 m. Micro-catchment: 1.1×1.1 = 1.2 m² per tree.", "pitfall": "Micro-catchment area must be kept bare (weed-free) to maintain runoff. Maintenance is critical.", "decision": "Use for high-value trees (olive, fig, almond) in arid zones. Combine with mulch at root zone.", "notes": "Evenari et al. (1982) The Negev Desert. Ancient runoff farming systems rediscovered.", "name_ar": "تصميم المصغرة (حواجز كنتور)", "purpose_ar": "تصميم مصايد ميكروية لكل شجرة.", "variables_ar": "V_plant = احتياج الشجرة\nR = مطر الموسم"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: Water harvesting enables agriculture in 200-400 mm rainfall zones — converting marginal land to productive. No energy input required."],
            "decision_boxes": ["▲  Decision: Start with rooftop harvesting (highest ROI). Add micro-catchments for trees. Reserve cisterns for high-value irrigation."],
        }],
    },

    # ========================================================================
    # 7. LIVESTOCK HOUSING (6)
    # ========================================================================
    {
        "roman": "XXXVIII", "title": "Livestock Housing",
        "chapters": [{
            "number": 38, "title": "Ventilation & Space Design",
            "intro": "Proper livestock housing improves productivity, welfare, and disease control. These formulas cover ventilation sizing, space requirements, and bedding management — the engineering of animal shelters.",
            "sub_sections": [],
            "formulas": [
                {"code": "LH.1", "name": "Winter Minimum Ventilation Rate", "formula": "V_min = N × BW × 0.044 × (CO₂_prod / (CO₂_max − CO₂_outside))", "variables": "N = number of animals\nBW = body weight (kg)\nCO₂_prod = 0.18 L CO₂ per kg BW per hour\nCO₂_max = 3000 ppm (0.3%)\nCO₂_outside = 400 ppm", "purpose": "Size minimum winter ventilation to remove CO₂ + moisture without excessive heat loss. Too little → respiratory disease. Too much → cold stress + heating cost.", "example": "100 dairy cows, 600 kg each: V = 100×600×0.044×(0.18/(0.3−0.04)) = 18,000 L/hr = 18 m³/hr. Minimum — size fan for 2× this.", "pitfall": "Moisture (not CO₂) is usually the limiting factor in winter ventilation. Use humidity-based sizing.", "decision": "Use variable-speed fans controlled by RH sensor. Target RH 60-75%.", "notes": "MWPS-32 (Midwest Plan Service). ASABE Standards for livestock environment.", "name_ar": "معدل التهوية الشتوي الأدنى", "purpose_ar": "تحديد الحد الأدنى للتهوية الشتوية.", "variables_ar": "N = عدد الحيوانات\nBW = وزن الجسم"},
                {"code": "LH.2", "name": "Summer Maximum Ventilation Rate", "formula": "V_max = Q_heat / (ρ × cp × ΔT)", "variables": "Q_heat = total heat produced (W)\nρ = air density (1.2 kg/m³)\ncp = 1005 J/kg/°C\nΔT = allowable temp rise (2-3°C)", "purpose": "Size maximum summer ventilation to remove animal heat + solar load. Under-sized → heat stress → production loss + mortality.", "example": "100 lactating cows, 600 W each + 20 kW solar: Q = 60 + 20 = 80 kW. ΔT=2: V = 80000/(1.2×1005×2) = 33.2 m³/s = 70,400 CFM. Need 3× 25,000 CFM fans.", "pitfall": "Tunnel ventilation needs end-to-end air speed 2-3 m/s. Check inlet area matches fan capacity.", "decision": "Add cooling: sprinklers + fans for dairy. Evaporative cooling pads for poultry in hot climates.", "notes": "ASABE EP270. Heat stress costs US dairy $900M/year in lost production.", "name_ar": "معدل التهوية الصيفي الأقصى", "purpose_ar": "تحديد الحد الأقصى للتهوية الصيفية.", "variables_ar": "Q_heat = الحرارة المنتجة"},
                {"code": "LH.3", "name": "Space Requirement by Species", "formula": "A = k × BW^0.67", "variables": "k = species constant (dairy 2.5, beef 2.0, swine 1.5, poultry 0.05)\nBW = body weight (kg)", "purpose": "Calculate floor area per animal based on allometric scaling. Crowding → stress, injury, disease, reduced gain.", "example": "600 kg dairy cow: A = 2.5 × 600^0.67 = 2.5 × 22.8 = 5.7 m²/cow. 100-cow barn: 570 m².", "pitfall": "Lying area vs total area differ. Add alley + feed bunk + waterer space.", "decision": "Free-stall: 1.2× width + 1.8× length of cow. Bedded pack: 7-9 m²/cow.", "notes": "FAO (2012) Animal Welfare Standards. EU minimum: 6 m²/dairy cow, 0.75 m²/finish pig.", "name_ar": "متطلبات المساحة حسب النوع", "purpose_ar": "حساب مساحة الأرضية لكل حيوان.", "variables_ar": "k = ثابت النوع\nBW = وزن الجسم"},
                {"code": "LH.4", "name": "Bedding Requirement", "formula": "B = N × BW × k_bed", "variables": "N = number of animals\nBW = body weight (kg)\nk_bed = bedding rate (kg/kg BW/day):\nStraw: 0.002, Sawdust: 0.0015, Sand: 0.005", "purpose": "Estimate daily bedding requirement for comfort + moisture absorption. Insufficient bedding → mastitis + lameness.", "example": "100 dairy cows, 600 kg, straw: B = 100 × 600 × 0.002 = 120 kg straw/day = 44 t/year.", "pitfall": "Sand bedding doesn't decompose — manure management needs separate sand-settling lane.", "decision": "Deep-pack bedding: 4 kg/day/cow. Free-stall: 1 kg/day/cow fresh + weekly top-up.", "notes": "Compost bedding (pack) with added culture reduces need + generates heat in winter.", "name_ar": "متطلبات الفرشة", "purpose_ar": "تقدير الاحتياج اليومي للفرشة.", "variables_ar": "N = عدد الحيوانات\nk_bed = معدل الفرشة"},
                {"code": "LH.5", "name": "Manure Storage Sizing", "formula": "V_storage = N × (M_liquid + M_solid + wash_water) × days", "variables": "N = animals\nM_liquid = liquid manure production (L/day/animal)\nM_solid = solid manure (kg/day)\nwash_water = cleaning water (L/day)\ndays = storage period (120-180 typical)", "purpose": "Size manure storage to hold waste until land application (non-spreading season). Under-sized → illegal spreading + environmental contamination.", "example": "100 cows, 50 L/day manure + 20 L wash: V = 100 × 70 × 150 = 1,050,000 L = 1050 m³ storage. Earthen lagoon 20m × 25m × 2m deep.", "pitfall": "Add 20% for rainfall + safety freeboard. Cover to reduce odor + ammonia loss.", "decision": "Anaerobic lagoon + separator: liquid irrigated, solid composted. Or store as slurry in tank.", "notes": "NRCS Conservation Practice 359 (Waste Storage Facility). EPA CAFO rules: 180-day minimum.", "name_ar": "حجم تخزين السماد", "purpose_ar": "تحديد حجم تخزين السماد حتى التطبيق.", "variables_ar": "N = عدد الحيوانات\ndays = فترة التخزين"},
                {"code": "LH.6", "name": "Lighting for Laying Hens (Lux + Photoperiod)", "formula": "Lux_target = 20-40 lux at bird level\nPhotoperiod = 14-16 hr/day (constant from peak lay)", "variables": "Lux = illuminance at bird level\nPhotoperiod = hours of light per day", "purpose": "Optimize lighting for egg production. Too little light → reduced lay. Too much → stress + pecking. Photoperiod controls hormonal cascade for ovulation.", "example": "Laying house: 30 lux for 16 hr. Use LED warm-white (2700K) for calm behavior. Dim to 5 lux at night for rest.", "pitfall": "Never decrease photoperiod during lay — causes molt + production drop. Increase only.", "decision": "Use dawn/dusk dimming (30 min ramp) to prevent panic + piling. Program timer with season.", "notes": "Morris (2004). 1 lux ≈ 0.1 fc. LED saves 70% vs incandescent, 40% vs fluorescent.", "name_ar": "إضاءة الدجاج البياض", "purpose_ar": "تحسين الإضاءة لإنتاج البيض.", "variables_ar": "Lux = شدة الإضاءة\nPhotoperiod = ساعات الضوء"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: Proper housing reduces feed waste 10-20%, disease treatment 50%, and improves welfare — all reduce environmental footprint per kg product."],
            "decision_boxes": ["▲  Decision: Ventilation is #1 priority — under-sized fans cost more in lost production than the fan itself. Size for summer max, control with variable speed for winter min."],
        }],
    },

    # ========================================================================
    # 8. ADVANCED BEEKEEPING (5)
    # ========================================================================
    {
        "roman": "XXXIX", "title": "Advanced Beekeeping",
        "chapters": [{
            "number": 39, "title": "Colony Management & Health",
            "intro": "Beekeeping math — varroa monitoring, queen rearing schedules, colony population dynamics, pollination contracts, and winter prep. Essential for commercial apiary management.",
            "sub_sections": [],
            "formulas": [
                {"code": "BK.1", "name": "Varroa Mite Treatment Threshold", "formula": "Treat when: mites/day on sticky board ≥ 10 (summer) or ≥ 3 (fall)", "variables": "mites/day = natural drop on screened bottom board\nThreshold varies by season + colony strength", "purpose": "Determine when to treat varroa — #1 threat to honey bee colonies. Below threshold: monitor. Above: treat immediately.", "example": "72-hour sticky board count = 45 mites → 15/day. Summer threshold 10: treat now with formic acid or thymol.", "pitfall": "Alcohol wash is more accurate but kills sampled bees. Sugar shake is non-lethal but less accurate.", "decision": "Treat August-September for winter bee health. Late treatment → winter colony collapse.", "notes": "Honey Bee Health Coalition. IPM approach: resistant stock + screen bottoms + soft chemicals.", "name_ar": "عتبة علاج حلم الفاروا", "purpose_ar": "تحديد متى يعالج حلم الفاروا.", "variables_ar": "mites/day = العث يومياً"},
                {"code": "BK.2", "name": "Queen Rearing Schedule (Grafting → Emergence)", "formula": "Day 0: graft larvae\nDay 12: queen cells capped\nDay 16: queen emerges\nDay 23-28: mating flights\nDay 28-33: first eggs laid", "variables": "Queen development: 16 days from egg to emergence\nGrafting at 12 hr larval age", "purpose": "Schedule queen rearing — timing is precise. Graft too late → queen inferior. Emergence too late in mating nuc → virgins kill each other.", "example": "Graft May 1 → cells capped May 12 → emergence May 16 → mating May 23-28 → first eggs May 28.", "pitfall": "Weather during mating flights (day 7-12 post-emergence) is critical. Rain = poor mating → drone layers.", "decision": "Mark queens with year color (white/yellow/red/green/blue). Clip wings to prevent swarming.", "notes": "Doolittle (1889) grafting method. Jenter/Cupkit systems avoid grafting skill requirement.", "name_ar": "جدول تربية الملكات", "purpose_ar": "جدول دقيق لتربية الملكات من التطعيم إلى الظهور.", "variables_ar": "Day = اليوم من التطعيم"},
                {"code": "BK.3", "name": "Colony Population Model", "formula": "Bees(t) = Bees(0) × e^(−m×t) + Brood(t-21) × survival\nBrood development: egg→worker = 21 days", "variables": "Bees(0) = initial adult bee count\nm = daily mortality rate (0.01-0.02)\nBrood(t) = capped brood emerging at time t\nsurvival = 0.9 (10% die before emerging)", "purpose": "Model colony population dynamics. Predict when colony will peak, need supersing, or risk collapse. Queen lays 1500-2000 eggs/day at peak.", "example": "Colony with 30,000 bees, 10,000 capped brood, m=0.015: Day 21: Bees = 30000×e^(−0.015×21) + 10000×0.9 = 22,000 + 9,000 = 31,000. Stable — queen laying enough.", "pitfall": "Brood takes 21 days — queen decisions today affect colony 3 weeks later. Plan supering accordingly.", "decision": "If predicted population <15,000: add supplement (pollen patty + syrup). Or combine colonies.", "notes": "Sakofski (1990). BeePOP model (USDA). Population peaks 6-8 weeks after queen starts laying.", "name_ar": "نموذج تعداد المستعمرة", "purpose_ar": "نمذجة ديناميكيات عدد النحل في المستعمرة.", "variables_ar": "Bees = عدد النحل\nm = معدل الوفيات"},
                {"code": "BK.4", "name": "Pollination Contract Sizing", "formula": "Hives/ha = (flowers_per_m² × pollen_demand) / (bees_per_hive × collection_rate)", "variables": "flowers_per_m² = bloom density\npollen_demand = kg pollen per flower type\nbees_per_hive = 15,000-30,000 foragers\ncollection_rate = 0.01 kg pollen/bee/day", "purpose": "Determine hive density for commercial pollination contracts. Almonds need 2-3 hives/ha, apples 1-2, blueberries 4-5.", "example": "Almond orchard: 50 flowers/m², demand 0.001 kg/flower, 20000 bees/hive: hives = (50×10000×0.001)/(20000×0.01) = 2.5 hives/ha. Standard recommendation.", "pitfall": "Competition from wild pollinators reduces needed hives. But habitat loss means fewer wild bees.", "decision": "Place hives in groups of 4-8 at 100m intervals. Move in at 10% bloom, remove at petal fall.", "notes": "Delaplane & Mayer (2000). Almond pollination = 75% of US commercial bee revenue.", "name_ar": "حجم عقد التلقيح", "purpose_ar": "تحديد كثافة الخلايا للتلقيح التجاري.", "variables_ar": "flowers = كثافة الأزهار\nbees = عدد النحل"},
                {"code": "BK.5", "name": "Winter Survival Honey Stores", "formula": "Stores_needed = colony_size × consumption_rate × winter_days\nconsumption = 5-10 g honey/bee/month (clustered)", "variables": "colony_size = bees entering winter (15,000-30,000)\nwinter_days = days below 10°C\nconsumption = 0.2-0.3 g honey/bee/day (active)", "purpose": "Calculate honey reserves needed for winter survival. Starvation = #1 cause of winter colony loss. Better to over-feed than under-feed.", "example": "25,000 bees, 120 winter days, 0.25 g/day: Stores = 25000 × 0.25 × 120 = 750,000 g = 750 kg... that's too high. Use monthly: 25000 × 7 g × 4 months = 700,000 g... still high. Realistic: 15-25 kg honey per colony for winter.", "pitfall": "Winter consumption is lower (clustered bees = 5-10 g/month per bee). Active flight days use 10× more. Use 15-25 kg per colony as rule of thumb.", "decision": "Leave 1-2 full supers (15-20 kg each) for winter. Supplement with 5-10 kg sugar syrup (2:1) in fall.", "notes": "Seeley & Visscher (1985). Northern climates need 25+ kg. Southern (mild) need 10-15 kg.", "name_ar": "احتياطي العسل الشتوي", "purpose_ar": "حساب مخزون العسل اللازم لبقاء الشتاء.", "variables_ar": "colony_size = عدد النحل\nwinter_days = أيام الشتاء"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: Each hive pollinates 1-4 ha of crops worth $200-2000. Honey bees contribute $15B/year to US agriculture."],
            "decision_boxes": ["▲  Decision: Monitor varroa monthly (May-September). Treat proactively — by the time you see symptoms, colony is already doomed."],
        }],
    },

    # ========================================================================
    # 9. FODDER CONSERVATION (5)
    # ========================================================================
    {
        "roman": "XL", "title": "Fodder Conservation",
        "chapters": [{
            "number": 40, "title": "Hay & Haylage Management",
            "intro": "Fodder conservation bridges seasonal feed gaps. Hay (dry) and haylage (fermented) preserve forage quality for months. These formulas cover drying time, bale density, moisture targets, and storage loss.",
            "sub_sections": [],
            "formulas": [
                {"code": "FC.1", "name": "Hay Curing Time to 20% Moisture", "formula": "t = (M_initial − 20) / (ET₀ × k_dry × 0.5)", "variables": "M_initial = initial moisture (%)\nET₀ = evapotranspiration rate (mm/day)\nk_dry = drying efficiency (0.3-0.5 for swath)\n0.5 = moisture vs water depth conversion", "purpose": "Estimate hours needed to dry cut forage to safe baling moisture (≤20%). Baling too wet → mold + spontaneous combustion.", "example": "Alfalfa cut at 75% moisture, ET₀=5 mm: t = (75−20)/(5×0.4×0.5) = 55/1.0 = 55 hours ≈ 3 sunny days.", "pitfall": "Night humidity re-wets hay. Tedding (fluffing) speeds drying 30%. Conditioning (crimping) speeds 50%.", "decision": "If rain forecast <3 days: wait. If already cut + rain coming: ted + use preservative (propionic acid).", "notes": "Rotz et al. (1991). Large round bales can tolerate 25% moisture with preservative.", "name_ar": "وقت تجفيف القش إلى 20%", "purpose_ar": "تقدير الوقت اللازم لتجفيف العلف إلى رطوبة آمنة.", "variables_ar": "M_initial = الرطوبة الأولية\nET₀ = التبخر"},
                {"code": "FC.2", "name": "Bale Density + Storage DM", "formula": "DM_stored = V_bale × ρ_bale × DM%", "variables": "V_bale = bale volume (m³)\nρ_bale = bale density (kg/m³): round 150-200, square 200-300\nDM% = dry matter fraction", "purpose": "Calculate dry matter stored per bale. Helps inventory feed for winter ration planning.", "example": "Round bale 1.2m × 1.5m: V = π×0.6²×1.5 = 1.7 m³. At 180 kg/m³, 85% DM: DM = 1.7×180×0.85 = 260 kg DM/bale.", "pitfall": "Density varies by baler + operator. Weigh sample bales to calibrate.", "decision": "Higher density = less storage space + better fermentation (haylage). But costs more fuel + baler wear.", "notes": "ASABE S424.1. Round bale dimensions vary; use actual measured diameter + length.", "name_ar": "كثافة البالرة + التخزين", "purpose_ar": "حساب المادة الجافة المخزنة لكل بالرة.", "variables_ar": "V_bale = حجم البالرة\nρ_bale = الكثافة"},
                {"code": "FC.3", "name": "Haylage Moisture Target (Wrapped Bale)", "formula": "Target: 40-60% moisture (55% optimal)", "variables": "Below 40%: poor fermentation (not enough moisture for bacteria)\nAbove 60%: Clostridial fermentation (butyric acid + bad smell)\n55%: optimal lactic acid fermentation", "purpose": "Determine correct moisture for wrapped bale silage (haylage). Too dry = mold. Too wet = butyric (inedible).", "example": "Alfalfa wilted to 55%: wrap within 4 hr of baling. 4-6 layers stretch film. Ferments for 6-8 weeks before feeding.", "pitfall": "Puncture in wrap → oxygen enters → mold. Inspect bales weekly, repair holes with tape.", "decision": "Use moisture tester (Koster/microwave) before baling. If 65%: ted for 2 more hours.", "notes": "Muck et al. (2008). Wrapping within 4 hr is critical — delayed wrapping reduces quality 10-20%.", "name_ar": "رطوبة القش المخمر (المغلف)", "purpose_ar": "تحديد الرطوبة الصحيحة للقش المخمر المغلف.", "variables_ar": "Target = الهدف"},
                {"code": "FC.4", "name": "Wrapping Layers + Seal Quality", "formula": "Layers = 4 (minimum) to 6 (optimal) to 8 (long-term)\nO₂_permeability = k_film / layers", "variables": "k_film = film permeability (typical: 100 cm³/m²/day for 25µm stretch film)\nMore layers = lower O₂ = better fermentation", "purpose": "Determine stretch film layers for bale silage. Too few → O₂ ingress → spoilage. Too many → waste of expensive film.", "example": "6-month storage: 4 layers sufficient. 12-month: 6 layers. 18-month+: 8 layers. Film cost: $0.50-0.80/bale/layer.", "pitfall": "Apply film at 50-70% stretch (pre-stretch). Under-stretch = loose wrap. Over-stretch = tears.", "decision": "Use white film (reflects sun, keeps bale cool). Black film heats bale — quality loss.", "notes": "Huhnke (2003). Stretch film should be UV-stabilized for 12+ month outdoor life.", "name_ar": "طبقات الغلاف + جودة الختم", "purpose_ar": "تحديد عدد طبقات الفيلم للقش المخمر.", "variables_ar": "layers = الطبقات\nk_film = نفاذية الفيلم"},
                {"code": "FC.5", "name": "Dry Matter Loss in Storage", "formula": "DM_loss% = k_storage × months × (M_bale − 15) × depth_factor", "variables": "k_storage = loss rate: 0.3 (indoors dry), 0.8 (outdoors stacked), 2.0 (uncovered on ground)\nmonths = storage duration\nM_bale = bale moisture (%)\ndepth_factor = 1.0 (single layer), 1.5 (2-high), 2.0 (3-high)", "purpose": "Estimate dry matter loss during storage. Unprotected outdoor storage loses 15-30% DM. Indoor: 5%. Wrapped: 2-5%.", "example": "Round bales outdoors 6 months, 18% moisture, 2-high: loss = 0.8 × 6 × 3 × 1.5 = 21.6%. 22% of feed lost — expensive!", "pitfall": "Loss is invisible — you don't see the mold + oxidation. Only weigh bales before + after to measure.", "decision": "Stack indoors: worth $20-40/bale in saved feed. Or wrap (haylage) — loses only 3-5%.", "notes": "Russell et al. (1990). Highest loss at bottom + sides of stack (moisture wicking from ground).", "name_ar": "فقد المادة الجافة في التخزين", "purpose_ar": "تقدير فقد المادة الجافة أثناء التخزين.", "variables_ar": "k_storage = معدل الفقد\nmonths = مدة التخزين"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: Proper fodder conservation reduces feed waste 15-30% — less land needed for feed production, less methane from livestock fed moldy forage."],
            "decision_boxes": ["▲  Decision: Invest in covered storage before investing in bigger balers. A $5000 shed saves $10,000+ in feed losses over 5 years."],
        }],
    },
]

# ============================================================================
# Update JSON
# ============================================================================

def main():
    with open(DATA_PATH, 'r', encoding='utf-8') as f:
        data = json.load(f)

    new_formula_count = sum(len(ch.get('formulas', [])) for p in NEW_PARTS for ch in p.get('chapters', []))

    data['parts'].extend(NEW_PARTS)

    new_all_formulas = []
    for part in data['parts']:
        for chapter in part.get('chapters', []):
            for formula in chapter.get('formulas', []):
                formula['part'] = part['title']
                formula['chapter'] = chapter['title']
                formula['chapter_number'] = chapter.get('number')
                new_all_formulas.append(formula)
    data['all_formulas'] = new_all_formulas

    old_total = data['meta']['total_formulas']
    data['meta']['total_formulas'] = len(new_all_formulas)
    data['meta']['total_parts'] = len(data['parts'])
    data['meta']['total_chapters'] = sum(len(p.get('chapters', [])) for p in data['parts'])

    cats = {}
    for f in new_all_formulas:
        cat = f['part']
        cats[cat] = cats.get(cat, 0) + 1
    data['meta']['categories'] = cats

    with open(DATA_PATH, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Added {new_formula_count} new formulas across {len(NEW_PARTS)} new parts")
    print(f"Total formulas: {old_total} → {data['meta']['total_formulas']}")
    print(f"Total parts: {data['meta']['total_parts']}")
    print(f"Total chapters: {data['meta']['total_chapters']}")
    print("\nNew parts:")
    for part in NEW_PARTS:
        n = sum(len(c.get('formulas', [])) for c in part['chapters'])
        print(f"  {n:3d}  {part['title']} (Part {part['roman']})")

if __name__ == '__main__':
    main()
