#!/usr/bin/env python3
"""Add 21 formulas to reach 500 total."""
import json
from pathlib import Path

DATA_PATH = Path('/home/z/my-project/src/data/agri_formulas.json')

NEW_PARTS = [
    # ========================================================================
    # 1. AGRICULTURAL WASTE MANAGEMENT (6)
    # ========================================================================
    {
        "roman": "XLI", "title": "Agricultural Waste Management",
        "chapters": [{
            "number": 41, "title": "Waste Valorization & Circular Economy",
            "intro": "Agricultural waste — crop residue, manure, plastic, processing by-products — can be valorized into energy, fertilizer, or materials. These formulas quantify waste streams and their potential value.",
            "sub_sections": [],
            "formulas": [
                {"code": "AW.1", "name": "Crop Residue Production", "formula": "Residue = Yield × (R:S ratio)", "variables": "Yield = grain/seed yield (t/ha)\nR:S = residue-to-straw ratio (wheat 1.3, corn 1.0, rice 1.5)", "purpose": "Estimate crop residue produced per hectare. Essential for bioenergy planning, compost feedstock calculation, and erosion management (retain 30% for soil cover).", "example": "Wheat yields 4 t/ha: Residue = 4 × 1.3 = 5.2 t/ha. Retain 2 t for erosion (30%), harvest 3.2 t for bioenergy or compost.", "pitfall": "R:S ratio varies by variety + growing conditions. Drought reduces ratio.", "decision": "Never remove >50% of residue — soil organic matter + erosion protection lost.", "notes": "Lal (2005). Corn stover removal for ethanol is controversial — soil C depletion risk.", "name_ar": "إنتاج مخلفات المحصول", "purpose_ar": "تقدير كمية المخلفات لكل هكتار.", "variables_ar": "Yield = الإنتاج\nR:S = نسبة المخلفات للقش"},
                {"code": "AW.2", "name": "Composting Volume Reduction", "formula": "V_final = V_initial × (1 − DM_loss) × (ρ_initial / ρ_final)", "variables": "V_initial = starting pile volume (m³)\nDM_loss = dry matter loss (0.3-0.5)\nρ = bulk density (initial ~400, final ~600 kg/m³)", "purpose": "Estimate final compost volume. Composting reduces volume 40-70% — important for facility sizing + output planning.", "example": "Pile starts 100 m³, DM loss 40%, density 400→600: V_final = 100 × 0.6 × (400/600) = 40 m³. 60% volume reduction.", "pitfall": "Volume reduction ≠ mass reduction. Mass loss is mostly CO₂ + H₂O vapor.", "decision": "Size composting pad for 2× final product volume (turning space + active piles).", "notes": "Rynk et al. (1992) On-Farm Composting Handbook.", "name_ar": "تقليل حجم التسميد", "purpose_ar": "تقدير الحجم النهائي للسماد العضوي.", "variables_ar": "V_initial = الحجم الأولي\nDM_loss = فقد المادة الجافة"},
                {"code": "AW.3", "name": "Plastic Mulch Recovery Rate", "formula": "Recovery = (Mass_collected / Mass_applied) × 100", "variables": "Mass_collected = plastic retrieved (kg)\nMass_applied = plastic installed (kg)\nTypical: 60-80% recoverable", "purpose": "Measure plastic mulch recovery efficiency. Unrecovered plastic fragments contaminate soil for decades. Regulatory threshold approaching.", "example": "Applied 45 kg/ha plastic mulch, collected 31 kg: Recovery = 31/45 × 100 = 69%. 14 kg/ha fragments remain in soil.", "pitfall": "Photodegradation fragments plastic — can't collect pieces <5cm. Biodegradable mulch avoids issue.", "decision": "If recovery <70%: switch to biodegradable mulch (PBAT/PLA blends, ~3× cost but zero residue).", "notes": "EU Directive 2019/904 bans single-use plastics. Agricultural mulch exemptions expiring 2030.", "name_ar": "معدل استرجاع البلاستيك", "purpose_ar": "قياس كفاءة استرجاع البلاستيك الزراعي.", "variables_ar": "Mass_collected = المسترجع\nMass_applied = المطبق"},
                {"code": "AW.4", "name": "Anaerobic Lagoon Loading Rate", "formula": "LR = (N × VS_daily) / V_lagoon", "variables": "N = number of animals\nVS_daily = volatile solids per animal (kg/day)\nV_lagoon = lagoon volume (m³)\nSafe: <0.06 kg VS/m³/day", "purpose": "Size anaerobic waste lagoon to prevent overload + odor. Over-loaded lagoons go acid + smell terrible.", "example": "500 pigs, 0.3 kg VS/day each, 1000 m³ lagoon: LR = (500×0.3)/1000 = 0.15. Overloaded — double lagoon volume.", "pitfall": "Lagoon must be deeper than 3m for anaerobic zone. Shallow lagoons = odor problems.", "decision": "If LR >0.06: add separator (removes 30% solids), increase volume, or switch to digester.", "notes": "ASABE EP403.2. NRCS has lagoon sizing standards per animal type.", "name_ar": "معدل تحميل البحيرة اللاهوائية", "purpose_ar": "تحديد حجم بحيرة النفايات اللاهوائية.", "variables_ar": "N = عدد الحيوانات\nVS = المواد الصلبة المتطايرة"},
                {"code": "AW.5", "name": "Bioplastics from Starch — Yield", "formula": "Yield = starch_content × conversion_eff × plastic_density", "variables": "starch_content = starch % of crop (corn 70%, potato 20%)\nconversion_eff = 0.6 (starch → PLA)\nplastic_density = 1.24 g/cm³", "purpose": "Estimate bioplastic (PLA) yield from starch crops. Replaces petroleum-based plastics with biodegradable alternative.", "example": "1 t corn grain at 70% starch: PLA = 1000 × 0.7 × 0.6 = 420 kg PLA. At 1.24 g/cm³: 339 L volume.", "pitfall": "PLA needs industrial composting (60°C) to biodegrade — home compost too cold.", "decision": "PHA (from bacteria) biodegrades in marine environments — better than PLA but 3× cost.", "notes": "NatureWorks (Ingeo PLA). Global bioplastics market: 2.4 Mt/yr (2023), growing 20%/yr.", "name_ar": "اللدائن الحيوية من النشا", "purpose_ar": "تقدير إنتاج اللدائن الحيوية من محاصيل النشا.", "variables_ar": "starch_content = نسبة النشا"},
                {"code": "AW.6", "name": "Waste-to-Wealth Value Recovery", "formula": "V_recovered = Σ(product_value × yield) − processing_cost", "variables": "product_value = $/unit of recovered product\nyield = quantity recovered\nproducts: biogas, compost, animal feed, biochar", "purpose": "Calculate net value from agricultural waste valorization. Positive = profitable. Identifies best waste-to-wealth pathway.", "example": "10 t manure → biogas $200 + compost $400 − processing $150 = $450 net value. Better than land application ($100 fertilizer value).", "pitfall": "Processing cost includes labor + energy + capital depreciation — often underestimated.", "decision": "Rank pathways by V_recovered. Co-product biogas + digestate is usually highest.", "notes": "Ellen MacArthur Foundation circular economy framework. EU Bioeconomy Strategy 2030.", "name_ar": "استرداد القيمة من النفايات", "purpose_ar": "حساب القيمة الصافية من تحويل النفايات لمنتجات.", "variables_ar": "product_value = قيمة المنتج"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: Agricultural waste valorization reduces disposal costs + generates revenue + avoids methane emissions from open decomposition."],
            "decision_boxes": ["▲  Decision: Map all waste streams on your farm. For each, compute V_recovered for 3-4 pathways. Invest in the highest-value option."],
        }],
    },

    # ========================================================================
    # 2. ORGANIC CERTIFICATION & STANDARDS (5)
    # ========================================================================
    {
        "roman": "XLII", "title": "Organic Certification & Standards",
        "chapters": [{
            "number": 42, "title": "Transition Planning & Compliance",
            "intro": "Organic certification opens premium markets but requires 36-month transition + strict input compliance. These formulas help plan the transition economics + buffer zone requirements.",
            "sub_sections": [],
            "formulas": [
                {"code": "OC.1", "name": "Organic Transition Period (36 Months)", "formula": "Eligible_date = Last_prohibited_input_date + 36 months", "variables": "Last_prohibited_input = date of last synthetic fertilizer/pesticide application\n36 months = USDA/NOP minimum", "purpose": "Calculate when land becomes eligible for organic certification. Transition period ensures soil + ecosystem free of prohibited substances.", "example": "Last synthetic N applied March 15, 2025. Eligible: March 15, 2028. First organic harvest: any crop harvested after this date.", "pitfall": "Buffer zone + parallel production rules apply during transition — can't sell as organic until certified.", "decision": "Plant perennial crops (alfalfa, clover) during transition — builds soil + N for first organic crop.", "notes": "USDA NOP 7 CFR 205. EU: 24 months. IFOAM: 12-36 months depending on history.", "name_ar": "فترة التحول العضوي (36 شهر)", "purpose_ar": "حساب متى تصبح الأرض مؤهلة للشهادة العضوية.", "variables_ar": "Last_prohibited = آخر تطبيق محظور"},
                {"code": "OC.2", "name": "Buffer Zone Width (Organic)", "formula": "W_buffer = max(8m, drift_distance × 1.5)", "variables": "drift_distance = expected pesticide drift distance (m)\nMinimum: 8m (USDA NOP) or 6m (EU)", "purpose": "Determine buffer zone between organic + conventional fields. Prevents spray drift contamination. Insufficient buffer = decertification.", "example": "Adjacent conventional field sprays glyphosate with 5m drift: W = max(8, 7.5) = 8m minimum buffer. Plant hedgerow for physical barrier.", "pitfall": "Buffer zone crops can't be sold as organic — use for personal use or leave fallow.", "decision": "Plant 8m+ hedgerow (trees + shrubs) — acts as buffer + pollinator habitat + windbreak.", "notes": "USDA NOP 205.202. EU 889/2008. Some certifiers require 15m for high-drift areas.", "name_ar": "عرض المنطقة العازلة (عضوي)", "purpose_ar": "تحديد عرض المنطقة العازلة بين الحقول العضوية والتقليدية.", "variables_ar": "drift_distance = مسافة الانجراف"},
                {"code": "OC.3", "name": "Organic Premium Price Analysis", "formula": "Premium% = (P_organic − P_conventional) / P_conventional × 100", "variables": "P_organic = organic selling price ($/kg)\nP_conventional = conventional price", "purpose": "Calculate price premium for organic products. Typical: 20-100%. Justifies transition costs + lower yields.", "example": "Organic wheat $0.40/kg, conventional $0.25/kg: Premium = (0.40-0.25)/0.25 = 60%. Need to offset 20% yield gap + certification cost.", "pitfall": "Premiums vary by market channel: direct-to-consumer 50-100%, wholesale 20-40%.", "decision": "If premium <30%: transition may not be profitable. Consider regenerative (non-certified) premium instead.", "notes": "USDA Organic Market Report. Global organic market: $130B (2023), growing 8-12%/yr.", "name_ar": "تحليل علاوة السعر العضوي", "purpose_ar": "حساب علاوة السعر للمنتجات العضوية.", "variables_ar": "P_organic = السعر العضوي\nP_conventional = السعر التقليدي"},
                {"code": "OC.4", "name": "Compliant Input Check (OMRI List)", "formula": "Allowed = (substance ∈ NOP_list) AND (use_method ∈ approved_uses)", "variables": "NOP_list = National Organic Program allowed substances\napproved_uses = specific applications (soil amendment, pest control, etc.)", "purpose": "Verify if an input is allowed for organic production. Using prohibited substance = decertification + 36-month re-transition.", "example": "Copper sulfate: allowed for fungal control (maximum 6 kg/ha/yr). Glyphosate: prohibited — zero tolerance.", "pitfall": "Generic names differ from brand names. Always check OMRI/WSDA listing for specific product.", "decision": "Keep receipts + labels of all inputs for audit trail. When in doubt, don't use.", "notes": "OMRI (Organic Materials Review Institute). USDA NOP National List 205.601-602.", "name_ar": "فحص المدخلات المسموحة (OMRI)", "purpose_ar": "التحقق من إذن مدخل للإنتاج العضوي.", "variables_ar": "NOP_list = قائمة البرنامج الوطني العضوي"},
                {"code": "OC.5", "name": "Organic Yield Gap Estimation", "formula": "Y_gap = (Y_conventional − Y_organic) / Y_conventional × 100", "variables": "Y_conventional = conventional yield (t/ha)\nY_organic = organic yield\nTypical gap: 10-25%", "purpose": "Quantify yield penalty from organic farming. Must be offset by price premium + lower input costs for profitability.", "example": "Conventional corn 10 t/ha, organic 8 t/ha: Y_gap = 20%. At 60% price premium: revenue organic = 8×1.6 = 12.8 vs conventional 10×1.0 = 10. Organic wins.", "pitfall": "Yield gap narrows over time (soil biology improves). Year 1-3 gap is largest.", "decision": "If gap >30%: focus on soil building (cover crops, compost) before transitioning cash crops.", "notes": "Seufert et al. (2012) Nature. Organic yields 75-80% of conventional on average; 5% gap in best systems.", "name_ar": "تقدير فجوة الإنتاج العضوي", "purpose_ar": "تحديد فرق الإنتاج بين العضوي والتقليدي.", "variables_ar": "Y_conventional = الإنتاج التقليدي"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: Organic farming reduces pesticide use 98% + synthetic fertilizer 100% + builds soil biodiversity + pollinator habitat."],
            "decision_boxes": ["▲  Decision: Start transition with high-premium crops (herbs, berries, vegetables). Use 3-year transition for soil building (cover crops + compost)."],
        }],
    },

    # ========================================================================
    # 3. CLIMATE-SMART AGRICULTURE (5)
    # ========================================================================
    {
        "roman": "XLIII", "title": "Climate-Smart Agriculture",
        "chapters": [{
            "number": 43, "title": "Adaptation & Mitigation Metrics",
            "intro": "Climate-smart agriculture simultaneously adapts to climate change + reduces emissions + maintains productivity. These formulas quantify climate resilience + carbon footprint per unit of food.",
            "sub_sections": [],
            "formulas": [
                {"code": "CS.1", "name": "Carbon Intensity per Unit Food (kg CO₂e/kg)", "formula": "CI = (Total_emissions) / (Crop_yield × area)", "variables": "Total_emissions = N₂O + CH₄ + fuel_CO₂ + input_CO₂ (kg CO₂e/ha)\nYield = t/ha\nArea = ha", "purpose": "Calculate carbon footprint per kg of food produced. Lower = more climate-efficient. Consumers + retailers increasingly demand this metric.", "example": "Wheat: N₂O 300 + fuel 100 + fertilizer_mfg 400 = 800 kg CO₂e/ha. Yield 5 t: CI = 800/5 = 160 kg CO₂e/kg... too high. Recompute: 800/5 = 160 g CO₂e/kg = 0.16 kg. Good (wheat average 0.5-1.0 kg).", "pitfall": "Include ALL emissions: fertilizer manufacturing (40% of total), transport, machinery. Not just field emissions.", "decision": "Target: reduce CI 20% in 5 years. Levers: less N, no-till, cover crops, solar pumping.", "notes": "Cool Farm Tool (www.coolfarm.org). SAI Platform Flourishing 2.0 benchmark.", "name_ar": "كثافة الكربون لكل وحدة طعام", "purpose_ar": "حساب البصمة الكربونية لكل كجم طعام.", "variables_ar": "Total_emissions = إجمالي الانبعاثات\nYield = الإنتاج"},
                {"code": "CS.2", "name": "Drought Resilience Score", "formula": "DRS = (TAW × rooting_depth × water_use_eff × soil_OM_factor) / ET₀_peak", "variables": "TAW = total available water (mm)\nrooting_depth = effective root depth (m)\nwater_use_eff = WUE relative to benchmark\nsoil_OM_factor = 1 + OM%/5\nET₀_peak = peak ET₀ (mm/day)", "purpose": "Score farm's drought resilience. Higher = more resilient. Combines soil water holding + rooting + WUE + organic matter. Used for climate risk assessment.", "example": "TAW 120mm, roots 1.2m, WUE 1.0, OM 2%: DRS = (120×1.2×1.0×1.4)/6 = 33.6. Compare: degraded soil TAW 80, roots 0.6m, OM 1%: DRS = (80×0.6×0.8×1.2)/6 = 7.7. 4× more resilient.", "pitfall": "DRS is relative — compare to regional benchmark, not absolute threshold.", "decision": "Improve DRS: add OM (compost/cover crop), deep-rooting varieties, deficit irrigation.", "notes": "FAO Climate-Smart Agriculture Sourcebook. World Bank Climate-Smart Agriculture profiles.", "name_ar": "مؤشر مرونة الجفاف", "purpose_ar": "تقييم مرونة المزرعة ضد الجفاف.", "variables_ar": "TAW = المياه المتاحة\nrooting_depth = عمق الجذور"},
                {"code": "CS.3", "name": "Heat Tolerance Index (Livestock)", "formula": "HTI = THI_exposure_hours × sensitivity_factor / acclimation_factor", "variables": "THI_exposure = hours/day where THI > 80 (cattle)\nsensitivity = 1.0 (Holstein), 0.7 (Brahman)\nacclimation = 1.0 (no), 0.7 (acclimated 30+ days)", "purpose": "Score livestock heat stress exposure. HTI >30: severe — milk drops 20%+, fertility crashes. Guides cooling investment.", "example": "Holstein in 35°C, 70% RH: THI=85, 8 hr exposure. HTI = 8×1.0×1.0 = 8. Moderate. Install fans + sprinklers.", "pitfall": "Night-time THI is critical — cattle can't cool down if nights stay warm.", "decision": "HTI >15: invest in shade + fans + sprinklers. HTI >30: consider moving to cooler microclimate.", "notes": "Renaudeau et al. (2012). THI = T − (0.55−0.0055×RH)×(T−14.4).", "name_ar": "مؤشر تحمل الحرارة (المواشي)", "purpose_ar": "تقييم تعرض المواشي لإجهاد الحرارة.", "variables_ar": "THI = مؤشر الحرارة-الرطوبة"},
                {"code": "CS.4", "name": "Water Productivity (kg/m³)", "formula": "WP = Yield / ET_actual", "variables": "Yield = crop yield (kg/ha)\nET_actual = actual evapotranspiration (m³/ha)\nTypical: wheat 1.0, maize 1.5, rice 0.5, potato 4.0 kg/m³", "purpose": "Measure kg of food produced per m³ of water consumed. Higher = more water-efficient. Key metric for water-scarce regions.", "example": "Maize yields 8 t/ha, ET_actual 5000 m³: WP = 8000/5000 = 1.6 kg/m³. Good — above global average (1.5).", "pitfall": "WP is different from irrigation efficiency. WP = crop output / total water consumed (rain + irrigation).", "decision": "Improve WP: deficit irrigation (20% less water, 5% yield loss → WP up 19%), mulching, drought-tolerant varieties.", "notes": "Zwart & Bastiaanssen (2004). FAO Water Productivity Framework. C4 crops (maize) inherently higher WP than C3 (wheat).", "name_ar": "إنتاجية المياه (كجم/م³)", "purpose_ar": "قياس كجم طعام لكل م³ ماء مستهلك.", "variables_ar": "Yield = الإنتاج\nET_actual = التبخر الفعلي"},
                {"code": "CS.5", "name": "Climate Adaptation ROI", "formula": "ROI_adapt = (Avoided_loss − Adaptation_cost) / Adaptation_cost × 100", "variables": "Avoided_loss = expected yield loss × probability × crop_value\nAdaptation_cost = investment (irrigation, shade, varieties, drainage)\nROI > 0: adaptation pays off", "purpose": "Evaluate return on climate adaptation investments. Justifies spending on resilience before disaster strikes.", "example": "Drought irrigation system $2000/ha. Expected drought loss without it: $3000/ha × 25% probability = $750 expected. ROI = (750-2000)/2000 = -62.5%. Not profitable at 25% probability. At 50%: ROI = (1500-2000)/2000 = -25%. At 75%: ROI = +12.5%.", "pitfall": "Probability estimates are uncertain. Use climate model projections (CMIP6) for 2030-2050.", "decision": "If ROI >0 at projected probability: invest. If <0: monitor + revisit in 5 years as climate changes.", "notes": "World Bank Climate Investment Funds. GCF Green Climate Fund finances adaptation in developing countries.", "name_ar": "عائد الاستثمار في التكيف المناخي", "purpose_ar": "تقييم عائد الاستثمار في تكيف المزرعة مع المناخ.", "variables_ar": "Avoided_loss = الخسارة المتوقعة"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: Climate-smart practices (no-till, cover crops, efficient irrigation, agroforestry) simultaneously reduce emissions + build resilience + improve soil."],
            "decision_boxes": ["▲  Decision: Calculate Carbon Intensity (CS.1) for your top 3 crops. If >0.5 kg CO₂e/kg: implement 3 mitigation practices (less N, no-till, cover crop)."],
        }],
    },

    # ========================================================================
    # 4. ON-FARM RESEARCH & TRIALS (5)
    # ========================================================================
    {
        "roman": "XLIV", "title": "On-Farm Research & Trials",
        "chapters": [{
            "number": 44, "title": "Trial Design & Analysis",
            "intro": "On-farm research validates practices under real conditions. These formulas help design statistically valid trials + interpret results — turning farmer observations into evidence-based decisions.",
            "sub_sections": [],
            "formulas": [
                {"code": "FR.1", "name": "Minimum Replicate Number", "formula": "n = (2 × (Z_α/2 + Z_β)² × σ²) / Δ²", "variables": "Z_α/2 = 1.96 (95% confidence)\nZ_β = 0.84 (80% power)\nσ = standard deviation of trait\nΔ = minimum detectable difference", "purpose": "Determine number of field replicates needed to detect a treatment effect. Too few = inconclusive. Too many = waste of land + effort.", "example": "Wheat yield σ=0.5 t/ha, want to detect 0.3 t/ha difference: n = (2×7.84×0.25)/0.09 = 43. Way too many for on-farm. Accept 0.5 t/ha: n = (2×7.84×0.25)/0.25 = 15. Feasible.", "pitfall": "On-farm trials use large plots — fewer reps but more representative. Use RCBD with 4-6 reps minimum.", "decision": "If n >6: increase Δ (accept larger difference) or use paired comparison (reduces variability).", "notes": "Gomez & Gomez (1984) Statistical Procedures for Agricultural Research. Standard text.", "name_ar": "الحد الأدنى للتكرارات", "purpose_ar": "تحديد عدد التكرارات المطلوبة لكشف تأثير المعاملة.", "variables_ar": "Z = قيم Z\nσ = الانحراف المعياري\nΔ = الفرق الأدنى القابل للكشف"},
                {"code": "FR.2", "name": "Least Significant Difference (LSD)", "formula": "LSD = t_α/2 × √(2 × MSE / r)", "variables": "t_α/2 = t-value at α=0.05, df = error df\nMSE = mean square error from ANOVA\nr = number of replications", "purpose": "Calculate minimum yield difference that is statistically significant. If difference between two treatments > LSD: real effect. Below LSD: could be random.", "example": "MSE=0.3, r=4 reps, df=9: t=2.26. LSD = 2.26×√(2×0.3/4) = 2.26×0.387 = 0.87 t/ha. Treatment A 8.0 vs B 7.0: difference 1.0 > 0.87 → significant.", "pitfall": "LSD only valid after ANOVA shows significant F-test. Don't use LSD on non-significant ANOVA.", "decision": "If LSD > expected treatment difference: increase replications or reduce variability (uniform plots).", "notes": "Fisher (1935). Protected LSD — only compare after significant F-test. Multiple comparison corrections (Tukey, Bonferroni) are stricter.", "name_ar": "أقل فرق معنوي (LSD)", "purpose_ar": "حساب الحد الأدنى للفرق ذي الدلالة الإحصائية.", "variables_ar": "t = قيمة t\nMSE = متوسط مربع الخطأ\nr = التكرارات"},
                {"code": "FR.3", "name": "Economic Optimum N Rate (EONR)", "formula": "EONR = N where: ∂Yield/∂N = Price_N / Price_crop", "variables": "∂Yield/∂N = marginal yield increase per kg N\nPrice_N = $/kg N\nPrice_crop = $/kg crop", "purpose": "Find N rate that maximizes profit (not yield). At EONR, last kg of N added returns exactly its cost. Applying more loses money.", "example": "Quadratic response: Y = 3 + 0.04N − 0.0001N². Price_N=$1, Price_crop=$0.20. EONR: 0.04−0.0002N = 1/0.20 = 5 → 0.04−0.0002N = 5... solve: N = (0.04−5)/0.0002... adjust units. Practically: use yield response curves from local trials.", "pitfall": "EONR varies by year (weather) + soil (N mineralization). Use 5-year average + adjust for current conditions.", "decision": "Apply EONR + 10% safety (risk-averse). Or use MRTN (Maximum Return to N) online tool.", "notes": "USDA MRTN tool: ncrc.agron.iastate.edu. Work by Sawyer et al. (2006).", "name_ar": "معدل النيتروجين الاقتصادي الأمثل", "purpose_ar": "إيجاد معدل N الذي يزيد الربح.", "variables_ar": "∂Yield/∂N = الزيادة الحدية\nPrice_N = سعر N"},
                {"code": "FR.4", "name": "Coefficient of Variation (CV%) for Trial Quality", "formula": "CV = (SD / Mean) × 100", "variables": "SD = standard deviation of yields\nMean = average yield\nCV <15%: good trial, CV >25%: unreliable", "purpose": "Assess trial quality. High CV means too much field variability — results unreliable. Low CV means trial was well-controlled.", "example": "Plot yields: 7.2, 7.8, 6.9, 7.5, 7.3. Mean=7.34, SD=0.33. CV = 0.33/7.34 × 100 = 4.5%. Excellent — reliable data.", "pitfall": "CV is trait-dependent. Yield CV 5-15% normal; quality traits 2-5%; disease scores 20-40%.", "decision": "If CV >20%: redo trial with more uniform field, more reps, or smaller plots.", "notes": "Gomez & Gomez (1984). CV is calculated from ANOVA error term, not raw data SD.", "name_ar": "معامل الاختلاف (CV%)", "purpose_ar": "تقييم جودة التجربة.", "variables_ar": "SD = الانحراف المعياري\nMean = المتوسط"},
                {"code": "FR.5", "name": "Partial Factor Productivity (PFP) for N", "formula": "PFP = Yield / N_applied", "variables": "Yield = crop yield (kg/ha)\nN_applied = nitrogen applied (kg/ha)\nTarget: >60 (cereals), >40 (vegetables)", "purpose": "Simplest N use efficiency metric. Measures kg crop produced per kg N applied. High PFP = efficient. Low = wasting N.", "example": "Wheat yields 5000 kg/ha with 150 kg N: PFP = 5000/150 = 33.3. Below target of 60 — improve: split applications, use inhibitors, match timing to crop demand.", "pitfall": "PFP doesn't account for soil N supply. High PFP may mean mining soil N (unsustainable).", "decision": "Track PFP over years. Declining PFP = soil N depletion. Improve with cover crops + compost.", "notes": "Cassman et al. (2002). PFP = AE (agronomic efficiency) × RE (recovery efficiency). Decompose for diagnosis.", "name_ar": "إنتاجية عامل النيتروجين الجزئي", "purpose_ar": "أبسط مؤشر لكفاءة استخدام النيتروجين.", "variables_ar": "Yield = الإنتاج\nN_applied = النيتروجين المطبق"},
            ],
            "summary_tables": [],
            "sustainability_notes": ["♻  Sustainability: On-farm research generates locally-relevant data, reducing blanket recommendations that over- or under-apply inputs."],
            "decision_boxes": ["▲  Decision: Partner with extension service for trial design. Even simple strip trials (treated vs untreated) generate valuable data if replicated 4+ times."],
        }],
    },
]

def main():
    with open(DATA_PATH, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    new_count = sum(len(ch.get('formulas', [])) for p in NEW_PARTS for ch in p.get('chapters', []))
    data['parts'].extend(NEW_PARTS)
    
    new_all = []
    for part in data['parts']:
        for ch in part.get('chapters', []):
            for f in ch.get('formulas', []):
                f['part'] = part['title']
                f['chapter'] = ch['title']
                f['chapter_number'] = ch.get('number')
                new_all.append(f)
    data['all_formulas'] = new_all
    
    old = data['meta']['total_formulas']
    data['meta']['total_formulas'] = len(new_all)
    data['meta']['total_parts'] = len(data['parts'])
    data['meta']['total_chapters'] = sum(len(p.get('chapters', [])) for p in data['parts'])
    
    cats = {}
    for f in new_all:
        cats[f['part']] = cats.get(f['part'], 0) + 1
    data['meta']['categories'] = cats
    
    with open(DATA_PATH, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"Added {new_count} formulas across {len(NEW_PARTS)} parts")
    print(f"Total: {old} → {data['meta']['total_formulas']}")
    print(f"Parts: {data['meta']['total_parts']}")
    print(f"Chapters: {data['meta']['total_chapters']}")
    for p in NEW_PARTS:
        n = sum(len(c.get('formulas', [])) for c in p['chapters'])
        print(f"  {n}  {p['title']} ({p['roman']})")

if __name__ == '__main__':
    main()
